### ISSUE TITLE
tests unitaires des vues

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#100]
- [x] Tester la liste des contenus (online/offline)
- [x] Tester le diff (pas d'erreur 500 sur le premier diff, diff disponible sur 2 versions)
- [x] Warn typo sur un tutoril n'ayant que External comme auteur
- [x] Import d'un manifest incorrect
- [x] Import d'une archive ancienne version
- [x] DownloadOnlineContent
- [x] 301 sur les vieilles urls
- [x] Send/Editnote avec des mauvais paramètres
- [x] Alert/Solve avec des mauvais paramètres
- [x] Liste de validation (historique de validation, liste de validation et filtres sur celle-ci)
- [x] `last_read_note()` et `first_unread_note()` (y compris en mode déconnecté)
- [x] les flux rss et atom
- [x] Import avec archive d'image.

**Comment by pierre-24** [comment]
... Tout un programme ;-)

**Comment by pierre-24** [comment]
Et sinon, notre `utils.py` a une couverture proprement dégeulasse ^^

**Comment by artragis** [comment]
Oui, parce que les vues l'utilisant ne sont pas testées.

Et parce qu'on a parfois codé deux fois les choses, une fois dans utils, une fois dans les vues. Je regarde ça ce midi.

**Comment by artragis** [comment]
et une de moins :)

**Comment by artragis** [comment]
@pierre-24 un de tes tests semble foirer oO

**Comment by pierre-24** [comment]
Encore ? Mais ?

**Comment by artragis** [comment]
https://travis-ci.org/artragis/zds-site/jobs/70413769

**Comment by pierre-24** [comment]
Bon, ça m'amuse pas, parce qu'il plante une fois sur deux. Ça sens le bug mystique --"

**Comment by pierre-24** [comment]
(oui, j'ai déjà testé avec mysql et non, j'arrive pas à le reproduire en local)

**Comment by artragis** [comment]
j'ai relancé. On pourra doser la mysticité du truc.

**Comment by pierre-24** [comment]
Il est passé. Tu la sens la mysticité ? :-°

**Comment by artragis** [comment]
travis fait vraiment beaucoup de merde en fait.

**Comment by pierre-24** [comment]
Mouais. Je vais garder Travis à l'oeil ces prochains temps, pour voir un peu si ça se produit de manière régulière ou pas.
