### ISSUE TITLE
Faire comprendre à la dropdown qu'on est bien dans les articles

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#114]
Je sais pas comment s'appelle cette petite barre jaune, mais quand on visite la liste des articles ou un article, bah il faudrait qu'elle soit affiché en dessous de "articles":

![screenshot from 2015-05-16 22 07 09](https://cloud.githubusercontent.com/assets/7889675/7668769/0e03ce70-fc18-11e4-84e8-bbe5591f6db5.png)

Je n'ai parfaitement aucune idée de ou c'est géré :o

**Comment by Eskimon** [comment]
Indice pour la mise en forme : il faut rajouter la classe "current" au bon moment...

**Comment by pierre-24** [comment]
Ah, ok ;)

**Comment by Eskimon** [comment]
fix incoming !

**Comment by artragis** [comment]
je passe en need qa.

**Comment by Vayel** [comment]
Problème ici : http://zds.francoisdambrine.me/articles2/58/qa58/

**Comment by pierre-24** [comment]
Toutafé :o

**Comment by pierre-24** [comment]
Normalement réglé :)

**Comment by Vayel** [comment]
Malheureusement non : http://zds.francoisdambrine.me/articles2/64/qa28/

Mais d'ailleurs on a le même problème avec les tutos : http://zds.francoisdambrine.me/tutoriels2/66/pa/

**Comment by artragis** [comment]
attends que je mette mon serveur à jour stp!

je viens de le faire y'a deux secondes.

**Comment by Vayel** [comment]
Oups pardon ! 

J'ai une 502 pour le serveur là.

**Comment by artragis** [comment]
fixed

**Comment by Vayel** [comment]
Parfait (pour les deux :P).
