### ISSUE TITLE
Achever la doc de la ZEP-12

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#115]
Maintenant que RTD a terminé de nous ennuyer et que tout le monde est sensé pouvoir la compiler, il faudrait:
- [x] mettre à jour la page de la ZEP-12, entre autre la publication, et la migration
- [x]  quelques _screens_ de l'interface (pas fait, abandonné pour cause de guide du contributeur)
- [x] rajouter la documentation de nos nouveaux _templatetags_, une page existant désormais dans la doc front pour ça (voir https://github.com/zestedesavoir/zds-site/pull/2641, je me suis pas cassé la tête à l'écrire pour rien :p )
- [x] supprimer les anciennes docs articles/tutos, tout en regardant si il y a pas des morceaux à récupérer (je pense par exemple au "processus de publication" de la doc des tutos v1)
- [x] refaire une passe _autodoc_, en rajoutant des `:type`, `:rtype:` et en transformant les simples quotes de code en double quote de code (reStructuredText et pas markdown ;) )
- [x] documentation de la fonction d'import qui gère désormais les images.

**Comment by Vayel** [comment]
Que puis-je faire ici sans avoir besoin de me plonger dans le code et la spec' (que vous connaissez bien mieux que moi) ?

**Comment by pierre-24** [comment]
Sans te plonger dans le code, je dirais la partie "pure doc", donc reprendre les morceaux de l'ancienne doc des tutos et les remettre dans la doc de la ZEP-12.

**Comment by Vayel** [comment]
Aurais-tu l'amabilité de m'indiquer quels sont les fichiers de l'ancienne doc (à supprimer du coup ?) et ceux de la nouvelle (ceux de la ZEP-12) ?

**Comment by pierre-24** [comment]
toute la doc est ici: https://github.com/artragis/zds-site/tree/zep_12_double_stack/doc/source

En particulier, dans "back-end, l'ancien fichier des tutos est celui-ci: https://github.com/artragis/zds-site/blob/zep_12_double_stack/doc/source/back-end/tutorial.rst et le nouveau celui là : https://github.com/artragis/zds-site/blob/zep_12_double_stack/doc/source/back-end/tutorialv2.rst

Il y a aussi le fichier "article.rst" à virer :)

**Comment by Vayel** [comment]
1er et 4è points faits avec #130.

Le 2è n'aurait-il pas plutôt sa place dans le guide du contributeur ?

**Comment by pierre-24** [comment]
C'est une très bonne remarque, et il faudrait qu'on discute de manière générale de la manière dont ont fait notre doc. Prochain Zest'meeting, je vais essayer de me souvenir d'ajouter le point !

(j'ai des trucs à dire sur autodoc en passant, maintenant qu'il fonctionne).

**Comment by Vayel** [comment]
L'UI est terminée ? Je peux prendre des screens ?

**Comment by pierre-24** [comment]
Vu ce qu'il reste à faire, j'ai effectivement tendance à dire qu'on touchera plus à grand chose.

**Comment by Vayel** [comment]
Il y a moyen de cacher l'étiquette de la sidebar Django ("DjDT") ? Au pire, je bidouillerai le style de la page, mais il me faut l'enlever pour les screens.

**Comment by pierre-24** [comment]
Le problème de cette petite barre, c'est qu'elle est bien pratique au delà de ça. Mais bon, au pire tu peux la déplacer vers le bas et je pense pas que ça soit si perturbant si elle est planquée là en bas ;)

**Comment by artragis** [comment]
J'ai commenté les templatetags et j'ai fait une passe complète sur les modèles. Il ne reste plus que les utils/form/view à documenter.

Je pense aussi à écrire une documentation sur les paramètres des "includes" dans les templates.

**Comment by artragis** [comment]
Voilà pour la doc, plus qu'à faire des screen.

**Comment by pierre-24** [comment]
Bon. Pour les screens, j'hésite. D'un coté, ça fait bien, de l'autre la doc originale n'en contenait pas forcément, et le "guide du contributeur" en contiendra, lui. Donc ?

**Comment by artragis** [comment]
tu decides.

**Comment by Vayel** [comment]
Je peux m'occuper des screens si vous voulez.

**Comment by pierre-24** [comment]
Si tu te sens d'humeur à faire ça, pourquoi pas :)

**Comment by artragis** [comment]
des nouvelles ou pas? dois-je clore (on abandonne les screen) ou bien on laisse ouvert?

**Comment by pierre-24** [comment]
Pour moi, ça peut attendre le "guide du contributeur". Sauf si @Vayel  est motivé ;)

**Comment by artragis** [comment]
Ok je clos. Je pense que @Vayel fait déjà un gros boulot en ce moment en relisant les tutos qui sont en béta, ce qui est bien plus important.
