### ISSUE TITLE
"validation des tutoriels" n'est présent que sur certaines pages

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#116]
[Reporté par Vayel](https://zestedesavoir.com/forums/sujet/846/zep-12-refonte-du-principe-des-tutoriels-et-articles/?page=17#p57161).

Par exemple, pas sur la page d'accueil, 

![screenshot from 2015-05-16 22 41 00](https://cloud.githubusercontent.com/assets/7889675/7668824/a0ae4e86-fc1c-11e4-8a55-cccdcfaf0f03.png)

Mais bien sur la liste des contenus:

![screenshot from 2015-05-16 22 41 26](https://cloud.githubusercontent.com/assets/7889675/7668827/b8201284-fc1c-11e4-816d-b85e8e4b1c76.png)

**Comment by Eskimon** [comment]
Ca vient d'ici : https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/base.html#L450

Le code est un peu ... bizarre, je sais pas quel morceau est le bon mais a l'heure actuelle sur le site c'est le format `perms.tutorial.change_[tutorial|article]` qui est utilisé

```
{% if is_staff %}
    <li>
        <a href="{% url "validation:list" %}?type=tuto">{% trans "Validation des tutoriels" %}</a>
    </li>
{% endif %}

{% if perms.article.change_article %}
    <li>
        <a href="{% url "validation:list" %}?type=article">{% trans "Validation des articles" %}</a>
    </li>
{% endif %}
```

**Comment by Eskimon** [comment]
Je m'en occupe

**Comment by artragis** [comment]
comme j'ai mergé les commits de cette PR, je passe en needqa

**Comment by Vayel** [comment]
Il semblerait que ce soit bon par ici.
