### ISSUE TITLE
Rajouter des boutons supplémentaires à l'édition

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#117]
[Proposé par Vayel](https://zestedesavoir.com/forums/sujet/846/zep-12-refonte-du-principe-des-tutoriels-et-articles/?page=17#p57165):

> On pourrait plutôt proposer deux boutons "Ajouter un conteneur" et "Ajouter un extrait". Pour faciliter la vie de l'auteur, un clic sur un tel bouton ferait apparaître un menu à l'instar de "Déplacer" avec la liste des positions possibles (existantes et autorisées en fonction du type de l'objet). Au moins, on peut aisément créer tout type d'objet partout depuis n'importe où et on ne se demande plus ce qu'est une partie ou un chapitre.

Évolution, mais il faut le proposer ;)

**Comment by Vayel** [comment]
Ce ne serait pas "rajouter des boutons" mais "remplacer les boutons actuels par". En effet, on ne sait pas trop si "partie" désigne : 
- Un conteneur de niveau 1, _i.e._ enfant direct du tutoriel
- Un conteneur comportant deux niveaux (des chapitres constitués d'extraits)

Dans le premier cas, ça fait bizarre d'avoir des parties possiblement de différente profondeur. Dans le deuxième cas, on pourrait avoir des parties adjacentes à des chapitres.

Du coup, je suggère de conserver uniquement le terme "conteneur" et d'explicitement demander à l'auteur où il souhaite l'ajouter. Ca resterait d'ailleurs en accord avec la doc, qui ne parle pas de parties ou de chapitres.

**Comment by Vayel** [comment]
Actuellement, une partie est un conteneur de niveau 1, quelque soit son contenu. Du coup, il y a un souci terminologique dans le message signalant une faute dans le tutoriel.

Par exemple, il est [ici](http://zds.francoisdambrine.me/mp/32/proposition-de-correction/messages/) mention d'un chapitre, alors qu'il s'agit d'une [partie](http://zds.francoisdambrine.me/contenus/39/qa86tuto/).

**Comment by pierre-24** [comment]
En effet. Par contre, pour faciliter le suivi, fait une _issue_ à part :)
