### ISSUE TITLE
"Ce conteneur est actuelement vide"

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#118]
![screenshot from 2015-05-16 22 46 46](https://cloud.githubusercontent.com/assets/7889675/7668833/6d4205aa-fc1d-11e4-919f-d945d378ca35.png)

Et d'une, il y a une faute à "actuellement" ([merci Vayel](https://zestedesavoir.com/forums/sujet/846/zep-12-refonte-du-principe-des-tutoriels-et-articles/?page=17#p57161) :-° )

Et de deux, maintenant qu'on à nommé nos conteneurs, autant utiliser le nommage dans ces messages là aussi (donc "ce chapitre est actuellement vide")

**Comment by artragis** [comment]
Corrigé

**Comment by Vayel** [comment]
Pas complètement : 
- http://zds.francoisdambrine.me/contenus/33/qa-118/
- http://zds.francoisdambrine.me/contenus/34/qa-118-bis/p/
- http://zds.francoisdambrine.me/contenus/34/qa-118-bis/p-1/c/
- http://zds.francoisdambrine.me/contenus/34/qa-118-bis/p-2/#1-s (ici, pas de message)

Peut-être enlever la majuscule à "Partie" dans "Cette Partie est actuellement vide. " : http://zds.francoisdambrine.me/contenus/34/qa-118-bis/. De même avec "Chapitre : http://zds.francoisdambrine.me/contenus/34/qa-118-bis/p-1/.

**Comment by artragis** [comment]
voilou

**Comment by Vayel** [comment]
Je chipote mais : 
- http://zds.francoisdambrine.me/contenus/33/qa-118/ (il manque un "l")
- http://zds.francoisdambrine.me/contenus/34/qa-118-bis/p-2/#1-s (il manque un point)

**Comment by artragis** [comment]
voilou

**Comment by Vayel** [comment]
Désolé de nouveau : http://zds.francoisdambrine.me/contenus/33/qa-118/ (il manque "Ce contenu").

**Comment by artragis** [comment]
Done (par contre j'ai mis "Le" plutôt que "Ce" pour être comme partout quand on parle des tuto/articles)

**Comment by Vayel** [comment]
Bien vu. Par contre, il y a des majuscules gênantes à "Tutoriel" et "Article".

**Comment by artragis** [comment]
il y en a partout.

**Comment by Vayel** [comment]
Euh non, pas à "partie" : http://zds.francoisdambrine.me/contenus/34/qa-118-bis/p/

D'ailleurs, il semblerait que ce soit "Ce" à la place de "Le".

**Comment by artragis** [comment]
remplacé

**Comment by Vayel** [comment]
Parfait.

**Comment by artragis** [comment]
je dépile.

**Comment by pierre-24** [comment]
C'te QA :o 

Merci @Vayel ^^
