### ISSUE TITLE
Menu "Suppression" vide

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#119]
Quand je suis sur une partie, la catégorie "Suppression" à gauche est vide. De même quand je suis dans un chapitre. Il faut laborieusement se rendre au parent pour supprimer un élément.

**Comment by pierre-24** [comment]
Je rajoute qu'elle est vide uniquement quand le tuto est publié (ce qui n'est pas normal dans tout les cas, mais ça donne une petite idée de pourquoi ça bugge):

![screenshot from 2015-05-17 09 10 02](https://cloud.githubusercontent.com/assets/7889675/7670484/7c5069fe-fc74-11e4-9e4b-78dcdd2637d6.png)

(http://zds.francoisdambrine.me/contenus/23/test-1/une-partie/, avec `user`)

**Comment by pierre-24** [comment]
Corrigé !

La QA est évidente :-)

**Comment by Vayel** [comment]
QA OK.

**Comment by artragis** [comment]
Du coup je ferme ^^
