### ISSUE TITLE
La galerie n'est pas supprimée à la suppression du tuto

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#122]
Tout est dans le titre :)

**Comment by artragis** [comment]
C'est pas sensé être volontaire ça? pour éviter la perte d'image sur le forum?

**Comment by Vayel** [comment]
Vu que dans tous les cas l'auteur pourra la supprimer manuellement s'il le souhaite vraiment, autant lui faciliter la vie sans lui forcer la main en le lui demandant lors de la suppression du contenu, non ?

**Comment by pierre-24** [comment]
@artragis : [C'est déjà le cas sous une forme semblable dans le code original](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorial/models.py#L359), j'ai fait que remettre ça ;)
@Vayel : ça peut effectivement être un compromis.

**Comment by Vayel** [comment]
La galerie (vide ou non) est bien supprimée à la suppression d'un tutoriel/article.

**Comment by artragis** [comment]
ok donc je clos

2015-05-21 12:02 GMT+02:00 Vincent notifications@github.com:
