### ISSUE TITLE
Terminologie dans le message signalant une faute

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#124]
Actuellement, une partie est un conteneur de niveau 1, quelque soit son contenu. Du coup, il y a un souci terminologique dans le message signalant une faute dans le tutoriel.

Par exemple, il est [ici](http://zds.francoisdambrine.me/mp/32/proposition-de-correction/messages/) fait mention d'un chapitre, alors qu'il s'agit d'une [partie](http://zds.francoisdambrine.me/contenus/39/qa86tuto/).

**Comment by artragis** [comment]
je m'en occupe ce midi.

**Comment by artragis** [comment]
done.

**Comment by Vayel** [comment]
[Appelé depuis un chapitre](http://zds.francoisdambrine.me/mp/49/proposition-de-correction/messages/?page=1#p51). Je verrais plutôt un truc comme ça : 

```
Salut !

Il me semble avoir rencontré une faute de langue dans ton tutoriel X dans le chapitre Y de la partie Z :

> 
```

Pour la proposition de correction, il faudrait un autre champ quand on clique sur le bouton de signalement, parce que là c'est pas du tout clair (et surtout, le faute et la correction apparaissent dans la même citation dans le MP...).

**Comment by pierre-24** [comment]
Doucement, tu mélanges plein de truc ;)
1. Tu veux avoir un champ "problème" et un champ "proposition de correction". Je suis pas contre l'idée, mais j'ai peur que la boite modale soit trop "petite" pour contenir tout ça (ou alors, il faudrait employer des `<input type="text" />`, donc exit le texte multiligne). Parce que non, la taille d'une modale ne s'adapte pas à son contenu (et ça, c'est pas de notre faute) ;)
2. Tu souhaiterais que le message soit plus explicite et donne tout le "chemin" vers l'endroit ou est signalé la faute: c'est un peu _tricky_ à faire, mais faisable (mais autant le faire direct dans la template).

**Comment by Vayel** [comment]
En effet, pardon. ^^'

Je viens de me rendre compte qu'il y avait le lien du chapitre depuis lequel on a signalé la faute, donc inutile d'indiquer la partie. Par contre, et c'est plus embêtant, il n'y a pas de référence à la section. Par exemple, ce [signalement](http://zds.francoisdambrine.me/mp/54/proposition-de-correction/messages/?page=1#p56) a été fait depuis l'url http://zds.francoisdambrine.me/tutoriels2/49/qa124/p/c/#1-s. Après, comme il s'agit d'une ancre, j'ignore si on peut facilement remédier à ça.

**Comment by pierre-24** [comment]
Ce n'est pas facilement faisable, parce que ça veut dire qu'il faudrait un bouton "signaler une faute" pour chaque section. Je sais qu'il y a des tickets dans ce sens là et des propositions, mais jusqu'ici, personne n'as été en mesure de proposer une solution satisfaisante (et on a tous en tête ce qui se passait sur OC avec cette petite barre qui se déplaçait avec ta souris).

**Comment by artragis** [comment]
Donc on est bon pour cette partie là ou pas?

**Comment by Vayel** [comment]
Je fais une PR pour corriger les fautes et ça devrait être OK.

**Comment by artragis** [comment]
Cool \o/

**Comment by Vayel** [comment]
Can be closed.
