### ISSUE TITLE
Présence du bouton "Signaler une faute"

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#125]
Sur [cette page](http://zds.francoisdambrine.me/tutoriels2/49/qa124/p/) (à consulter avec user car le tutoriel est publié avec admin), il n'y a pas le bouton "Signaler une faute". Du coup, pas très pratique pour en indiquer une dans l'introduction ou la conclusion de la partie.

Il faudrait le bouton sur toutes les pages et préciser dans le MP d'où il a été cliqué (contenu, partie, chapitre, section).

**Comment by pierre-24** [comment]
Au delà du fait que c'est extrèmement facile à implémenter (il suffit d'enlever la condition qui dit que ça ne doit apparaitre que sur les conteneur terminaux), est ce que ça a du sens ?

**Comment by Vayel** [comment]
> Du coup, pas très pratique pour en indiquer une dans l'introduction ou la conclusion de la partie.

**Comment by pierre-24** [comment]
ça se tient, mais je me demande pourquoi je l'avais pas fait à l'époque (c'est déjà moi qui avait mis en place la solution à la base).

**Comment by Eskimon** [comment]
Je viens de regarder, je vois bien le bouton. Du coup on est comment ici ? Plutot bien nan ?

**Comment by artragis** [comment]
Plutôt je ferme.
