### ISSUE TITLE
La suppression d'un extrait a des effets indésirables sur le markdown

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#126]
**Scénario**
1. Je crée un article dont le titre est "banane" dans la catégorie "php"
2. Je crée une première  section dont le titre est "banane" dont le contenu est vide
3. Je crée une deuxième section dont le titre est "banane" dont le contenu est vide
4. Je crée une troisième section dont le titre est "banane" dont le contenu est vide
5. Je suprimme la deuxième section

**Problème** : Lors de l'affichage de l'article j'ai le message "Une erreur est survenue dans la génération de texte Markdown. Veuillez rapporter le bug."

Ce scénario est rare, mais l'erreur obtenue me fait dire que la suppression d'un extrait est partiellement buggy.

**Comment by artragis** [comment]
sur mon serveur ledit article s'appelle bonobo?

**Comment by pierre-24** [comment]
Alors ça, c'est pas commun. Et c'est d'autant plus bizarre qu'à priori, le manifest contient bien ce qu'il doit contenir:

``` json
{
    "object": "container", 
    "slug": "bonobo", 
    "title": "Bonobo", 
    "introduction": "introduction.md", 
    "conclusion": "conclusion.md", 
    "children": [
        {
            "object": "extract", 
            "slug": "bonobo", 
            "title": "Bonobo", 
            "text": "bonobo.md"
        }, 
        {
            "object": "extract", 
            "slug": "bonobo-2", 
            "title": "Bonobo", 
            "text": "bonobo-2.md"
        }
    ], 
    "version": 2, 
    "description": "", 
    "type": "ARTICLE", 
    "licence": "Beerware"
}
```

.... Et que les fichiers sont là :o 

![screenshot from 2015-05-18 10 06 57](https://cloud.githubusercontent.com/assets/7889675/7682372/9db7afe0-fd45-11e4-9987-036b6a37fe25.png)

**Comment by firm1** [comment]
C'est bien l'article bonobo oui.

**Comment by firm1** [comment]
J'ai un scénario de bug presque similaire. Si j'importe un tuto avec plusieurs partie, en supprimant une partie, si je retourne dans la version précédente pour la revoir, c'est le bazard. (voir tuto La fabrication numérique)

**Comment by pierre-24** [comment]
Je t'avoue que je ne comprend pas: [sur cette version](http://zds.francoisdambrine.me/contenus/comparaison/53/la-fabrication-numerique/?version=30ba4c335874c85bd14bf9e9658836bd23ad1a0e), tout y est ?!?

**Comment by firm1** [comment]
Ah, j'ai louché pour celui-là alors. My Bad.

**Comment by pierre-24** [comment]
Voilà, à QA dès que artragis a mis à jour son serveur :)

**Comment by artragis** [comment]
voilà qui est fait.

**Comment by firm1** [comment]
Bon, en testant l'issue, j'ai un problème.

Scénario : 
1. Je crée un article dont le titre est "banane" dans la catégorie "php"
2. Je crée une première  section dont le titre est "banane" dont le contenu est vide
3. Je crée une deuxième section dont le titre est "banane" dont le contenu est vide
4. Je crée une troisième section dont le titre est "banane" dont le contenu est vide

Erreur 500 qui me dit : 

``` http
Exception at /contenus/54/banane/

slug "banane-1" already in the slug pool !

Request Method:     GET
Request URL:    http://zds.francoisdambrine.me/contenus/54/banane/
Django Version:     1.7.7
Exception Type:     Exception
Exception Value:    

slug "banane-1" already in the slug pool !

Exception Location:     /home/francois/zds-site/zds/tutorialv2/models/models_versioned.py in add_slug_to_pool, line 160
Python Executable:  /home/francois/zds-site/zdsenv/bin/python
Python Version:     2.7.3
Python Path:    

['/home/francois/zds-site',
 '/home/francois/zds-site/zdsenv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg',
 '/home/francois/zds-site/zdsenv/lib/python2.7',
 '/home/francois/zds-site/zdsenv/lib/python2.7/plat-linux2',
 '/home/francois/zds-site/zdsenv/lib/python2.7/lib-tk',
 '/home/francois/zds-site/zdsenv/lib/python2.7/lib-old',
 '/home/francois/zds-site/zdsenv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/home/francois/zds-site/zdsenv/local/lib/python2.7/site-packages',
 '/home/francois/zds-site/zdsenv/local/lib/python2.7/site-packages/git/ext/gitdb',
 '/home/francois/zds-site/zdsenv/local/lib/python2.7/site-packages/gitdb/ext/smmap']

Server time:    mar, 19 Mai 2015 10:50:01 +0200
```

**Comment by pierre-24** [comment]
En effet ^^

Encore une personne que la ZEP-12 n'aime pas :o

**Comment by pierre-24** [comment]
Voilà, c'est mergé. J'ai malheureusement été obligé de virer "banane" (il est irrattrapable, le manifest était corrompu), mais tu pourra le retenter pour la QA ;)

**Comment by firm1** [comment]
Je confirme, problème résolu
