### ISSUE TITLE
On est pas censé pouvoir modifier les vieilles versions

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#136]
url incriminée : http://zds.francoisdambrine.me/contenus/57/bonobo-2/bonobo/bonobo/?version=bf437d3e1c9f0c8a95c3a1b360f6d73ff5acbf33

Je suis sur une vieille version du tutoriel. Je ne peux pas éditer un extrait, donc je n'ai pas la possibilité de modifier du vieux contenu. Cependant, dans la sidebar j'ai les boutons "Action > Déplacer" et "Suppression > supprimer" qui donnent l'impression que je peux réaliser ces actions sur ce vieux contenu. Ce qui n'est pourtant pas le cas.

Du coup, je pense qu'on a un bug d'affichage là non ?

**Comment by artragis** [comment]
En prod ça fait quoi? Juste pour savoir.

**Comment by pierre-24** [comment]
Je suis d'accord avec firm1, il manque une condition dans la template :-)

**Comment by pierre-24** [comment]
Voilà, logiquement c'est bon !

**Comment by Vayel** [comment]
Ok ici.
