### ISSUE TITLE
Les catégories de la topbar ne sont pas correctes

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#137]
Rattaché au "boss final de la ZEP-12" (#87)

Il est nécéssaire d'aller modifier le fichier [`topbar.py`](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/utils/templatetags/topbar.py) pour lui faire employer notre nouveau modèle. Ceci étant dit, mon _issue_ a également pour intérêt de dire qu'un tel code existe déjà, [dans la vue des contenus publics](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_published.py#L239), donc faudra déplacer ça et réutiliser le code convenablement (pas de copie de code, please ;) )

**Comment by artragis** [comment]
il a quoi notre modèle de plus que ce que j'avais déjà modifié avec la ligne :

``` python
subcats_tutos = PublishableContent.objects.values('subcategory')\
        .filter(sha_public__isnull=False, type="TUTORIAL")\
        .all()
    catsubcats = CategorySubCategory.objects \
        .filter(is_main=True)\
        .filter(subcategory__in=subcats_tutos)\
        .order_by('category__position', 'subcategory__title')\
        .select_related('subcategory', 'category')\
        .values('category__title', 'subcategory__title', 'subcategory__slug')\
        .all()
```

**Comment by pierre-24** [comment]
Le modèle est très très bien :)

... Mais il faut bouger cette partie de code dans `topbar.py` pour que la dropdown s'en serve aussi, et notre modèle doit se servir de la fonction de `topbar.py`, et pas avoir une fonction à lui qui fait pareil (à la base, je pense que c'était `topbar` qui était employé dans la template).

**Comment by artragis** [comment]
heu... my brain went out.

**Comment by pierre-24** [comment]
Ouais, faut que j'arrête d'essayer d'écrire des messages en 4ième vitesse avant d'attraper des bus, ça donne rien. Je recommence:
- Pour le moment, le code qui génère l'affichage des catégories est en doublon à deux endroit: [là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_published.py#L239) et dans [`topbar.py`](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/utils/templatetags/topbar.py). J'aime pas les doublon dans le code, ça induit quasi systématiquement des régressions quand on fait pas attention. Conclusion, tout doit être migré dans `topbar.py` :)
- Le code de `topbar.py` lui même est fonctionnel, mais ... Il se répète aussi. Et soit dit au passage, le paramètre `user` qu'on passe aux fonctions n'as jamais servis à rien, mais pour l'utiliser comme filtre, il faut passer un paramètre. Donc autant passer un paramètre `type` qui fait le job de faire la différence article/tuto et corriger la template en `{% for category,machin in "ARTICLE"|top_category_content %}`, [là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/base.html#L192) et [là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorialv2/index_online.html#L113).

... _brain in_ ?

**Comment by artragis** [comment]
My brain came back in.

**Comment by pierre-24** [comment]
Ça aussi, je veux bien :)

(ça a le mérite d'être un minimum drôle à faire :p )

**Comment by artragis** [comment]
impéc.

**Comment by pierre-24** [comment]
Voilà :)

**Comment by artragis** [comment]
donné que les fonctionnements n'ont pas changé, je clos.
