### ISSUE TITLE
Renvoyer des Http 404 plus "dev friendly"

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#139]
On peut faire des 

``` python
raise Http404("une erreur")
```

et alors, pour le dev' (parce qu'il faut `Debug=True`), le message en question s'affichera dans la page de la 404. Ça peut être utile ;)

**Comment by artragis** [comment]
toutafé.

**Comment by Vayel** [comment]
Si ce n'est pas trop compliqué, je peux m'en occuper. Par contre, je veux bien des détails. ^^

**Comment by artragis** [comment]
Il suffit de regarder quand on envoie des 404 et ajouter un argument qui
dit "the resource not found due to an inexisting pk" ou bien "due to an
unknown slug" etc.

2015-05-21 11:49 GMT+02:00 Vincent notifications@github.com:

**Comment by Vayel** [comment]
Quels sont les fichiers à scanner ?

**Comment by artragis** [comment]
mixins, utils, views, models. En se concentrant sur la zep12

2015-05-21 12:28 GMT+02:00 Vincent notifications@github.com:

**Comment by Vayel** [comment]
C'est juste pour les devs ? Pas besoin de faire de phrases bien tournées ?

**Comment by pierre-24** [comment]
C'est effectivement rien que pour les dev's: en temps normal, c'est la page 404 du ZdS qui est employée (avec Clem'). Du coup, de l'anglais "petit chinois" suffit amplement (en même temps, si un vrai anglophone lisait nos commentaires, je pense qu'il nous frapperait un bon coup avec le _harrap's_). 

Je soupçonne par contre que ces phrases apparaitrons dans le log, ce qui est loin d'être une mauvaise chose si c'est le cas.

**Comment by Vayel** [comment]
Au pire, je squasherai mes commits.

**Comment by pierre-24** [comment]
Y'a pas vraiment de QA là dessus, si ?

**Comment by artragis** [comment]
Nope, c'est fait donc je ferme.
