### ISSUE TITLE
Page d'acceil inaccessible en mode déconnecté

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#142]
Se déconnecter et visiter http://zds.francoisdambrine.me/

`int() argument must be a string or a number, not 'SimpleLazyObject'` sur `{{ article.last_read_note.get_absolute_url }}`

Ma main à couper qu'on demander le pk de l'user sans avoir vérifié qu'il était connecté ;)

**Comment by artragis** [comment]
c'est dans les content_part_type_xxx.part.html

**Comment by pierre-24** [comment]
ça, je savais :p

**Comment by artragis** [comment]
Ok, donc je te laisse modifier? Façon, là faut que je me repose, j'ai 
une journée pré-long weekend demain.

**Comment by pierre-24** [comment]
Je te promet rien, je suis moi-même parfaitement déclassé, aujourd'hui.

**Comment by pierre-24** [comment]
# Note de QA
- Commenter au préalable un article quelques fois
- Sur la page d'accueil, en mode déconnecté, vous devez tomber sur le premier commentaire, même si il y en a plusieurs
- En mode connecté, vous devez tomber sur le dernier commentaire lu.

**Comment by Vayel** [comment]
Ok ici. Par contre, user n'a plus d'avatar. J'ignore si c'est normal.

**Comment by artragis** [comment]
oui.
