### ISSUE TITLE
Images et HTML d'un tuto

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#147]
Quand on génère le HTML d'un tuto, les liens vers les images pointent soit sur les images d'origine (`/media/xxx/` ou URL du web), soit sur leur versions téléchargées pour les besoins du PDF (c'est cette dernière option qui est en place actuellement, un peu par hasard). Dans les deux cas, quand on télécharge le HTML, c'est sans les images.

Du coup, proposition: pourquoi ne pas faire télécharger une archive qui contiendrait le HTML **ET** les images ? (puisqu'on les as sous la main).

**Comment by artragis** [comment]
+1, mais c'est une évolution.

**Comment by pierre-24** [comment]
Je suis tout à fait d'accord :)

**Comment by Eskimon** [comment]
Je n'aurais pas dit mieux :D
