### ISSUE TITLE
Les images sans nom font planter la récupération automatique

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#148]
[Reporté par Vayel](https://zestedesavoir.com/forums/sujet/846/zep-12-refonte-du-principe-des-tutoriels-et-articles/?page=19#p58130).

(ce ticket sert plus de suivi qu'autre chose)

**Comment by pierre-24** [comment]
Voilà, @Vayel :)

**Comment by Vayel** [comment]
**Edit :** après une MAJ du serveur, ça va mieux. Et du coup c'est bon. ^^
