### ISSUE TITLE
Rappel de l'alerte lors de sa résolution

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#153]
> Salut.
> 
> J'ai vu que tu travaillais à reformuler les messages automatiques dans le cadre de la ZEP-12. J'aimerais réagir au sujet de templates/tutorialv2/messages/resolve_alert.md : je sais que c'est une (petite) évolution, mais il me paraît utile d'ajouter à ce message un rappel du message de signalement que l'on a envoyé.
> 
> Une fois le signalement fait, on n'a plus aucune trace de ce que l'on a dit.

De Dominus Carnufex, par MP.

Ca doit prendre deux secondes, mais je n'ai pas trouvé le template du message d'alerte envoyé au staff.

**Comment by pierre-24** [comment]
Merci Dominus si tu passes par ici,

Le template [se trouve là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorialv2/messages/resolve_alert.md), ainsi qu'il l'as indiqué :)

Quand à l'endroit ou c'est géré, [c'est dans les vues des objets publiés](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_published.py#L580). Typiquement, pour que ça fonctionne, il faudrait renvoyer une nouvelle variable à la template ([quelques lignes plus bas](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_published.py#L603)), en oubliant pas d’appliquer le "truc" `'\n'.join(['> ' + line for line in texte_de_l_alerte.split('\n')])` (qu'un jour je vais craquer et ajouter dans un _templatetag_).

**Comment by Vayel** [comment]
Justement, je me suis mal exprimé : `texte_de_l_alerte` il est où ?

**Comment by pierre-24** [comment]
`Alert` est [un objet défini là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/utils/models.py#L240) :)

Donc vu le contexte, bah ... `alert.text` :)

**Comment by pierre-24** [comment]
QA: OK :)
