### ISSUE TITLE
Les tutos en bêta d'un utilisateur ne pointent pas sur la version bêta

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#155]
Quand on visite le profil d'un utilisateur, et qu'on clique sur "Activité > Tutoriels > en version bêta", le lien est celui de la version brouillon (genre là : http://zds.francoisdambrine.me/contenus/tutoriels/1/?filter=beta)

La solution, c'est de passer `type="beta"` à la template, MAIS il faut le faire uniquement si on visite un profil qui n'est pas le sien (sinon, on va se taper les liens bêta en cliquant sur "mes tutoriels").

**Comment by pierre-24** [comment]
D'ailleurs, les liens "Activité > Tutoriels > en version publique" ne pointanit pas non plus sur la version publique. Maintenant c'est le cas :)

**Comment by Vayel** [comment]
> Maintenant c'est le cas :)

Ouais ! :P

**Comment by artragis** [comment]
donc je peux fermer?

**Comment by Vayel** [comment]
Oui.
