### ISSUE TITLE
Les métriques des articles d'un membres apparaissent même à 0

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#156]
Voir là: http://zds.francoisdambrine.me/membres/voir/admin/

![screenshot from 2015-05-24 20 56 15](https://cloud.githubusercontent.com/assets/7889675/7790471/66e305f2-0257-11e5-93ae-206b17be2093.png)

Pour les tutoriels, quand une métrique est à zéro (par exemple ici "en validation"), elle n’apparaît pas, alors que c'est l'inverse pour les articles.

**Comment by artragis** [comment]
Il me semble qu'en prod c'est comme ça.

**Comment by pierre-24** [comment]
Pas faux.

**Comment by pierre-24** [comment]
... Manque de pot, je suis un peu têtu :p

**Comment by artragis** [comment]
QA OK
