### ISSUE TITLE
Nombre d'articles non indiqué dans le profil

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#159]
Ici : http://zds.francoisdambrine.me/membres/voir/staff/

Dans "Activités" > "Articles" il n'y a rien alors que "Derniers articles" n'est pas vide.

**Comment by pierre-24** [comment]
J'ai du "abuser" avec ma dernière PR en date (un if mal écrit, probablement)

**Comment by artragis** [comment]
as-tu eu le temps de le corriger ou bien puis-je me le réserver pour demain?

**Comment by pierre-24** [comment]
Je t'en prie. 

[mylife]Je suis complètement busy pour les prochains jours (je rentre à la maison de mon stage de 3 mois donc bon)[/mylife]

**Comment by artragis** [comment]
corrigé. C'était un problème de pluriel.

**Comment by Vayel** [comment]
C'est good.
