### ISSUE TITLE
impossible de commenter un article

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#161]
# désolation

**Comment by pierre-24** [comment]
D'où que ça vient, ça ?

**Comment by pierre-24** [comment]
Ça a pas réglé le problème :/

**Comment by artragis** [comment]
nope, je sèche là.

2015-06-04 11:44 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by pierre-24** [comment]
Je regarde :-)

**Comment by pierre-24** [comment]
Quasiment un bug d'intégration, d'où le fait que les tests ne disaient rien.

# Pour la QA:
- Publier un article
- Vérifier que vous pouvez le commenter uner première fois et puis une deuxième (l'antispam doit rester actif, donc changez d'user)

**Comment by artragis** [comment]
done, j'ai même ping/pongé
