### ISSUE TITLE
Mauvais lien vers le pseudo lors d'un signalement de faute

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#164]
https://github.com/zestedesavoir/zds-site/issues/2788

**Comment by pierre-24** [comment]
Oui, mais l'erreur se situe pas dans le back de la ZEP-12, mais "plus haut", non ?

**Comment by Vayel** [comment]
Je l'ignore. Mais vu que j'ai changé certains messages dans le cadre de cette ZEP, je me suis dit que cette _issue_ s'y intégrait peut-être.

**Comment by pierre-24** [comment]
Moui, en effet, bien vu. Je vais essayer de regarder ça ce soir.

**Comment by artragis** [comment]
La zep12... ne linke plus vers la personne qui envoie le mail : https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorialv2/messages/warn_typo.md

**Comment by Vayel** [comment]
Bien vu. Il pourrait être intéressant de le signaler dans l'autre issue, même si ce problème de caractères spéciaux mérite d'être résolu.

**Comment by artragis** [comment]
il me semble qu'il y a une PR pour ça.

**Comment by pierre-24** [comment]
Bon, j'ai QA ladite PR, et logiquement, la résolution ne passe pas par nos templates (ou les originales), donc logiquement, on est bon ;)

**Comment by artragis** [comment]
Que dois-je faire pour la QA?

**Comment by pierre-24** [comment]
Ben faut remonter la branche de _dev_ ici, puis créer un pseudo avec des caractères bizarres (genre `ïtrema &@ck`), puis lui faire signaler une faute sur un truc. Et dans le MP qui signale l'erreur, vérifier que le lien vers le profil est correct !

**Comment by artragis** [comment]
Ok, la remontée de dev attendra que la release soit passée.

**Comment by artragis** [comment]
le merge a été fait, comme on ne link plus le pseudo, OSEF et QA validée.
