### ISSUE TITLE
Ordonner les tags

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#169]
https://zestedesavoir.com/forums/sujet/2743/ordonner-les-tags/?page=1#p62011

**Comment by pierre-24** [comment]
Juste un `sorted_by()` à rajouter ;)

**Comment by Vayel** [comment]
Je le rajoute à ces niveaux-là ?
- https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/forms.py#L159
- https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/article/forms.py#L56

**Comment by pierre-24** [comment]
Le deuxième n'est pas nécéssaire ;)

**Comment by Vayel** [comment]
`zds/article/` va être supprimé j'imagine ?

**Comment by pierre-24** [comment]
Yep ... Mais pas tout de suite.

**Comment by artragis** [comment]
doit-on faire quelque chose ici?

**Comment by Vayel** [comment]
Ouep : trier les résultats passés en arguments à la vue [ici](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/forms.py#L159).

**Comment by artragis** [comment]
VOilà.

**Comment by Vayel** [comment]
C'est fort appréciable. Merci !

**Comment by artragis** [comment]
Puis-je fermer?

**Comment by Vayel** [comment]
Ouep !
