### ISSUE TITLE
Séparation du texte d'un article en extraits

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#171]
Il faut tester le comportement introduit par la PR #170 :
- Créer un article v1 contenant toutes sortes de titres, y compris des titres dans des balises de codes, ou qui n'est pas censé être un titre (à priori, [ceci est un bon début](http://paste.awesom.eu/Lz3w), mais soyez créatifs)
- Créez un article v1 ne contenant pas de titre de niveau 1 (comme c'est le cas [pour les interviews](https://zestedesavoir.com/articles/?tag=Interview) !)
- Lancez la migration v1→v2
- Constater que tout c'est bien passé !

**Comment by artragis** [comment]
ça vaudrait presque le coup de modifier la classe ArticleFactory puis de donner le code yaml pour que je puisse simplement faire un `python manage.py load_factory_data la_factory_des_articles.yaml; python manage.py migrate_to_zep12`

**Comment by pierre-24** [comment]
Je suis pas bien la partie "puis de donner le code yaml" :p

**Comment by artragis** [comment]
load_factory_data utilise un fichier yaml pour sérialiser

**Comment by pierre-24** [comment]
Je sais. Mais comme je le dis sur la PR, ça fait pas doublon avec `load_fixtures` ?

**Comment by artragis** [comment]
pas le même but, là on personnalise les cas pour faire une vraie QA.

**Comment by pierre-24** [comment]
Je vois. En fait, j'ai peur que `load_factory_data` me permette pas de mettre le texte que je veux :s

**Comment by artragis** [comment]
c'est toi qui voit.

**Comment by artragis** [comment]
QA OK, je ferme et je me lance dans les TU.
