### ISSUE TITLE
Les bulles ne s'affichent plus dans les listes d'article

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#173]
Salut,
le nombre de notes dans les listes d'article ne s'affiche plus. J'ai introduit ce bug en tentant de réduire drastiquement le nombre de requête de type COUNT(*) sur les tables de commentaires. Je regarderais plus avant plus tard.

**Comment by artragis** [comment]
le problème est réglé et le nombre de requête a drastiquement baissé sur la page de liste des articles et légèrement sur la HP (ce qui est appréciable :p) 

Je mets en need QA, ainsi qu'en "style" car là il va falloir réfléchir à faire disparaître les get_XXX qui font des requêtes ou bien les renommer (solution du pauvre). On fait trop de calculs pour rien je trouve. 110 requêtes (division par 2 par rapport à ce matin quand même !!) sur la page de listing des articles en anonyme c'est clairement trop !

**Comment by Vayel** [comment]
C'est ok. Par contre, l'infobulle est pas terrible.

**Comment by pierre-24** [comment]
Qu'est ce que tu appelles "pas terirble" ?

**Comment by Vayel** [comment]
"réaction" c'est bof comme texte. Plutôt "Consulter les commentaires." ou un truc du genre.

**Comment by artragis** [comment]
hum j'ai peut être foiré l'infobulle, normellement c'est "X réactions" 
avec X le nombre de réactions.

**Comment by artragis** [comment]
fixed.

**Comment by pierre-24** [comment]
Cool, et je confirme, donc _closed_ :)

**Comment by pierre-24** [comment]
(par contre, Travis a pas apprécié :-° )

**Comment by artragis** [comment]
J'essaie de réduire le nombre de requêtes, mais effectivement, c'est OK.

2015-06-29 13:13 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by artragis** [comment]
(si c'est bon, j'avais fait une petite typo que je n'avais pas remarqué,
ayant exécuté le mauvais TU)

**Comment by Vayel** [comment]
Il y a une petite faute : "Aucune réaction**s**".

**Comment by pierre-24** [comment]
T'es sur qu'il faut un s ? (moi et le français, en même temps)

**Comment by Vayel** [comment]
Non, justement il n'en faut pas. ^^

**Comment by Vayel** [comment]
Peut-être ré-ouvrir l'issue pour ne pas oublier la faute ? C'est le `pluralize` qui fout la merde.

**Comment by pierre-24** [comment]
Voilà :)

**Comment by artragis** [comment]
à vérifier que c'est pas déjà comme ça sur la zep04 car c'est le template
par défaut de django qui merdouille là.

2015-06-30 15:51 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by Vayel** [comment]
On est bon ici.

**Comment by pierre-24** [comment]
Nice :)
