### ISSUE TITLE
Tags sujet bêta

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#174]
Lorsqu'on crée un contenu et le passe en bêta, le sujet en bêta n'a pas de tag `tutoriel` ou `article`. Est-ce voulu ?

**Comment by artragis** [comment]
Oui.Il me semble que c'est @Eskimon qui nous avait dit que c'était peu utile dans les faits.

**Comment by Vayel** [comment]
On ne peut pas trop juger pour l'instant vu qu'il n'y a pas de bêta pour les articles mais, à terme, il me semble intéressant de pouvoir trier les sujets selon le type de contenu. ^^

**Comment by artragis** [comment]
Après il y a d'autres problèmes, notamment de longueur : le champ titre 
ne t'autorise pas plus de X caractères et les tags en font parti. 
Ajouter [tutoriel] c'est déjà en ajouter 10.

**Comment by pierre-24** [comment]
Pas faux. Ce qui soulève un problème idiot: qu'est ce qui se passe si le titre d'un contenu est trop long ?

**Comment by Eskimon** [comment]
Il est tronque. Je me rappelle plus avoir dit ça, mais c'est vrai que l'information apportée est faible non (tu ira plus voir un sujet si le type est précisé ?)

**Comment by Vayel** [comment]
> On ne peut pas trop juger pour l'instant vu qu'il n'y a pas de bêta pour les articles mais, à terme, il me semble intéressant de pouvoir trier les sujets selon le type de contenu. ^^

Il y a tout de même une différence entre relire un big-tuto et un article. Ca permettrait également de différencier les sujets de bêta de ceux posant une question du genre "Pensez-vous qu'un tutoriel sur ça soit une bonne idée ?". Mais on peut laisser comme ça pour l'instant et voir si ça pose problème par la suite.

**Comment by artragis** [comment]
Vayel : peux-tu ouvrir un topic sur le forum (sûrement dans bug&suggestions) pour que la communauté décide?

**Comment by Vayel** [comment]
[Done](https://zestedesavoir.com/forums/sujet/3505/tags-des-sujets-des-contenus-en-beta/)

**Comment by artragis** [comment]
Quelle réponse aporte-t-on à ça du coup @Eskimon ?

**Comment by pierre-24** [comment]
Je pense qu'il est en vacance, notre CdP :-)

**Comment by Vayel** [comment]
Au pire, on laisse comme ça en attendant. Le type est précisé dans le [premier message](https://github.com/Vayel/zds-site/blob/messages/templates/tutorialv2/messages/beta_activate_topic.md). Si jamais on le demande, il suffira d'ajouter la fonctionnalité.

**Comment by pierre-24** [comment]
De toute façon, y'a pas le feu au lac, à priori la zep-12 peut pas sortir avant #51, et c'est un gros chantier en lui-même. Donc on a encore le temps de statuer sur les détails d'ici là ;)

**Comment by artragis** [comment]
Rien n'y fait on dirait. Je pense que ça va devenir une évolution pour quand les tags seront mieux intégrés.

**Comment by Vayel** [comment]
Ouep. On ne va pas bloquer la ZEP pour ça.

**Comment by artragis** [comment]
évol + close.
