### ISSUE TITLE
Migrer la commande pdf_generator

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#178]
parce que pour l'instant elle ne gère pas la zep12 mais la v1 du module du tuto (`python manage.py pdf_generator`).

PS : @spacefox, @Eskimon : ne pensez-vous pas qu'il serait plus judicieux de mettre cette commande en tachecron et de ne pas faire la génération de pdf lors de la publciation, ça génère pas mal d'erreur 500 et fait planter les workers.

**Comment by pierre-24** [comment]
Moui. Ceci dit, je me suis un peu cassé la tête pour plus avoir de 500 à la publication  (séparer le dossier de build de celui publié aide beaucoup, on essaye plus d'accéder à des trucs qui existent pas)

**Comment by artragis** [comment]
je comprends, mais quand pandoc plante après 20 secondes de lancement, ça fait quand même planter le serveur de test, je pense que c'est pareil pour les worker.

**Comment by pierre-24** [comment]
Ah, ok :)

J'avoue que comme on a pas ça en local, c'est difficile de se rendre compte. 

Disons que l'idée est pas déconnante, mais que ça reporte le problème, et ça rend éventuellement plus complexe de tracker les erreurs, non ?

**Comment by artragis** [comment]
évidemment, c'est le mot.

**Comment by pierre-24** [comment]
Voilà voilà, au moins la commande est créée, avec le bout de TU et la doc.

(par contre, la QA, c'est à la maison, pour celle là)

**Comment by artragis** [comment]
Bon ça marche, j'ai quelques trucs bien marant, mais ça marche.
Je ferme
