### ISSUE TITLE
Dédoublement des tutoriels sur la page d'accueil

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#180]
Si on republie, un tutoriel déjà validé, il apparaît en double sur la page d’accueil et le titre de l'ancien est écrasé par le nouveau.

![bug-page-accueil](https://cloud.githubusercontent.com/assets/6099338/8430297/6d55d68a-1f30-11e5-8fb8-8702e9b461a8.png)

**Comment reproduire:**
- Importer un tutoriel
- Faire des modifications
- Valider le tutoriel
- Ajouter 2 à la fin du titre 
- Republier

**Comment by artragis** [comment]
Ok je crois savoir d'où ça vient. si j'ai le temps je le fais avant ce soir, sinon @pierre-24 c'est juste le filtre qu'il faut changer pour qu'il ne prenne pas _tous_ les PublishedContent mais uniquement ceux qui se referent à `public_version` dans PublishableContent.

**Comment by DevHugo** [comment]
Si on peut même plus vous ralentir avec des bugs … Pire qu’efficace.

**Comment by artragis** [comment]
Je mts en "need qa" parce que j'ai pas le droit de faire la qa moi même, mais ça semble bon et en plus j'économise encore 4 requêtes sans faire d'effort supplémentaire.

**Comment by pierre-24** [comment]
Donc ça bugge, et au final on fait de l'opti :o 

Il est temps qu'on prenne des vacances ^^

**Comment by pierre-24** [comment]
QA ok :)
