### ISSUE TITLE
erreur 500 sur le get de acepter validation

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#184]
Si vous vous rendez à zds.francoisdambrine.me/validations/accepter/185/ vous obtenez une 500. Il faut forcer la redirection ou lever une 404 quand on fait un GET sur cette page. 
Voilou.

**Comment by pierre-24** [comment]
Je te parie qu'il lui manque le truc pour la changer en _modale_ ;)

**Comment by artragis** [comment]
:p Je pense plutôt que c'est un cas qu'on n'a pas prévu car il n'a aucune
utilité.

Le 3 juillet 2015 10:08, Pierre Beaujean notifications@github.com a écrit
:

**Comment by pierre-24** [comment]
... Il contient quoi le 185 ???

**Comment by artragis** [comment]
la fabrication numérique.
Il est impossible à publier sur mon serveur.

2015-07-03 10:41 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by pierre-24** [comment]
J'arrive même pas à le trouver dans la liste des tutos à valider o_O

(par contre, j'ajoute que modifier explicitement le lien fait pire que mieux: http://zds.francoisdambrine.me/validations/accepter/4/, on a aussi une erreur 500 alors qu'au mieux, ça devrait être 404)

**Comment by artragis** [comment]
je répète : c'est parce qu'on n'a pas prévu de protéger le GET : cette url
ne doit être accessible qu'avec POST, pas autrement.

Le 3 juillet 2015 13:30, Pierre Beaujean notifications@github.com a écrit
:

**Comment by pierre-24** [comment]
Aaaaaaaaaaah, ok ^^

j'avais pas compris (on dira que c'est la chaleur)

**Comment by artragis** [comment]
need qa

**Comment by Vayel** [comment]
Fofèrekwa ?

**Comment by artragis** [comment]
tu regardes que http://zds.francoisdambrine.me/validations/accepter/185/ est innaccessible et que le message d'erreur te dit bien que c'est parce que c'est en GET .

**Comment by Vayel** [comment]
```
Page not found (404)
Request Method:     GET
Request URL:    http://zds.francoisdambrine.me/validations/accepter/185/

Validation acceptance is not reachable with GET method
```

**Comment by artragis** [comment]
Donc c'est bon.
On valide et on ferme.

2015-07-06 14:32 GMT+02:00 Vincent notifications@github.com:
