### ISSUE TITLE
Protéger la galerie contre sa propre suppression si elle est liée à un contenu

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#185]
Actuellement, si on supprime une galerie liée à un contenu, ledit contenu est immédiatement supprimé. Il serait bien d'éviter ce comportement.

(mais c'est le contenu qui est lié à la galerie et pas l'inverse, ce qui complique un peu les choses)

**Comment by artragis** [comment]
need qa

**Comment by Vayel** [comment]
On me dit que la galerie ne peut pas être supprimée parce qu'elle est liée à un tutoriel existant. Et ça me fait aussi ça avec les galeries d'articles, mais le message d'erreur n'est plus bon du coup.

**Comment by artragis** [comment]
sniff.

**Comment by Vayel** [comment]
Pourquoi ? On veut pouvoir supprimer une galerie attachée à un contenu ?

**Comment by artragis** [comment]
non, faut que j'aille trifouiller le code pour faire coincider "tutoriel"
et "article" et ça me rend triste d'échouer à la QA pour ça (merci de
l'avoir faite).

2015-07-06 14:39 GMT+02:00 Vincent notifications@github.com:

**Comment by artragis** [comment]
voilà

**Comment by Vayel** [comment]
> La galerie 'qa32tuto' ne peut pas être supprimée car elle est liée **à le** tutoriel qa32tuto.
> 
> La galerie 'qa32ar' ne peut pas être supprimée car elle est liée à l'article qa32ar.

Il y a un problème dans la première phrase.

Sinon, il y a des apostrophes autour du nom de la galerie, mais pas de celui du contenu. J'en mettrais partout. Et même plutôt des guillemets, français : 

> La galerie « qa32tuto » ne peut pas être supprimée car elle est liée au tutoriel « qa32tuto ».
> 
> La galerie « qa32ar » ne peut pas être supprimée car elle est liée à l'article « qa32ar ».

**Comment by pierre-24** [comment]
> Et même plutôt des guillemets, français

Y'a pas vraiment de règle à ce niveau là, et je pense que je suis du genre à faire _une fois sur deux_ en fonction de mon humeur. 

Disons que l'endroit ou c'est le plus employé, c'est les MPs (oui, ta PR), donc si tu t'es tenu à cette règle, autant qu'on s'y aligne, mais est-tu sur de l'avoir employée partout ?

**Comment by Vayel** [comment]
J'utilise toujours des guillemets français pour les textes "officiels" (tutoriels notamment).

**Comment by pierre-24** [comment]
Effectivement, j'ai regardé, il y en a partout. Du coup ...

**Comment by artragis** [comment]
je vous laisse gérer., pas le temps today.

2015-07-07 14:29 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by Vayel** [comment]
C'est [ici](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/gallery/views.py#L181).

Plusieurs questions : 
- Pourquoi a-t-on deux cas d'erreur ? Quelle est la différence entre ancien et nouveau système de ce côté-là ?
- Peut-on de manière simple savoir si le contenu est un article ou un tutoriel ?

**Comment by pierre-24** [comment]
Ah, j'étais dessus, mais si tu veux t'en occuper, je t'en prie :)

On a deux cas d'erreurs parce que avant, un article n'avais pas de galerie, ça concernait uniquement les tutoriels. Et sinon, `content.type` contient soit "TUTORIAL" soit "ARTICLE", donc il te suffit de remplir la variable `_type` correctement en fonction :)

**Comment by pierre-24** [comment]
(ps: TU :p )

**Comment by Vayel** [comment]
Je veux bien que tu t'en charges. C'est chiant parce que [textual_type](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/models/models_database.py#L119) ajoute un extrait. Du coup, c'est galère pour récupérer le type du contenu en français.

**Comment by pierre-24** [comment]
Voilà. Par contre, la QA va être plus complexe, j'ai rétabli l'ancien comportement qui empêche de cocher sur la case si le tuto est lié à la galerie (oui, ça fait ça en prod)

**Comment by Vayel** [comment]
Euh non, en prod on a : "La galerie 'Introduction au protocole WAMP ' ne peut pas être supprimée car elle est liée à un tutoriel existant.", ce qui me parait plus explicite.

**Comment by pierre-24** [comment]
Bon, je me mange des effets retords de mes propres QA, alors. Je supprime ce comportement ;)

**Comment by pierre-24** [comment]
@Vayel ? (c'est passé sur le serveur :) )

**Comment by Vayel** [comment]
C'est parfait chef.

**Comment by pierre-24** [comment]
C'est parti :)

**Comment by Vayel** [comment]
Si je puis me permettre de chipoter, je remplacerais le texte "Le tutoriel « qa185tuto » est lié à cette galerie" à droite par "La galerie est liée au tutoriel « qa185tuto ».".

**Comment by Vayel** [comment]
Je m'en occupe.
