### ISSUE TITLE
Bouton lecture zen

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#187]
Il a une sale gueule. Presque invisible.

**Comment by pierre-24** [comment]
Moui. Y'a pas un truc en _prod_ comme ça ?

(pour commencer, je demanderai un `npm run gulp -- build` à @artragis pour être sur)

**Comment by artragis** [comment]
C'est effectivement ça qui manque, ça vient, ça vient.

**Comment by artragis** [comment]
je ferme, c'est bon.
n'oublions pas que mon serveur est un serveur de test et il voit passer pas mal de versions instables ducoup parfois le front généré n'est pas le bon.
