### ISSUE TITLE
MP d’accueil :)

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#188]
Juste pas oublier de changer les liens du MPs qu'on reçoit à sa première connexion ("article" et "tutoriels")

**Comment by artragis** [comment]
quel fichier?

**Comment by pierre-24** [comment]
Là : https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/member/views.py#L781

**Comment by artragis** [comment]
Voilà

**Comment by Vayel** [comment]
Seul artragis peut créer un membre, non ?

**Comment by pierre-24** [comment]
Disons que pour la confirmation d'inscription, tu ne recevra probablement jamais le mail avec le _token_, donc t'es coincé. À tester en local ;)

**Comment by Vayel** [comment]
Au pire, je peux m'inscrire avec une adresse bidon, non ?

**Comment by pierre-24** [comment]
Même. Sans le token, tu sais pas lancer la procédure de confirmation d'inscription qui envoi le MP. T'inquiète va, je vais faire ça en local dans 5 minutes ;)

**Comment by pierre-24** [comment]
Rapport de QA: OK :)
