### ISSUE TITLE
Supprimer une galerie depuis la galerie

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#195]
https://zestedesavoir.com/forums/sujet/3544/supprimer-une-galerie-depuis-la-galerie/

On peut l'intégrer à cette ZEP, non ? J'imagine que ce n'est pas très compliqué à faire.

**Comment by pierre-24** [comment]
Non, c'est clairement _hors-scope_, ce serait outrepasser le but de la ZEP-12 ;)

**Comment by pierre-24** [comment]
(mais par contre, tu peux passer une PR sur le dépôt principal, c'est méga-facile à faire ;) )
