### ISSUE TITLE
Gestion de la "slug pool" quand on importe une archive

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#196]
Pour reproduire le bug:
- Créer un tuto avec deux extraits
- Télécharger l'archive et éditer le "manifest.json" pour que ces deux extraits aie le même slug
- Ré-importer l'archive

Résultat: une erreur 500 disant « slug "xxxx" already in the slug pool ! »

Faut renvoyer une erreur qui ressemble un peu plus à quelque chose ;)

**Comment by artragis** [comment]
Non, il suffit de bien utiliser la fonction qui fait des add_extract et add_container pour que le second paramètre vaille "True".

**Comment by pierre-24** [comment]
Mmmh ... Difficile, parce que cette fonction utilise ce qui se passe avec `load_content_from_json()`. Quand bien même, ta proposition est alors de regénérer tout les slugs, ce qui foutrait un bazar monstre avec ta propositon précédente de ne pas les modifier ;)

**Comment by artragis** [comment]
Du coup le message est assez clair, je toruve non? on ne peut pas tout 
charger car il y a des slug identiques. (sauf si le problème est que ça 
génère une 500, si c'set ça, on fait un try/catch et on met le bon 
message dans messages.error)

**Comment by pierre-24** [comment]
Tout à fait, ce que j'ai fait :)

**Comment by artragis** [comment]
Pour la QA:

créez **en local** un tuto qui a le manifeste suivant (et les fichiers qui vont avec): 

``` json
{
    "object": "container", 
    "slug": "qa-du-bug-de-pierre", 
    "title": "QA du bug de Pierre", 
    "introduction": "introduction.md", 
    "conclusion": "conclusion.md", 
    "children": [
        {
            "object": "extract",
            "slug": "premier-slug",
            "title": "un_titre",
            "text": "un_titre.md"
        }
,
       {
            "object": "extract",
            "slug": "premier-slug",
            "title": "un_titre2",
            "text": "un_titre2.md"
        }
    ], 
    "version": 2, 
    "description": "async et await sont vos amis.", 
    "type": "TUTORIAL", 
    "licence": "CC-BY-SA"
}

```

Importez l'archive ainsi formée,

observez que nous n'avons pas une page 500 et que le message anonçant le problème apparait.

**Comment by artragis** [comment]
QA OK.
