### ISSUE TITLE
Créer une option pour désactiver l'auto-build des PDFs

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#198]
Ça sera moins pénible :)

**Comment by pierre-24** [comment]
Pour la QA: 
- Mettre l'option `build_pdf_when_published` à `False`
- Publier un tuto et constater que le PDF n'est pas généré
- Vous pouvez vous amuser à le générer avec `generate_pdf` :p

**Comment by artragis** [comment]
ce qui d'ailleurs pourra nous permettre d'accélerer les TU qui n'ont pas besoin de la génération de PDF.

**Comment by pierre-24** [comment]
Oh, tient, j'avais oublié que j'avais une PR en cours :p 

> ce qui d'ailleurs pourra nous permettre d'accélerer les TU qui n'ont pas besoin de la génération de PDF.

Effectivement, je vais voir si je peux pas faire ça dans le même temps =)

**Comment by artragis** [comment]
QA OK
