### ISSUE TITLE
Auteur des messages automatiques de bêta

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#201]
Aujourd'hui, quand un message automatique est posté avec le compte de l'OP. Peut-être serait-il préférable de le faire avec celui ayant fait l'action (mise à jour de la bêta, fermeture de la bêta...) ?

**Comment by pierre-24** [comment]
Je trouve la réflexion pas idiote, dans le sens ou actuelement, puisqu'on se sert du _bot_, l'auteur qui balance en bêta recoit une notif'. Là, seul les autres auteurs, le cas échéant, en recevraient une. Donc ça me semble pas déconnant.

**Comment by Vayel** [comment]
Ouip, c'est un autre point : faire suivre le sujet à tous les auteurs.

**Comment by pierre-24** [comment]
J'ai en tête que c'est déjà le cas, mais je peux me tromper ;)

**Comment by Vayel** [comment]
Si je me souviens bien, ça ne l'est pas : je ne suivais pas, de mémoire, automatiquement le sujet sur la récurrence.

**Comment by pierre-24** [comment]
En effet, je pensais qu'on le faisait déjà sur la ZEP-12, mais [en effet, c'est pas le cas](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_contents.py#L1235).

**Comment by Vayel** [comment]
J'ouvre une issue.

**Comment by pierre-24** [comment]
Mmmmh, [en fait c'est déjà le cas](http://zds.francoisdambrine.me/forums/sujet/25/un-test-pour-le-fun/) (user a mis en bêta et admin l'as mis à jour). Je regarde ce que je peux faire pour l'autre issue ;)
