### ISSUE TITLE
Faire suivre automatiquement le sujet en bêta par tous les auteurs

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#202]
Tout est dans le titre. Apparemment, c'est [par là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_contents.py#L1235).

**Comment by artragis** [comment]
Rapport de QA:
- création d'un tuto avec admin
- ajout d'un auteur (user)
- mise en béta

résultat : (n'ayant pas bien compris le comportement attendu, je ne fais que décrire le comportement obtenu, à vous de voir si c'est pas comme vous le voulez)
- admin a créé le topic de beta
- user a un TopicFollowed MAIS le message n'est pas marqué comme nouveau pour lui
- le topic de beta apparait dans le menu de droite (sujets suivis)

**Comment by Vayel** [comment]
> MAIS le message n'est pas marqué comme nouveau pour lui

Je ne pense pas qu'on puisse remédier à ça sans faire de bidouille, puisque ça reviendrait à être notifié de la **création** d'un sujet.

Je détaille la QA : 
- Créer un tutoriel, avec admin par exemple
- Ajouter un auteur, user par exemple
- Mettre en bêta, avec admin par exemple
- Poster un message dans le sujet de bêta, avec un autre compte que admin et user
- Constater que admin a une notification (normal) **et** que user en a une (le but de cette issue)

**Comment by artragis** [comment]
Alors QA OK!
