### ISSUE TITLE
Le HTML du message "Importer un nouveau contenu" n'est pas interprété

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#204]
Sur la page: contenus/importer/archive/nouveau/ on peut voir le message suivant 

> "Pour importer des images, veuillez spécifier la seconde archive. Les motifs `![légende](archive:chemin/vers/image.extension)`, référant aux images stockées dans l'archive, seront remplacés par les URLs générées par le site."

**Comment by pierre-24** [comment]
Non, c'est fait exprès !! Ça veut effectivement dire que ce motif en markdown sera interprété comme tel. Après, si t'as pas compris instinctivement, c'est que le message est pas clair.

Une idée de comment le formuler ? :)

**Comment by DevHugo** [comment]
Si c'est clair lu trop vite.
