### ISSUE TITLE
PDF en bêta

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#205]
Serait-il facile de permettre le téléchargement sous forme de PDF des contenus en bêta ? Ce serait pratique pour effectuer de la relecture hors-ligne.

**Comment by pierre-24** [comment]
Le problème, c'est que pour obtenir un PDF, il faut lancer toute la "machine" _pandoc_, c'est à dire réaliser un seul gros fichier markdown, puis le passer à la moulinette et ainsi de suite, soit une opération très coûteuse en terme de ressource (il suffit de voir les temps de publication sur le serveur d'artragis, qui s'approchent de la réalité). Si on donne ce "pouvoir" aux auteurs, on fait tomber la _prod_. 

Donc à l'heure actuelle, c'est absolument pas réaliste.

Ceci dit, comme je le disais sur un autre sujet, rien n'empêche de coder un outil externe via l'export sous forme d'archive :)
