### ISSUE TITLE
liste de tous les tickets

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#206]
Ce ticket est là pour lister tous les tickets d'upstream qu'on résoud avec la zep 12
- [x] [2540](https://github.com/zestedesavoir/zds-site/issues/2540) (SEO)
- [x] [2405](https://github.com/zestedesavoir/zds-site/issues/2405) (BUG)
- [x] [2400](https://github.com/zestedesavoir/zds-site/issues/2400) (BUG)
- [x] [2308](https://github.com/zestedesavoir/zds-site/issues/2308) (BUG)
- [x] [2069](https://github.com/zestedesavoir/zds-site/issues/2069) (BUG, à vérifier)
- [x] [1999](https://github.com/zestedesavoir/zds-site/issues/1999) (SEO)
- [x] [1762](https://github.com/zestedesavoir/zds-site/issues/1762) (EVOLUTION)
- [x] [1405](https://github.com/zestedesavoir/zds-site/issues/1405)
- [x] [2274](https://github.com/zestedesavoir/zds-site/issues/2274) (EVOLUTION)
- [x] [2636](https://github.com/zestedesavoir/zds-site/issues/2636) (BUG)
- [x] [1443](https://github.com/zestedesavoir/zds-site/issues/1443) (EVOLUTION)
- [x] [1319](https://github.com/zestedesavoir/zds-site/issues/1319) (EVOLUTION)
- [x] [1509](https://github.com/zestedesavoir/zds-site/issues/1509) (EVOLUTION)
- [x] [1519](https://github.com/zestedesavoir/zds-site/issues/1519) (BUG, à vérifier)
- [x] [1654](https://github.com/zestedesavoir/zds-site/issues/1654) (BUG, à vérifier, mais logiquement OK)
- [x] [1599](https://github.com/zestedesavoir/zds-site/issues/1599) (EVOLUTION)
- [x] [1780](https://github.com/zestedesavoir/zds-site/issues/1780) (EVOLUTION, UNIQUEMENT IMPORT)
- [x] [850](https://github.com/zestedesavoir/zds-site/issues/850) (BUG)
- [x] [1226](https://github.com/zestedesavoir/zds-site/issues/1226) (BUG)
- [x] [949](https://github.com/zestedesavoir/zds-site/issues/949) (EVOLUTION)
- [x] [2936](https://github.com/zestedesavoir/zds-site/issues/2936) ("BUG")
- [x] [2933](https://github.com/zestedesavoir/zds-site/issues/2933) (EVOLUTION)
- [x] [2939](https://github.com/zestedesavoir/zds-site/issues/2939)

**Comment by Vayel** [comment]
Pour les bugs, je peux regarder sur ton instance ?

**Comment by artragis** [comment]
ok course (notons que ceux cochés ont déjà été testés)

**Comment by Vayel** [comment]
2069 semble bon. Par contre, suite à un déplacement, on est redirigé dans l'élément déplacé. Il serait préférable de rester au niveau du parent, au cas où on voudrait déplacer d'autres choses.

**Comment by Vayel** [comment]
1519 OK.

**Comment by Vayel** [comment]
1654 OK.

**Comment by artragis** [comment]
pour le 2069 on met comme ça, et on fera comme tu as fait avec la ZEP 04 : on proposera ça sur le forum une fois que ça sera mis en palce.

**Comment by pierre-24** [comment]
Grâce à la perspicacité de Vayel, je rajoute le 2936, que je vais régler de suite.

**Comment by Vayel** [comment]
J'ai pas compris : 

> mais on c'est trompé de comportement sur la suppression.

**Comment by Vayel** [comment]
Un de plus : https://github.com/zestedesavoir/zds-site/issues/2939

**Edit :** en fait, non.

**Comment by pierre-24** [comment]
Et on oublie pas les [tickets évolution](https://github.com/artragis/zds-site/issues?q=label%3A%C3%A9volution+is%3Aclosed), à remonter sur le dépot principal le cas échéant.

(je pensais qu'on en avais plus, mais soit)
