### ISSUE TITLE
Supprimer le contenu doit enlever de la liste d'auteur

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#207]
Autrement dit,
- Si il y a plusieurs auteurs et que l'un clique sur "supprimer", c'est lui qui est retiré de la liste d'auteur et le contenu n'est pas supprimé
- Si il n'y a qu'un seul auteur, le contenu est supprimé normalement

(comme c'est un comportement de _prod_, autant le remettre pour éviter les surprises)

**Comment by Vayel** [comment]
Par "supprimer", tu veux dire le contenu ?

Dans le bug que j'ai relevé, je parlais de se soi-même retirer des auteurs et d'être renvoyé vers le contenu donc vers une 403, pas de supprimer le contenu.

**Comment by pierre-24** [comment]
En fait:
1. En _prod_, actuellement, quand il y a plusieurs auteurs et que l'un deux clique sur "supprimer", l'auteur est juste retiré de la liste (et le contenu n'est pas supprimé). Puis tu te mange une 403
2. Le comportement actuel de la ZEP-12 est le suivant: quelque soit le nombre d'auteurs, si y'en a un qui clique sur "supprimer", le contenu est détruit, et on est bien redirigé.

Donc cette PR fait en sorte qu'on soit _iso_-prod, on a le bon comportement quand on a plusieurs auteurs ET on est bien redirigé sans 403 :-)

Autrement dit, ton bug est corrigé sur la ZEP-12, mais je corrige le fait que la ZEP-12 ne se comporte pas comme ce qui est actuellement.

**Comment by pierre-24** [comment]
EDIT parce que j'ai vu ton message sur le forum: oui, moi je parle bien du bouton supprimer le contenu

**Comment by Vayel** [comment]
Parfait. :)

**Comment by pierre-24** [comment]
Hop, QA faisable, artragis l'as mis sur son serveur

# Note de QA
- Créer un article (ou un tuto) avec un auteur A
- Rajouter un auteur B et C
- Vérifier que quand A se retire des auteurs, il n'as pas de 403
- Se connecter avec B, cliquer sur "supprimer le contenu"
- Se connecter avec C, vérifier que le contenu n'as pas disparu, mais que C est bien seul auteur
- Supprimer le contenu avec C, vérifier qu'il a bien disparu de la BDD (et, on l'espère, du système de fichier, mais on a un test pour ça :) )

**Comment by Vayel** [comment]
Ok ici, sauf pour le troisième point, pour lequel j'ai ouvert une issue. Si vous voulez regarder la BDD, le tutoriel s'appelait qa207. Plus précisément, j'ai : 
- Créé avec admin
- Ajouté user et user1
- Enlevé admin des utilisateurs avec admin : erreur (cf issue)
- Supprimé le contenu avec user : user enlevé des auteurs, contenu existant
- Supprimé le contenu avec user1 : user1 enlevé des auteurs, contenu existant
- Supprimé le contenu avec admin : contenu existant ?

**Comment by Vayel** [comment]
On peut fermer ici en principe. Peut-être vérifier en base si qa207 n'est bien plus là.
