### ISSUE TITLE
Impossible de s'enlever des auteurs

### ISSUE THREAD

**Issue by Vayel** [artragis/zds-site#210]
- Créer un tutoriel avec A
- Ajouter un auteur B
- Avec A, enlever A des auteurs
- Rien ne se passe
- Avec A, enlever B des auteurs
- Ok

Au passage, quand un auteur est seul, il est écrit "Vous êtes seul". Il serait préférable d'avoir le bouton de suppression et de supprimer le tutoriel si l'auteur s'enlève.

**Comment by pierre-24** [comment]
Quand tu dis "Avec A, enlever A des auteurs", c'est avec quel bouton ? (vraie question)

**Comment by artragis** [comment]
barre latérale -> gérer les auteurs -> supprimer à côté du pseudo adéquat.

**Comment by Vayel** [comment]
J'ai vu le message d'artragis apparaître en direct pendant que j'écrivais. x)

**Comment by pierre-24** [comment]
[Cette ligne](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_contents.py#L1647) me semble empêcher que l'auteur ne se vire lui même, je me trompe ?

**Comment by artragis** [comment]
Je propose ce code à la place

``` python
class RemoveAuthorFromContent(AddAuthorToContent):

    def form_valid(self, form):
        for user in form.cleaned_data["users"]:
            if user in self.object.authors.all() and self.object.authors.count() > 1: # if sent user is really an author
                gallery = UserGallery.objects.filter(user=user, gallery=self.object.gallery).first()
                gallery.delete()
                self.object.authors.remove(user)
            else: # if user is incorrect or alone
                messages.error(self.request, _(u'Vous êtes le seul auteur de ce tutoriel ou le membre sélectionné en a déjà quitté la rédaction.'))
                return redirect(self.object.get_absolute_url())

        self.object.save()
        if user != self.request.user: # if the removed author is not current user
            messages.success(self.request, _(u'Vous avez enlevé {} de la liste des auteurs'.format(user.username))
            self.success_url = self.object.get_absolute_url()
        else: # if current user is leaving the content's redaction, redirect him to a more suitable page
            messages.success(self.request, _(u'Vous avez quitté la liste des auteurs')
            self.success_url = reverse("content:index")
        return super(RemoveAuthorFromContent, self).form_valid(form)
```

**Comment by artragis** [comment]
Désolé pour les multiples éditions.

**Comment by pierre-24** [comment]
Moi, à la lecture, ça me semble bon :)

Ce qui me rappelle au passage que [`DeleteContent()`](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_contents.py#L303) ne renvois pas du tout de `messages.success()` ^^

**Comment by artragis** [comment]
Je te laisse faire une petite PR.

2015-07-21 10:32 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by pierre-24** [comment]
Voilààààà :)

**Comment by Vayel** [comment]
C'est bon mais on est redirigé vers le contenu donc vers une 403. Il faudrait l'être vers la liste de nos contenus.

**Comment by pierre-24** [comment]
[ça m'étonne](https://github.com/artragis/zds-site/pull/211/files#diff-fbcd4f81f2653c40ee3aae43c22d9552R1706) :o

**Comment by pierre-24** [comment]
(mais je confirme, ce qui m'étonne d'autant plus)

**Comment by Vayel** [comment]
Juste pour rappeler qu'il y a un bug à corriger ici (changer les labels serait une bonne idée). :)

**Comment by artragis** [comment]
corrigé, merci le debugger pycharm et à mort l'héritage :p

**Comment by Vayel** [comment]
Le serveur renvoie une 502. Tu me dis quand je peux QA. ^^

**Comment by artragis** [comment]
voilà

**Comment by Vayel** [comment]
Ca fonctionne lorsqu'il y a plusieurs auteurs. Seulement : 
- Le message de succès affiché est "Vous avez bien quitté la rédaction de ce tutorial". Il serait préférable d'avoir : "Vous avez bien quitté la rédaction de ce tutoriel.". Pour les articles, il manque juste un point à la fin de la phrase.
- Quand l'auteur est seul, il ne peut pas s'enlever des auteurs (il est écrit "Vous êtes seul"). Il serait préférable de le permettre et de considérer qu'un contenu sans auteur est un contenu à supprimer (il faudrait alors un message de confirmation). Pour cela, il suffit, me semble-t-il, d'attribuer au bouton "Supprimer" en face de l'unique auteur le même comportement que celui "Supprimer le tutoriel".

**Comment by artragis** [comment]
> Il serait préférable de le permettre et de considérer qu'un contenu sans
> auteur est un contenu à supprimer (il faudrait alors un message de
> confirmation).

je ne suis pas d'accord. Il y a un bouton pour supprimer. Je considère que
si la personne a été jusque dans la liste d'auteurs et a appuyé sur
"supprimer" à côté de son nom a soit fait une erreur soit il a fait un
chemin vraiment étrange. Je préfère dire "heu là on sait pas ce que tu veux
faire" que "es-tu sûr d'être sûr d'être sûr". On n'est pas windows et UAC.

Après, ouai, faudrait dire "tutoriel" et "article" ou "contenu" plutôt que
tutorial :p

**Comment by Vayel** [comment]
En effet, tu as raison.

**Comment by artragis** [comment]
typo corrigée, je ferme.
