### ISSUE TITLE
attribution d'un tuto sdz

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#217]
Salut,
cette [issue](https://github.com/zestedesavoir/zds-site/issues/2948) me fait penser qu'on a rien prévu, mais je sais pas vraiment ce que c'est que cette histoire.

**Comment by artragis** [comment]
juste pour dire que le bug est aussi chez nous.
par contre faudra ajouter ce cas au script de migration bien que je ne sache pas trop comment ça marche. En plus j'ai l'impression qu'on ne s'en sert nulle part.

**Comment by pierre-24** [comment]
Mmmh, c'est une fonction pour les admins. Comme ont avait dit que ceux-ci s'occuperait de tout convertir en tuto et de les attribuer à "auteur externe" le temps de, je dirais qu'il n'y a rien à faire. Pinge qui de droit pour être sur :)

**Comment by artragis** [comment]
d'accord @quidedroit.

je n'oublie pas @spacefox, @firm1 @shigerum

**Comment by SpaceFox** [comment]
Je confirme
