### ISSUE TITLE
La liste des catégories des tutoriels n'est pas correctement affichés

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#220]
Un tutoriel qui à plusieurs catégories n'est pas correctement affichés :

![plusieurscategoriestutoriels](https://cloud.githubusercontent.com/assets/6099338/9247409/1043c7ae-41b3-11e5-8049-6ccc3428b210.png)

**Comment reproduire ?**
- Créé un contenu avec plusieurs catégories et le publier

**Comment by artragis** [comment]
corrigé.
