### ISSUE TITLE
Le contenu du manifest dans l'archive n'est pas cohérent

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#221]
Le contenu du manifest de l'archive téléchargé n'est pas correct. 

**Comment reproduire ?**
- Créé un contenu avec une description et aucune partie et publier le.
- Changer la description et le titre et ajouter une partie, publier le.
- Télécharger l'archive de la version publié, vérifier que le manifest ne correspond pas et correspond à l'ancienne version du tuto.

**Comment by artragis** [comment]
j'ai donc créé un contenu avec une description

au début j'ai ça : 

``` json
{
    "object": "container", 
    "slug": "bbbbb", 
    "title": "bbbbb", 
    "introduction": "introduction.md", 
    "conclusion": "conclusion.md", 
    "children": [], 
    "version": 2, 
    "description": "gregrger", 
    "type": "TUTORIAL", 
    "licence": "Beerware"
}
```

je le renomme, change le titre et lui ajoute une partie, puis je le publie et j'obtiens le même manifeste dans l'archive alors que tous les autres "extra" sont OK, il y a donc bel et bien une erreur.

PS je n'arrive pas à dépublier le contenu http://zds.francoisdambrine.me/tutoriels2/110/bbbbbc/

**Comment by DevHugo** [comment]
~~J'ai remarqué aussi un autre problème qui peut-être lié.~~

~~Pour un tutoriel _non publié_, essaye de renommer le nom de la partie (pas l'introduction et pas la conclusion, vraiment le nom de la partie). Si tu essaye de télécharger l'archive, le nom des dossiers dans l'archive et le manifest ne change pas. Si tu le fait avec l'introduction de la partie ou la conclusion la, ça marche.~~

EDIT: Rien dit, ça marche en fait.

EDIT 2: J'ai trouvé.

**Comment by artragis** [comment]
Corigé

**Comment by DevHugo** [comment]
Du coup, on ferme
