### ISSUE TITLE
Le CSS de la ZEP-03 est cassé

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#223]
Le design de la page est cassé.

![zep03](https://cloud.githubusercontent.com/assets/6099338/9248126/85b1bf2c-41b9-11e5-8ec7-c6aec0a712a8.png)

**Comment by Situphen** [comment]
La page [`templates/tutorial/tutorial/help.html`](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorial/tutorial/help.html) a été modifiée par la ZEP 04 mais d'après ce que je vois vous n'avez pas reporté ces modifications sur [`templates/tutorialv2/view/help.html`](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorialv2/view/help.html) !

**Comment by artragis** [comment]
tu peux faire une PR sur mon dépôt, je la mergerai quand je serai chez moi.

**Comment by Situphen** [comment]
Je n'ai malheureusement pas le temps maintenant. Je le fais ce soir si j'ai le temps ou sinon demain. :)
