### ISSUE TITLE
Si un contenu demande de l'aide sur un contenu spécifique, toutes les icones s'affichent

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#224]
Ici test ne demande qu'un correcteur, tous les icones sont affichées.

![zep03](https://cloud.githubusercontent.com/assets/6099338/9248145/af708a8c-41b9-11e5-8b3e-fbb0ab5ac5a2.png)

**Comment by Situphen** [comment]
Lié à #223 je suppose

**Comment by DevHugo** [comment]
Surement ^^ ! On te laisse la main, chef !
