### ISSUE TITLE
On doit être connecté pour voir un tutoriel en beta

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#225]
Si on veut accéder à un contenu en beta, on doit être connecté sinon on est rediriger vers la page de connexion.

**Comment by artragis** [comment]
peux-tu exprimer la phrase en terme de ce qui marche ce qui ne marche pas.

Est-ce que, à l'heure actuelle un anonyme peut voir une beta sur mon serveur?

Si oui, bad, sinon je ferme.

**Comment by DevHugo** [comment]
J'ai perdu une bonne partie de mes favoris dans une manip pourrite, tu peux redonner l'adresse de ton instance ?

**Comment by artragis** [comment]
http://zds.francoisdambrine.me

2015-08-13 14:59 GMT+02:00 Hugo Courtecuisse notifications@github.com:

**Comment by DevHugo** [comment]
J'ai créé un contenu que j'ai mis en beta. Cela a créé [un topic comme celui-ci](http://zds.francoisdambrine.me/forums/sujet/29/ceci-est-un-exemple-de-contenu/?page=1#p1344). Le lien de la beta n'est accessible qu'au membres connecté ^^ ! Pourtant mon contenu, même en beta, raconte une belle histoire !

**Comment by artragis** [comment]
Ok, donc c'est normal, donc je ferme :p

Le 13 août 2015 15:18, Hugo Courtecuisse notifications@github.com a écrit
:

**Comment by DevHugo** [comment]
Ah! Tu as raison. Ça serais une bonne chose de changer ça dans le futur. C'est nul de pas pouvoir avoir accés au beta sans être connecté !

**Comment by artragis** [comment]
Au contraire ça serait une mauvaise chose de rendre totalement public des
choses non corrigées et non finalisées. La béta ça a été pensé pour que la
communauté des membres aide l'auteur, c'est pas un early access.

Le 13 août 2015 15:52, Hugo Courtecuisse notifications@github.com a écrit
:

**Comment by DevHugo** [comment]
Je comprend ton argument et je suis plutôt d'accord.
