### ISSUE TITLE
Impossible d'éditer un commentaire d'un contenu

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#226]
Si on veut éditer un commentaire d'un contenu, on se mange une erreur « TypeError at /contenus/reactions/edit/ int() argument must be a string or a number, not 'NoneType' ». 

Il faut tenter d'éditer ce genre de commentaire : 

![commentairesedition](https://cloud.githubusercontent.com/assets/6099338/9248378/aa764592-41bb-11e5-859a-85b81dda4952.png)

**Comment by artragis** [comment]
l'erreur 500 est corrigée mais il reste impossible d'éditer, je regarde ça demain.

**Comment by artragis** [comment]
corrigé complètement
