### ISSUE TITLE
Le lien dans le MP, d'ajout d'auteurs est invalide

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#231]
**Comment reproduire ?**
- Créé un contenu avec un compte (par exemple, admin).
- Ajouter un auteur au contenu
- Un mp a été envoyé sur le compte du nouveau auteur. Connectez-vous sur le compte de cet nouvel auteur et consulter le MP.

> Bonjour user,
> 
> Vous avez été intégré à la rédaction du contenu « Comment soigner sa plante verte ». La version brouillon, sur laquelle vous pourrez travailler, est disponible ici.
> 
> Plus rien maintenant ne retient votre plume, alors bon courage !

Le lien sur le mot "ici" est invalide.

**Comment by artragis** [comment]
En effet oO

**Comment by artragis** [comment]
Corrigé
