### ISSUE TITLE
Résumé de l'expérience de migration en pré-prod'

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#238]
En gros, pour ce faciliter la vie:
- Il faudrait pouvoir migrer sélectivement les articles, les mini ou les bigs-tutos
- Il faudrait pouvoir ne pas migrer ce qui l'as déjà été (mais comment ?)
- Il faudrait pouvoir exlure de la migration certaines choses (mais comment ?), ou migrer sélectivement des choses données (mais comment ?)

ping @sandhose pour d'autres retours :)

NOTE: le log de la migration : http://sprunge.us/SfFh

**Comment by artragis** [comment]
>    Il faudrait pouvoir migrer sélectivement les articles, les mini ou les bigs-tutos

déjà possible

> Il faudrait pouvoir ne pas migrer ce qui l'as déjà été (mais comment ?)

là c'est plus complexe

**Comment by sandhose** [comment]
J'ai trouvé une liste de tutos HS via: `find tutoriels-private/ -mindepth 1 -maxdepth 1 -type d '!' -exec test -e '{}/.git/refs/heads/master' ';' -print`

faudrait faire ça en prod pour vérifier si c'est propre à la preprod ou non

**Comment by pierre-24** [comment]
Tu sais la copier ici, ou c'est "privé" ?

**Comment by pierre-24** [comment]
> > Il faudrait pouvoir ne pas migrer ce qui l'as déjà été (mais comment ?)
> > là c'est plus complexe

Ben on peut comparer `tuto.old_pk + '_' + tuto.slug` avec le slug du vieux tuto (marche aussi avec les articles)

**Comment by sandhose** [comment]
```
tutoriels-private/238_decouvrir-et-utiliser-wordpress      
tutoriels-private/207_deployez-votre-site-avec-wordpress   
tutoriels-private/208_deployez-votre-site-avec-wordpress   
tutoriels-private/516_la-programmation-cobol               
tutoriels-private/467_apprenez-a-programmer-en-c           
tutoriels-private/515_la-programmation-cobol               
tutoriels-private/206_deployez-votre-site-avec-wordpress      
```

**Comment by artragis** [comment]
Problème avec le tutoriel/article
le C++14 est arrivé
en effet le slug de ce dernier a changé (de le-c14-est-arreve on passe à le-c-14-est-arrive) et du coup ça foire.

**Comment by pierre-24** [comment]
Bien vu. C'est idiot, d'ailleurs --"

**Comment by artragis** [comment]
problème : je ne vois pas d'où ça vient

**Comment by pierre-24** [comment]
Ce dernier problème est réglé. Reste les autres ^^

**Comment by pierre-24** [comment]
Tient, quid des tutos que @sandhose a mentionné plus tôt ? On envoit MP aux auteurs, ou bien ?

**Comment by DevHugo** [comment]
[La programmation cobol](https://beta.zestedesavoir.com/tutoriels/526/la-programmation-cobol/) semble marcher. 

Les deux autres, je serais pour contacter les auteurs.

**Comment by pierre-24** [comment]
"programmer en C", c'est le tuto de Taurre, qu'il a bousillé je sais pas trop comment, donc il faudra le ré-importer (il a une archive quelque part).

**Comment by pierre-24** [comment]
Note: le tuto qui pose problème porte le pk 516. Celui de prod [porte le pk 533](https://zestedesavoir.com/tutoriels/533/la-programmation-cobol/). J'en déduis que c'est pas le même et que quelqu'un a pêté un tuto sans le dire ;)

**Comment by DevHugo** [comment]
Tu veux dire que c'est bon, y'a plus aucun souci ?

**Comment by pierre-24** [comment]
Une màj pour l'indexation: http://sprunge.us/IFXM

**Comment by DevHugo** [comment]
Le mieux c'est qu'on peut quand même rechercher sur les trois contenus qui ont des erreurs. Les deux premiers semblent liés à l'absence de pubdate. 

C'est bizarre car avant il avait pas planter, donc c'est surement liés à ma dernière modification de code. Ou alors, ils y'avait pas de pubdate avant et comme avant il avait un auto_add=now, l'enregistrement ne bloquait pas.

Le dernier faut tester en local pour voir si on peut reproduire.

**Comment by pierre-24** [comment]
> Ou alors, ils y'avait pas de pubdate avant et comme avant il avait un auto_add=now, l'enregistrement ne bloquait pas.

Moi je vote pour cette option là. Même si je m'étonne d'avoir des contenus sans `pubdate` publiés dans la nature :o 

> Le dernier faut tester en local pour voir si on peut reproduire.

Ce qui m'étonne, c'est qu'il fini par `KeyboardInterupt`, comme si sandhose en avait eu marre :o

**Comment by artragis** [comment]
N'oublions pas que nous sommes sur une version du serveur sur laquelle
énormément de tests ont été réalisés. Il est probable que l'état actuel en
prod ne soit pas "pas de pubdate". Néanmoins, il faut remettre le "now" par
défaut  quand on fait un set (c'est simple ça ressemble à content.pubdate =
lavaleurquonveut or datetime.now())

**Comment by DevHugo** [comment]
Je pense que je peut rajouter une date par-défaut, c'est une ligne de code. Pour le troisième soucis, je regarde dans la soirée.

J'arrive pas à reproduire, pour le dernier mais pour les autres une PR a été lancé.

**Comment by DevHugo** [comment]
Du coup, récap, la PR pour mettre par-défaut une pubdate est passé. Il reste la dernière erreur, je sais pas pourquoi elle est la. Peut-être, est t-elle la temporairement, je propose que on laisse tomber pour cette fois et on regarde si elle est encore la, à la prochaine migration.

**Comment by sandhose** [comment]
Entre temps, l'option `--copy-repository` indiquée dans l'update.md pour l'indexation solr n'existe plus, et empêche la synchro. Faut corriger l'update.md à ce niveau la

**Comment by DevHugo** [comment]
Oups, désolé, on corrige ça.

**Comment by pierre-24** [comment]
(c'est corrigé)
