### ISSUE TITLE
Petite erreur de style sur la liste des tutoriels

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#240]
Sur [la bêta](https://beta.zestedesavoir.com/tutoriels/) :

![screenshot from 2015-08-16 20 10 51](https://cloud.githubusercontent.com/assets/7889675/9294610/09a1d42a-4453-11e5-8c69-e143c9e71263.png)

**Comment by pierre-24** [comment]
Remarque liée : la pagination est à `50`, ce qui n'est pas divisible par 3, du coup sur la dernière ligne, il n'y a que deux éléments au lieu de 3.

**Comment by artragis** [comment]
corrigé.
