### ISSUE TITLE
La migration crée un paquet monstre de notifications

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#241]
Personnellement, à ma connexion à la bêta, j'avais 69 notifications pointant sur des tutoriels que je n'ai jamais lu o_O

**Comment by pierre-24** [comment]
_j'ai rien dit_

**Comment by pierre-24** [comment]
Piste de solution: la date de tout les commentaires posté est "il y a 2h" sur la bêta a l'heure ou je poste ce message. Ce qui signifie probablement que le système crois probablement que les messages ont été repostés :)

**Comment by pierre-24** [comment]
Rapport de QA: la date des commentaires est bel et bien correcte, mais le problème n'est toujours pas résolu. Regarder du coté des `ContentRead` ?

(puisqu'on crée des nouveau à la migration)

**Comment by artragis** [comment]
Je sais pourquoi : on n'a pas mis le champ last_note à jour lors de la migration.

**Comment by pierre-24** [comment]
Ah, cool, si c'est ça c'est con à régler

**Comment by artragis** [comment]
Du moins on le fait mal : 

``` python

new_reac.pubdate = note.pubdate
        new_reac.update = note.update
        new_reac.save()

        export_read_for_note(note, new_reac, read_class)
        exported.last_note = new_reac
        for like in CommentLike.objects.filter(comments__pk=note.pk).all():
            like.comments = new_reac
            like.save()
        for dislike in CommentDislike.objects.filter(comments__pk=note.pk).all():
            dislike.comments = new_reac
            dislike.save()
```

**Comment by artragis** [comment]
je commit

**Comment by artragis** [comment]
problème non réglé mais plus précis : 

les notifications créées concernent les tutos que vous n'avez jamais lu :p

**Comment by pierre-24** [comment]
Pas que j'ai jamais lu, parce que j'en reconnais certain. Par contre, très clairement ou je n'ai jamais commenté. Moi je dirais "lu mais non commenté".

**Comment by pierre-24** [comment]
D'ailleurs : quel est l'endroit ou les notifications sont générées ? Pour être plus précis, quel est la condition qui fait apparaitre une notif ?

**Comment by artragis** [comment]
c'est quelque part dans utils/templatetags/notification il me semble.

**Comment by pierre-24** [comment]
J'ai un peu cherché, et voilà ce que j'ai fait
1. J'ai crée un article V1 avec `user`, et je l'ai fait publier. J'ai mis un commentaire dessus avec `admin`.
2. J'ai fait visiter à `staff` cet article
3. J'ai ensuite été mettre un second commentaire à cet article avec `user`
4. J'ai migré en V2

Résultat : 
- `user` n'as pas de notifs ; 
- `admin` à 2 notifs, dont la première des deux corresponds à l'ancien système, ce qui est logique ;
- `staff` a une notif pointant sur l'article, donc j'ai reproduit le bug.

Plus intéréssant encore, si `admin` remet un commentaire, `staff` se re-mange une notif (j'ai fait disparaître la notif précédente). Ça veut dire que `staff` est "abonné" à tord à l'article.

Soit les `ArticleRead` et `TutorialRead` ont un champ supplémentaire pour faire la différence entre les deux comportement, soit il y a un truc que j'ai pas compris. Un fix bête et méchant serait de ne créer de `ContentRead` que si il y a un commentaire effectivement écrit par l'auteur dans le fil, mais ça allonge clairement le temps par l'ajout d'une requête par `*Read` par commentaire (=beaucoup)

**Comment by pierre-24** [comment]
(oups, erreur de manip)

**Comment by DevHugo** [comment]
C'est pas problématique que ça soit beaucoups plus long, si c'est uniquement pendant la migration. Que la commande s'éxécute en 12 ou en 16 minutes, on s'en fout.

**Comment by pierre-24** [comment]
Tout à fait d'accord, mais si il y a moyen de faire plus propre et plus vite, je prend quand même :)

(je vais regarder à ça quand j'aurai un peu de temps, mais j'ai plein de truc à faire en même temps)

**Comment by artragis** [comment]
Le problème c'est que mon filtre est assez clair : je crée un 
ContentRead uniquement s'il en existe déjà dans la bdd (donc s'il y a 
abonnement).

Je ne comprends pas ce qu'il se passe.

**Comment by pierre-24** [comment]
Ben j'ai l'impression que dans l'ancien système, les `*Read` sont créés dès que tu visites les articles/tutos et qu'il doit y avoir une condition quelque part pour vérifier qu'il y a écriture. Maintenant, je dis ça sans avoir relu le code correspondant, donc c'est peut-être autrement que ça se passe.

**Comment by pierre-24** [comment]
Bon. J'ai QA le dernier commit d'artragis en date, et on dirais que ça fonctionne, en tout cas sur le scénario que j'ai décris plus haut :)
