### ISSUE TITLE
On a une 403 quand on dépublie

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#244]
- Créer un article/tuto avec `user`. Le publier
- Tenter de le dépublier avec admin (il est important que l'admin ne soit pas auteur)
- Recevoir une erreur 403

**Comment by artragis** [comment]
Le tutoriel en question est-il un tutoriel nouvellement créé ou un ancien tutoriel migré?

**Comment by pierre-24** [comment]
C'est du migré.

**Comment by artragis** [comment]
Car perso, je serai bien tenté de dire que les articles migrés ne seront pas dépubliables à cause de : 

``` python
            # publish the article !
            published = publish_content(exported, exported.load_version(exported.sha_draft), False)
            exported.pubdate = current.pubdate
            exported.update_date = datetime.now()
            exported.sha_public = exported.sha_draft
            exported.public_version = published
            exported.save()
```

J'ai corrigé cette erreur, mais je ne suis sûr de rien

**Comment by artragis** [comment]
Par contre : j'ai un peu de mal avec la nécessité de faire un 301 sur les articles : j'ai l'impression que les 400 sont là à cause de ça. On a des double PublishedContent qui servent à rien. 
Ce n'est qu'une hypothèse.

**Comment by pierre-24** [comment]
Non, comme je l'ai dit sur l'issue correspondante, le bug n'est à mon avis pas du à ça. Et le SEO oblige de toute façon a avoir ce doublet.

**Comment by pierre-24** [comment]
(et il est utile pour débuger, d'ailleurs, puisque tu prend l'adresse de prod et tu rajoute le `beta` dans l'adresse, c'est comme ça que j'ai fait)

**Comment by artragis** [comment]
Bon, en tout cas je pense que c'était bien les problèmes de sha qui généraient la 403 dans la dépublication.

**Comment by pierre-24** [comment]
ah, ça, par contre, c'est possible.

**Comment by artragis** [comment]
casse tête de merde : 

on ne peut pas utiliser current.sha_public pour les articles puisqu'on en a changé la structure !

**Comment by artragis** [comment]
ça devrait être réglé

**Comment by pierre-24** [comment]
Rapport de QA: non ^^ (j'ai migré un article publié et j'ai tenté de le dépublier)

Ça serait pas simplement une erreur dans les vues ?

**Comment by artragis** [comment]
Je pète un plomb là dessus.
Façon j'ai cassé travis à cause de ça il me semble.

**Comment by artragis** [comment]
tu l'as fait où la QA, en local? tu as pu lancer le debugger?

**Comment by pierre-24** [comment]
J'ai fait la QA en local, j'ai aucun droit sur la bêta :)

**Comment by artragis** [comment]
Tu peux réessayer juste au cas où tu aurais tenté avant que je fasse le push puisque je l'ai fait assez tard?

Si ça ne marche toujours pas, peux-tu lancer ton débugger stp pour me dire où le  PermissionDenied est lancé?

**Comment by pierre-24** [comment]
La 403 qu'on ce mange, [c'est celle là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_validations.py#L468). Pour une raison qui tient à la condition 4 lignes plus haut: on cherche un objet validation dont le `sha_public` n'est pas le bon, puisque la migration rajoute un commit.

Deux solutions : 
- On crée un objet validation supplémentaire et pour éviter les ennuis, on met le bot comme validateur
- On édite systématiquement le dernier objet validation en date pour changer le `sha_public`

La première solution me semble relativement plus propre (on a une trace du passage de la ZEP-12 au cas ou), mais ce n'est que mon avis.

**Comment by artragis** [comment]
Tu peux réessayer juste au cas où tu aurais tenté avant que je fasse le push puisque je l'ai fait assez tard?

Si ça ne marche toujours pas, peux-tu lancer ton débugger stp pour me dire où le  PermissionDenied est lancé?

**Comment by pierre-24** [comment]
Pourquoi tu reposte le même message alors que j'y ai répondu ? :)

**Comment by artragis** [comment]
misclick, dsl

2015-08-19 10:24 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by artragis** [comment]
BOn c'est corrigé.
