### ISSUE TITLE
La recherche ne fonctionne pas sur la beta

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#246]
Tenter de rechercher un tutoriel comme [Une introduction à Ruby](https://beta.zestedesavoir.com/tutoriels/473/une-introduction-a-ruby/) et vérifier que ça ne marche pas

**Comment by artragis** [comment]
normal on n'a pas pu indexer :p

**Comment by artragis** [comment]
Je ferme, l'issue est trop généraliste et causée par un problème d'indexation au départ.
