### ISSUE TITLE
Plus grand, le champ !

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#247]
Dans [l'article sur les satellites](https://beta.zestedesavoir.com/articles/88/et-si-des-etudiants-creaient-des-nanosatellites/) d'@artragis, les titres sont employés comme question. Du coup, à l'indexation, le titre `Le projet nanosatellite est un projet extrêmement ambitieux, vous pourriez nous donner quelques chiffres pour qu’on se représente?` est trop grand pour être indexé (MySQL râle avec `Warning: Data truncated for column 'title' at row 1`).

Ping @DevHugo :)

**Comment by artragis** [comment]
La joie des données réelles.

**Comment by artragis** [comment]
résolut par @DevHugo, je ferme.
