### ISSUE TITLE
Erreur 400 sur les articles de la bêta

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#248]
On a une 400 sur https://beta.zestedesavoir.com/articles/, mais pas sur https://beta.zestedesavoir.com/articles/?tag=cds, par exemple. Donc il y a un (ou plusieurs) article(s) fautif(s)

**Comment by pierre-24** [comment]
Note: ce qui donne une 400:
- https://beta.zestedesavoir.com/articles/?tag=android
- https://beta.zestedesavoir.com/articles/?tag=Ordinateur
- https://beta.zestedesavoir.com/articles/?tag=maths
- https://beta.zestedesavoir.com/articles/?tag=pedagogie
- https://beta.zestedesavoir.com/articles/?tag=interview
- https://beta.zestedesavoir.com/articles/?tag=zds

Il y a donc probablement plusieurs articles fautifs.

**Comment by pierre-24** [comment]
(et comme la PA plante aussi, un des articles est situé en PA, mais j'arrive plus à me souvenir de qui étaient les articles en PA)

**Comment by pierre-24** [comment]
[Cet article](https://beta.zestedesavoir.com/articles/5/les-nombres-flottants-logarithmiques/) possède une erreur 400 en bêta ([voir ici sur la prod](https://zestedesavoir.com/articles/37/les-nombres-flottants-logarithmiques/)). C'est probablement pas le seul, mais c'est un début.

**Comment by DevHugo** [comment]
Y'a deux soucis identifié, les miniatures sont mal importées et dans ma table publishedContent, j'ai deux lignes après la migration: 

`INSERT INTO `tutorialv2_publishedcontent` (`id`, `content_type`, `content_public_slug`, `content_pk`, `publication_date`, `sha_public`, `content_id`, `must_redirect`) VALUES
(1, 'ARTICLE', 'les-nombres-flottants-logarithmiques', 1, NULL, NULL, 1, 1),
(2, 'ARTICLE', 'les-nombres-flottants-logarithmiques', 1, '2015-08-17 12:53:08', '7ce57c95da003148a002d674bc09aa7465445e83', 1, 0);`

**Comment by DevHugo** [comment]
[Cette ligne la](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorialv2/includes/content_item_type_article.part.html#L30) fait bugger la page d'accueil.

**Comment by pierre-24** [comment]
Qu'il y aie deux ligne, c'est normal. La première correspond à "l'ancien article" est est en `must_redirect=True`, simplement pour le SEO (on se choppe une 301). La deuxième est le "vrai" article publié.

Par  contre, tu tiens probablement un truc avec les miniatures.

**Comment by pierre-24** [comment]
Peut-être lié à ça : https://github.com/zestedesavoir/zds-site/issues/2668

**Comment by DevHugo** [comment]
Ok, pour les deux lignes dans la table PublishedContent mais pour la première ligne dans cette table, j'ai deux NULL un sur la colonne sha_public et l'autre sur publication_time.

**Comment by pierre-24** [comment]
> j'ai deux NULL un sur la colonne sha_public et l'autre sur publication_time

[effectivement, ces champs ne sont pas rempli pour les articles](j'ai deux NULL un sur la colonne sha_public et l'autre sur publication_time). Est ce que ça jouerait ?

**Comment by pierre-24** [comment]
(mais artragis a corrigé via  #244 )

**Comment by artragis** [comment]
il faudra retenter une migration ce soir.

**Comment by pierre-24** [comment]
Ping @sandhose :)

**Comment by pierre-24** [comment]
M'enfin pour être sur, on mettrait pas un `try/except` du coté des miniatures ?

**Comment by DevHugo** [comment]
Si je résume, pendant la migration, il tente d'enregistrer l'image dans le dossier, `/media/articles/None/` ce qui donne `/media/articles/None/5338f3c9-80ed-4858-acc8-d7554826466b.jpg.60x60_q85_crop.jpg` comme adresse d'image alors que l'image devrait être dans le dossier de la galerie.

**Comment by DevHugo** [comment]
C'est à cause du bug que tu as cité avant. Avant la zep-12, quand tu ajoute une image directement, il est copié dans None.

**Comment by artragis** [comment]
à cause de quel bug? on en a cité tellement :p

Le 17 août 2015 14:31, Hugo Courtecuisse notifications@github.com a écrit
:

**Comment by DevHugo** [comment]
https://github.com/zestedesavoir/zds-site/issues/2668

**Comment by pierre-24** [comment]
Bref, un `try` et on est tranquille, non ?

**Comment by artragis** [comment]
A court terme, oui.

2015-08-17 16:24 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by pierre-24** [comment]
Mais de toute façon, ce script n'est sencé servir qu'une fois. Après, on est post-ZEP-12 avec gallerie et tout. Basta :p

**Comment by artragis** [comment]
en effet.

2015-08-17 16:27 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by pierre-24** [comment]
Parce que sérieusement, le but est de migrer avec le moins de _side-effets_

**Comment by artragis** [comment]
en effet.

2015-08-17 16:34 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by artragis** [comment]
http://cdn.ridikulum.com/images/comments/b36a368315d2bea6dce818e21ac46c97a7ccd8fc.gif

**Comment by DevHugo** [comment]
On c'était engagé la dessus, on va pas laisser ça comme ça, un peu de motivation :palm_tree: .

**Comment by DevHugo** [comment]
Allez, je le fait si vous voulez, c'est prêt avant ce soir, minuit.

**Comment by pierre-24** [comment]
ça c'est de la motivation :) :+1:

**Comment by DevHugo** [comment]
Bonne nouvelle, j'ai reussi.

**Comment by DevHugo** [comment]
Mauvaise nouvelle, y'a un autre problème. La date de publication n'est pas bonne.

**Comment by artragis** [comment]
détail, quand tu nous tiens.

**Comment by pierre-24** [comment]
Ouais, c'est une ligne aussi, non ?

**Comment by DevHugo** [comment]
Corrigé avec l'autre PR.

**Comment by artragis** [comment]
Bon bah j'ai le malheur de vous annoncer que ça ne marche pas.

Par contre c'est bel et bien un problème avec la thumbnail.

**Comment by DevHugo** [comment]
Je l'ai plus en local moi ! vous l'avez vous en local ?

**Comment by artragis** [comment]
non uniquement sur le serveur et je sais pas pourquoi ça fait ça.

**Comment by DevHugo** [comment]
C'est drôle, y'en a qui marchais pas avant et qui marche maintenant.

Exemple: [Cet article](https://beta.zestedesavoir.com/articles/5/les-nombres-flottants-logarithmiques/)

**Comment by DevHugo** [comment]
Par déduction, les tags ne fonctionnant pas en beta sont:
- https://beta.zestedesavoir.com/articles/?tag=android
- https://beta.zestedesavoir.com/articles/?tag=maths
- https://beta.zestedesavoir.com/articles/?tag=pedagogie
- https://beta.zestedesavoir.com/articles/?tag=interview
- https://beta.zestedesavoir.com/articles/?tag=zds

Un contenu qui marche pas: 
- https://beta.zestedesavoir.com/articles/4/lisibilite-dun-code-source/

**Comment by DevHugo** [comment]
Comment ça marchait les articles avant avec les galleries ? je comprend plus rien !

Je pense que c'est toujours à cause des miniatures mais que j'avais pas résolu le probléme avant !

**Comment by pierre-24** [comment]
Ben faudrait regarder la BDD voir comment les chemins des miniatures sont. T'as peut être inversé la tendance : ce qui marchait pas fonctionne et ce qui fonctionnait ne fonctionne plus. Non ?

**Comment by pierre-24** [comment]
Je "confirme" ma théorie: on a [ici](https://beta.zestedesavoir.com/oldarticles/) tout les anciens articles. Or si on prend l'article "essai" (https://beta.zestedesavoir.com/oldarticles/212/essai/), on vois que son pendant ZEP-12 plante (https://beta.zestedesavoir.com/articles/142/essai/). Or sa miniature est stocké à un endroit "classique" :https://beta.zestedesavoir.com/media/articles/212/f4410606-10f4-4891-aacf-e94ad962c700.png.60x60_q85_crop.jpg ... Donc il "suffit" de modifier un peu le code pour gérer les deux cas.

C'est d'ailleurs cet article qui fait planter la PA.

Pareil sur l'article des médailles fields (https://beta.zestedesavoir.com/articles/27/medailles-fields-2014/) et ceux qui suivent et qui ont des miniatures "normales" sur la liste des articles . Alors que pour les autres, à priori, c'est ok.

Comme je disais plus haut, c'est bien pratique pour débuguer, cette histoire de renvoyer des 301 :)

**Comment by DevHugo** [comment]
Ça avance, on a plus de 400 par-contre toutes les miniatures n'ont pas été migré =(.

Le contenu des deux tables article et gallery_image:
- http://sprunge.us/jTSb 
- http://sprunge.us/dDjJ

PS: J'ai une intuition sur le [try/catch/else](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/management/commands/migrate_to_zep12.py#L222)

**Comment by pierre-24** [comment]
> Ça avance, on a plus de 400 par-contre toutes les miniatures n'ont pas été migré =(.

Faux. En fait, si tu regarde [la liste originale](https://beta.zestedesavoir.com/oldarticles/), t'as énormément de case blanche, qu'on peut rapprocher au fait que la miniature des articles sur la préprod' n'existe pas (en fait, elle n'ont pas été migrées). Du coup, les articles qui doivent avoir des miniatures ont des miniatures, les articles qui ne doivent pas (=case blanche) n'en ont effectivement pas (= case grise).

De toute façon, en prod, on aura pas ces problèmes, puisque tout les articles ont effectivement une miniature et qu'il semblerait que tu aie finalement trouvé la bonne recette.

Problème réglé ?

**Comment by artragis** [comment]
+1.

Juste pour enlever le doute que tu as eu tout à l'heure @DevHugo : les galleries n'ont pas à être migrées.

En effet, nous utilisons les mêmes galleries dans le cas des tutoriels. Quant aux articles, nous en créons une nouvelle car dans l'ancienne version les articles n'avaient pas de gallerie. Mais c'est tout. Tout va bien de ce côté là.

**Comment by pierre-24** [comment]
Et d'un problème chiant de réglé. @DevHugo , t'as donc gagné une bière :)
