### ISSUE TITLE
Gestion de la desinscription du membre

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#25]
Pour être iso fonctionnel avec ce qu'il se fait aujourd'hui : 

> Les données du membre sont anonymisées :
> 
> ```
> le pseudo anonymous est employé :
>         pour les sujets du forum (qui, cependant, restent ouverts)
>         pour les messages des MP (le membre quitte les discussions auxquelles il participait) ;
>         pour les commentaires aux tutoriels et articles ;
> 
> les galeries non liées à un tutoriel sont données à external (puisque l’image peut être considérée comme venant d’un “auteur”) avec droit de lecture et d’écriture ;
> 
> les articles et tutoriels suivent ces règles :
>     si le tutoriel/article a été écrit par plusieurs personnes : le membre est retiré de la liste des auteurs ;
>     si le tutoriel/article est publié, il passe sur le compte “external”. Une demande expresse sera nécessaire au retrait complet de ces contenus ;
>     si le tutoriel/article n’est pas publié (brouillon, bêta, validation) il est supprimé, ainsi que la galerie qui lui est associée.
> ```

Vérifier qu'on est _iso_ avec la liste ci-dessus.

Il est également nécessaire de réécrire le T.U:
- [ ] supprimer les doubles tests (puisque article=tuto), 
- [x] vérifier ce qu'il arrive au topic de la bêta (pas testé actuellement), 
- [x] vérifier que les `PublishedContent` sont conservés/supprimé selon les cas, 
- [x] vérifier ce qu'il arrive aux galeries des contenus (normalement déjà testé)

**Comment by pierre-24** [comment]
J'ai l'impression, mais je peux me tromper, que ça va revenir à enlever du code redondant plus qu'autre chose (puisqu'il était logiquement dupliqué)

**Comment by artragis** [comment]
tu as tout compris. Et surtout cela va fortement simplifier la vue membre.

**Comment by pierre-24** [comment]
Bon, #112 est passé par là. C'est pas encore parfait (voir ci-dessus), mais c'est un début :)

**Comment by artragis** [comment]
juste une chose, pourquoi rien n'est coché ici?

**Comment by pierre-24** [comment]
Parce que j'ai taillé dans le test existant plus que je ne l'ai réécris (de manière à ce qu'il fonctionne), donc que je suis pas sur que les points de la liste soit réellement testé ou pas :)

**Comment by artragis** [comment]
Ok, là on est simplement dans du need test et du need QA?

**Comment by pierre-24** [comment]
C'est ça ;)

**Comment by Vayel** [comment]
Je me suis inscrit (qa25) mais n'ai pas reçu de mail de confirmation.

**Comment by artragis** [comment]
pas sûr que mon serveur ait activé les mails tiens. je suis sur un 
serveur de test vois-tu. Je vais voir dans l'admin si je peux t'activer 
manuellement.

**Comment by pierre-24** [comment]
... D'autant que par défaut, les mails sont renvoyés vers la sortie standard et pas vers un serveur mail, ce qui est pratique en local mais moins sur un serveur de test. Mais sinon, oui, tu peux l'activer à la main :)

(d'ailleurs, c'est fait. D'ailleurs, pour cette raison, évite quand même d'employer ta "vraie" adresse e-mail, au cas ou, puisque c'est pas envoyé, met n'importe quoi tant que ça a la forme d'une adresse e-mail)

**Comment by Vayel** [comment]
Parfait, merci. ^^

**Comment by Vayel** [comment]
J'ai créé des trucs mais j'ignore s'il faut que vous regardiez quelque chose avant qu'on supprime le compte "qa25".

[Galerie indépendante](http://zds.francoisdambrine.me/galerie/77/qa25/)
[Galerie contenu non publié et avec qa25 pour seul auteur](http://zds.francoisdambrine.me/galerie/80/qa25-solo-delete/)
[Galerie contenu non publié et avec qa25 et admin pour auteurs](http://zds.francoisdambrine.me/galerie/81/qa25-multi-delete/)
[Galerie contenu publié et avec qa25 pour seul auteur](http://zds.francoisdambrine.me/galerie/79/qa25-solo/)
[Galerie contenu publié et avec qa25 et admin pour auteurs](http://zds.francoisdambrine.me/galerie/78/qa25-multi-users/)
[Contenu publié avec pour auteurs qa25 et admin](http://zds.francoisdambrine.me/tutoriels2/72/qa25-multi-users/)
[Contenu publié avec pour seul auteur qa25](http://zds.francoisdambrine.me/articles2/73/qa25-solo/)
[Contenu non publié avec pour seul auteur qa25](http://zds.francoisdambrine.me/contenus/74/qa25-solo-delete/)
[Contenu non publié avec pour auteurs qa25 et admin](http://zds.francoisdambrine.me/contenus/75/qa25-multi-delete/)
[Commentaire contenu](http://zds.francoisdambrine.me/tutoriels2/66/pa/#p56)
[Sujet créé par qa25 et avec un seul message](http://zds.francoisdambrine.me/forums/sujet/13/qa25-solo/)
[Sujet créé par qa25 et avec une réponse de admin](http://zds.francoisdambrine.me/forums/sujet/11/qa25/)
[Sujet créé par admin et avec une réponse de qa25](http://zds.francoisdambrine.me/forums/sujet/12/qa25-_/)
[MP avec qa25 + admin](http://zds.francoisdambrine.me/mp/78/qa25/messages/)
[MP avec qa25 + admin + staff](http://zds.francoisdambrine.me/mp/79/qa25-multi-users/messages/)

Au fait, les identifiants sont : 
qa25
qa25mdp

**Comment by pierre-24** [comment]
Étant un peu parano envers mon propre code, je te propose également de mettre une image dans chaque gallerie et de vérifier son devenir :)

**Comment by Vayel** [comment]
Done. J'avais oublié de lister les deux conversations par MP.

Je ne sais pas par contre qui est "external".

**Comment by pierre-24** [comment]
Il y a deux comptes qui récupèrent les données des gens qui sont désinscrits, théoriquement: "external", c'est "Auteur externe" sur ZdS (récupère galleries et contenus), et "anonymous", c'est "anonyme" sur ZdS (donc l'anoymisation des messages). ([voir la doc](http://zds-site.readthedocs.org/fr/latest/back-end/member.html#desinscription)). 

Dans tout les cas, ces deux comptes n'ont pas le droit d'être inclus dans des MPs ou d'être auteurs de contenus.

Subtilité, aucun de ces deux comptes ne correspont au _bot account_, qui est Clem' sur ZdS et "admin" en développement (ce qui n'est pas très intelligent, mais on fait avec).

**Comment by Vayel** [comment]
Comment je sais qu'une galerie (non attachée à un contenu) est devenue la propriété d'external ?

**Comment by artragis** [comment]
d'ailleurs j'ai explicitement demandé de ne pas utiliser de vraie 
adresse sur ce serveur.

**Comment by artragis** [comment]
l'account est sur external/external il me semble.

**Comment by pierre-24** [comment]
> Comment je sais qu'une galerie (non attachée à un contenu) est devenue la propriété d'external ?$

Les identifiants de external sont dans la doc :)

Grillé par artragis

**Comment by Vayel** [comment]
Tout est ok, sauf pour : 
- Galerie indépendante
- Galerie contenu non publié et avec qa25 pour seul auteur
- Galerie contenu publié et avec qa25 pour seul auteur

Que je n'ai pas pu vérifier vu que external/external est invalide.

**Comment by pierre-24** [comment]
Maintenant il est valide :)

**Comment by Vayel** [comment]
Du coup c'est bon la QA ici. ^^

**Comment by pierre-24** [comment]
Nickel, plus qu'a TU :)

**Comment by artragis** [comment]
J'écris les TU le plus rapidement possible.

**Comment by pierre-24** [comment]
Tu m'as l'air motivé, de ces temps-ci :)

**Comment by artragis** [comment]
Faut bien que ça se fasse.

**Comment by Eskimon** [comment]
@Vayel tu confirmes tout les points dans la liste du premier post ? @pierre-24 tu pourras mettre a jour la liste quand ce sera confirme ?

**Comment by pierre-24** [comment]
Pour les points du bas, il s'agit de point à vérifier/implémenter dans les tests.

**Comment by artragis** [comment]
Voilà.
Par contre jen e suis pas d'accord pour supprimer les doublons.

**Comment by pierre-24** [comment]
Comme tu le sens, en fait. Je me basais sur le fait que article=mini-tuto, mais peu importe.

**Comment by artragis** [comment]
non puisqu'on change un paramètre et qu'à haut niveau d'abstraction article != tuto.

**Comment by pierre-24** [comment]
Accepté ;)
