### ISSUE TITLE
Impossible de déplacer un chapitre au même niveau qu'une partie

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#253]
Serveur : Bêta
Version : test_zep12/884f3ad
Système : OS X
Navigateur : Chrome

---

Scénario :
- Créez un tutoriel avec une seule partie, des chapitres et des extraits dans ces chapitres.
- Cliquez sur "Déplacer" pour le premier chapitre.
- Tentez de le déplacer avant la partie, **vous obtiendrez une 404**.
- Tentez de le déplacer après la partie, **vous obtiendrez l'erreur suivante :**

``` console
GitCommandError at /contenus/deplacer/
'git mv --dry-run 323_fragmenter-vos-projets/1795_fragment fragment' returned with exit code 128
stderr: 'fatal: bad source, source=323_fragmenter-vos-projets/1795_fragment, destination=fragment/1795_fragment'
```

**Comment by pierre-24** [comment]
Provient de ce qui est décrit dans #255
