### ISSUE TITLE
Markdown non généré au déplacement d'un chapitre

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#255]
Serveur : Bêta
Version : test_zep12/884f3ad
Système : OS X
Navigateur : Chrome

---

Scénario :
- Dans un tutoriel avec au moins une partie, deux chapitres et des extraits dans ces chapitres, cliquez sur "Déplacer" sur le premier chapitre.
- Sélectionnez "Descendre" et constatez que le chapitre se trouve en seconde place mais que ses extraits affichent le message suivant :

``` console
Une erreur est survenue dans la génération de texte Markdown. Veuillez rapporter le bug.
```

**Comment by pierre-24** [comment]
Ok, j'ai compris ce qui c'est passé ici: tu as d'abord tenté de "remonter" un machin nommé "Fragments" vers le dessus pour en faire une partie. Le problème, c'est que pour une raison ou une autre, ça ne c'est pas fait. Depuis, c'est un peu l'horreur parce que ton manifest ne correspond plus à la réalité. D'ou tout les bugs qui ont suivis.

**Comment by GerardPaligot** [comment]
Ah sorry, j'ai tenté d'isoler au plus possible mes scénarios.

**Comment by pierre-24** [comment]
ok, effectivement, c'est bien là qu'est le problème. Pour @artragis : 
1. Créer un big-tuto v1 avec une partie contenant un chapitre contenant un extrait ; 
2. Le migrer ;
3. Tenter de déplacer le chapitre "avant" la partie (donc remonter la partie, je pense que Andr0 avait pour idée de transformer son big- en moyen-tuto), on a alors une erreur de "The specified tree is invalid."

Le déplacement est à moitié effectif: le dossier est bien déplacé, le manifest correct, mais le commit non fait (bref, comme d'habitude). Puis ensuite, Andr0 est remonté sur ces erreurs, donc son dossier est mort. C'est donc plus un bug mystique, en ce qui concerne celui là.

@GerardPaligot : t'inquiète pas, de toute façon c'est la bêta, ton tuto sera comme neuf la prochaine fois qu'on re-migrera :)

**Comment by pierre-24** [comment]
(ah, oui, et ça fonctionne bien sur un tuto V2 créé à partir de l'interface V2)

**Comment by pierre-24** [comment]
Et ça marche aussi quand on déplace un chapite d'une partie à une autre, erreur de tree, et dossier bousillé :p

**Comment by pierre-24** [comment]
Bon, le "the specified tree is invalid", c'est bien entendu [celui de cette ligne](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_contents.py#L1603). Or quand on le commente, on remarque que l'erreur provient, dans le cas du déplacement que j'ai décrit plus haut, [de cette ligne là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/models/models_versioned.py#L689). Autrement dit, le slug n'existe plus dans la liste de slug. Et effectivement, dans la liste de slug, celui-ci à déjà perdu le préfixe `xx_` (ou `xx` représente le slug). C'est donc bien un problème avec ancien/nouveau slugs.

**Comment by pierre-24** [comment]
Et le responsable de ce bordel, c'est le `True` a la fin de [cette ligne](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/models/models_versioned.py#L1259) ... Non ?

(c'pas pour autant qu'il faut le virer, que du contraire)

**Comment by artragis** [comment]
si tu enlèves le True, tu auras des problèmes plus tard quand des parties
ou extraits avec le même slugs se retrouveront dans la même partie. Imagine
toi "TP 1" comme titre donne "tp-1" comme slug et si on déplace le truc
dans une autre partie qui a tp-1 bah ça marchera pas.

2015-08-19 8:54 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by artragis** [comment]
Néanmoins il est possible que la gestion du renommage soit mauvaise, je le
conçois.

**Comment by pierre-24** [comment]
C'eswt pour ça que j'avais édité en disant "(c'pas pour autant qu'il faut le virer, que du contraire)" :)

Je dis juste que le bug ce situe probablement par là quelque part.

**Comment by artragis** [comment]
Je vois pas les édit sur gmail :p

Je regarderai ce midi.

**Comment by artragis** [comment]
C'est bon.
