### ISSUE TITLE
Impossible de déplacer un extrait dans un autre chapitre

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#256]
Serveur : Bêta
Version : test_zep12/884f3ad
Système : OS X
Navigateur : Chrome

---

Scénario :
- Dans un tutoriel avec au moins une partie, deux chapitres et des extraits dans ces chapitres, cliquez sur "Déplacer" sur le premier extrait.
- Sélectionnez un déplacement avant un extrait d'un autre chapitre et constatez l'erreur suivante :

``` console
GitCommandError at /contenus/deplacer/
'git mv 323_fragmenter-vos-projets/1805_listfragment/5951_utilisation-simple-des-listes.md 323_fragmenter-vos-projets/1795_fragment/utilisation-simple-des-listes.md' returned with exit code 128
stderr: 'fatal: renaming '323_fragmenter-vos-projets/1805_listfragment/5951_utilisation-simple-des-listes.md' failed: No such file or directory'
```

Edit :
- Quand vous tentez de faire la même chose mais en déplacent avant, vous obtenez une erreur 404.
- Aucune erreur lorsque vous déplacez dans le même chapitre.

**Comment by pierre-24** [comment]
Provient de ce que j'ai expliqué dans #255 !
