### ISSUE TITLE
Impossible de déplacer une partie dans un chapitre

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#257]
> **Attention :** Je ne dis pas que ce qui suit devrait être possible. Simplement que rien ne m'y empêche et donc, que j'obtiens une erreur.

Serveur : Bêta
Version : test_zep12/884f3ad
Système : OS X
Navigateur : Chrome

---

Scénario :
- Dans un tutoriel avec au moins deux partie, des chapitres et des extraits dans ces chapitres, cliquez sur "Déplacer" sur une partie.
- Sélectionnez un déplacement avant/après un extrait d'un autre chapitre et constatez l'erreur suivante :

``` console
GitCommandError at /contenus/deplacer/
'git mv --dry-run 230_les-services-du-google-play 228_experience-utilisateur/les-services-du-google-play' returned with exit code 128
stderr: 'fatal: bad source, source=230_les-services-du-google-play/1391_installation/conclusion.md, destination=228_experience-utilisateur/les-services-du-google-play/1391_installation/conclusion.md'
```

**Comment by pierre-24** [comment]
On pense avoir un problème avec le déplacement de manière générale ^^

**Comment by GerardPaligot** [comment]
Content de le découvrir maintenant alors. A titre personnel, le déplacement est la fonctionnalité que je vais le plus utiliser dès la release de cette ZEP. :)

**Comment by pierre-24** [comment]
Ton tutoriel est bizarre. Il indique qu'une partie s'appelle "Fragments", mais cette partie n'existe pas dans les fichiers.

**Comment by pierre-24** [comment]
Dans quel tuto sont situés ces parties ? (j'ai besoin du slug). Et théoriquement, c'est un déplacement qui devrait être interdit, donc bug effectivement.

**Comment by GerardPaligot** [comment]
C'est un big tuto que je n'ai pas publié. Je t'aurais bien donné l'archive mais zeste de savoir est down.

**Comment by pierre-24** [comment]
Peu importe, le slug me suffit, j'ai un accès en lecture à la bêta :)

**Comment by artragis** [comment]
@GerardPaligot : en fait c'est un bug qui n'arrive qu'avec les tutos migrés. Il n'est pas normal mais il est là.

On essaie de comprendre ce qui génère l'erreur mais là c'est mystique.

**Comment by GerardPaligot** [comment]
@pierre-24 Le tuto avec tout plein de parties, c'est [celui-ci alors](http://beta.zestedesavoir.com/contenus/426/aller-plus-loin-dans-le-developpement-android/).

@artragis Malheureusement, les tutos migrés seront l'objet du module pendant plusieurs mois à la release de la ZEP.

**Comment by artragis** [comment]
> Malheureusement, les tutos migrés seront l'objet du module pendant
> plusieurs mois à la release de la ZEP.

Oui, nous savons et c'est pour ça qu'on essaie de débugger le tout. Mais
actuellement nous avons des problèmes pour reproduire le bug en local,
c'est là notre problème.

**Comment by pierre-24** [comment]
Pas si mystique que ça (voir #255 )

**Comment by artragis** [comment]
corrigé.
