### ISSUE TITLE
Le tutoriel « Petit guide pour SQL Plus » ne fonctionne pas en beta

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#260]
Il est impossible de consulter le tutoriel en beta. Le lien depuis la [beta](https://beta.zestedesavoir.com/tutoriels/226/petit-guide-de-sqlplus/) et le lien depuis la [prod](https://beta.zestedesavoir.com/tutoriels/226/petit-guide-de-sqlplus/).

L'erreur étant `sha is not None and related version could not be found due to /opt/zdsenv/ZesteDeSavoir/contents-public/petit-guide-de-sqlplus`

**Comment by DevHugo** [comment]
Je précise juste que le tutoriel marche bien quand on importe l'archive. C'est donc la migration qui a du foiré (pour ne pas changer). 

_Petite remarque, j'importe directement depuis l'archive le dossier est nommé: `petit-guide-de-sql-plus` dans l'erreur on voit qu'il cherche un dossier appelé `petit-guide-de-sqlplus` (manque le tiret entre le SQL et le Plus). Surement ça, l'erreur ^^ !_

La stackstrace lors du index_content (http://sprunge.us/QidU).

**Comment by pierre-24** [comment]
Deux choses : 
1. Heureusement qu'on a cette commande pour déterminer les bugs
2. Ceci dit, le fait que ça apparaisse pas dans Sentry me fait un peu "peur", on mettrait pas un log quelque part ? Et on attraperait pas les erreurs pour éviter à la commande de planter systématiquement et de terminer son travail malgré tout ? (quitte à écrire quelque part "Ce machin n'as pas pu être indexé").

Au delà de ça, ça ressemble encore a un de ces problèmes de changement de slugs :/

**Comment by DevHugo** [comment]
> Ceci dit, le fait que ça apparaisse pas dans Sentry me fait un peu "peur", on mettrait pas un log quelque part ? Et on attraperait pas les erreurs pour éviter à la commande de planter systématiquement et de terminer son travail malgré tout ? (quitte à écrire quelque part "Ce machin n'as pas pu être indexé").

On pourrais rediriger facilement la sortie de la commande vers un fichiers texte, on peut faire ça avec du shell, comme ceci, « manage.py index_content >> /var/log/indexation.txt ».  Je pense qu'on peut rajouter un try/catch pour ne pas bloquer l’exécution de la méthode. Si on veut, on pourrais même dans le catch envoyer un mail à l'administrateur avec l'erreur et les logs.

On fait ça ?

**Comment by pierre-24** [comment]
- Oui pour le try/catch,
- Oui pour le logging dans un fichier
- Non pour les mails à l'admin (on va vite nous raler dessus si on recoit un mail toutes les demi-heures pour dire que le même tuto n'as pas pu être indexé :p )

Je n'oublie pas qu'on a toujours un tuto qui nous fout une erreur (je regarde à ça tantôt), je cherche juste à éviter les ennuis plus tard ;)

**Comment by DevHugo** [comment]
Maintenant, l'indexation ne s’arrête plus à la première erreur. Mais on n'a toujours ce souci avec le tutoriel.

**Comment by pierre-24** [comment]
Ben en fait,
- Créer un tuto V1 et l'appeller "Petit guide de SQL*Plus", le publier ;
- Le migrer ;
- Constater qu'effectivement, pas moyen d'y accéder en version publique.

Donc, bug qui passe de "mystique" à reproductible.

Mieux encore, il n'y a que la version publique qui coince, et j'irais même jusqu'à dire que c'est pour la même raison qu'on a eu des soucis sur les articles. 

En fait, on se plante sur quel slug assigner à qui, [là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/management/commands/migrate_to_zep12.py#L391) :)

**Comment by DevHugo** [comment]
Ça marche GG !
