### ISSUE TITLE
Les dates dans les résultats de la recherche sont incorrect

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#262]
![cool](https://cloud.githubusercontent.com/assets/6099338/9388909/8834bd9e-4768-11e5-9dfc-333d159ba4ab.png)

Le, « il y'a une heure est faux » .

**Comment by artragis** [comment]
Faut regarder dans le template quelle est la date utilisée. Mais c'set un bug mineur Houra !

**Comment by pierre-24** [comment]
Comme je disais sur IRC (mais @DevHugo a disparu), [dans `reindex_content()`](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/search/utils.py#L123), c'est un champ `pubdate` qui est rempli, mais à priori, [dans le template](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/search/includes/content/content.html#L36),  c'est un champ `pub_date` qui est utilisé. Pourquoi ?

**Comment by pierre-24** [comment]
Ok. Hugo a trouvé :)

**Comment by DevHugo** [comment]
C'était pas ça, faut ré-ouvrir.
