### ISSUE TITLE
Les dates pour les résultats de la recherche pour les extraits et les chapitres sont mauvais

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#265]
Sinon tout est bon ! ^^

https://beta.zestedesavoir.com/rechercher/?q=La+gestion+d%27un+formulaire+avec+JSF

**Comment by pierre-24** [comment]
En même temps, on dirait que ni dans [`index_extract()`](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/search/utils.py#L34) ou [`index_container`](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/search/utils.py#L49) on ne met à jour le champ `pubdate`, alors qu'ils sont bien définis dans le modèle :)

**Comment by DevHugo** [comment]
J'ai utilisé un petit tour de magie ^^. 

Dans [les modéles](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/search/models.py), le `pubdate` n'est pas définis dans SearchIndexContainer et SearchIndexExtract mais dans SearchIndexContent. 
Quand les contenus sont indexes dans Solr, dans le fichier [search_indexes.py](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/search_indexes.py#L89), je vais chercher la [pubdate](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/search_indexes.py#L89) dans l'objet SearchIndexContent.

Mais j'ai l’impression que ça marche maintenant o.O. Peut-être que le temps que la tache cron passe !

**Comment by DevHugo** [comment]
Jusqu'à preuve du contraire, ça marche donc, je ferme, on pourrais ré-ouvrir dans le cas ou on en aurait besoin.
