### ISSUE TITLE
Redirige mal l'utilisateur après un déplacement

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#266]
Serveur : Bêta
Version : test_zep12/fb381a2
Système : OS X
Navigateur : Chrome

---

Scénario :
- Dans un tutoriel avec des parties, des chapitres et des extraits, rendez-vous sur un chapitre et cliquez sur "Déplacer".
- Déplacez le chapitre dans une autre partie et constatez que vous êtes redirigé vers le chapitre destination plutôt que vers la nouvelle destination de votre chapitre.

Pour être plus claire, si vous avez un tutoriel fictif comme celui-ci :

Partie 1
Chap 1
Chap 2
Partie 2
Chap 3
Chap 4

Et que vous déplacez Chap 1 avant ou après Chap 3, vous serez redirigé sur Chap 3 et non pas sur Chap 1.

> **Attention :** Dans certain cas, il ne redirige même pas sur la partie ou le chapitre, il se contente de revenir sur la page d'accueil du tutoriel.

**Comment by artragis** [comment]
c'est volontaire car on n'a jamais pu se décider là dessus, évolution pour la suite quand on aura une vraie spec à ce propos.
