### ISSUE TITLE
Impossible de créer autre chose que des sections pour un mini tuto

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#268]
Serveur : Bêta
Version : test_zep12/fb381a2
Système : OS X
Navigateur : Chrome

---

Scénario :
- Avec un mini tutoriel v1 qui ne possède que des extraits, constatez qu'il est impossible de créer autre chose que des extraits et que le tutoriel est condamné à rester un mini tutoriel au sens v1.

> **Attention :** Je ne sais pas si ce bug est spécifique aux anciens tutoriels. Il faudrait tester la création d'un tutoriel v2 avec que des sections dedans.

**Comment by artragis** [comment]
> Avec un mini tutoriel v1 qui ne possède que des extraits, constatez qu'il est impossible de créer autre chose que des extraits et que le tutoriel est condamné à rester un mini tutoriel au sens v1

Logique, c'est voulu comme ça.

**Comment by GerardPaligot** [comment]
Ok, c'est dommage mais si c'est prévu comme ça, restons là dessus pour le moment.

**Comment by artragis** [comment]
Il faudrait juste un bouton "transformer en moyen tuto" mais c'est une évolution.
