### ISSUE TITLE
Opération pour ajouter un auteur très (trop) long

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#269]
Serveur : Bêta
Version : test_zep12/fb381a2
Système : OS X
Navigateur : Chrome

---

Scénario :
- Sur un tutoriel, ajoutez un auteur.
- Constatez que l'opération prend un temps démesuré (facilement une dizaine de seconde).

**Comment by artragis** [comment]
vérifié. Faudra que @sandhose vérifie qu'on n'a pas de slow query.

**Comment by DevHugo** [comment]
Je confirme que sur la beta, c'est super lent !

**Comment by artragis** [comment]
sur mon instance aussi. faudrait regarder.

**Comment by DevHugo** [comment]
Sur ton instance, ça prend (~2-3 secondes)

**Comment by artragis** [comment]
ce qui à l'échelle dem on instance est immense.

**Comment by DevHugo** [comment]
J'ai regardé, le code et j'ai rien trouvé de choquant. Je passe mon tour pour celle-ci.

**Comment by artragis** [comment]
y'a peut être une slow query quelque part quand on charge trop de chose 
avec des jointures.

**Comment by pierre-24** [comment]
Et on vois comment les "slow queries" ? (j'ai encore oublié ^^)

**Comment by DevHugo** [comment]
Y'a un dossier sur la beta ?

**Comment by pierre-24** [comment]
Un dossier de quoi ?

**Comment by pierre-24** [comment]
On a testé, c'est pas une _slow query_.

**Comment by pierre-24** [comment]
C'est pas nous, logiquement: il faut attend de temps pour envoyer un simple MP sur la bêta.

**Comment by pierre-24** [comment]
Bon, résultat des courses, c'est à priori pas nous :)
