### ISSUE TITLE
Publication

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#27]
Le procesus de publication n'est pas encore porté. Cf la documentation sur la manière dont il a été conçu.
- [x] publication basique
- [x] Jsfiddle : #53 
- [x] "Autres contenus" (HTML, PDF, ePub, ...) : #58

**Comment by artragis** [comment]
Je passe la tâche de bloquant à need QA car pierre a implémenté les bases de la publication.
\o/ !!

**Comment by artragis** [comment]
Juste pour que tout le monde soit au courant : 

il n'y a plus qu'un seul bug lors de la publication : le jsfiddle n'est pas pris en compte.

Pour le reste, tout est OK.

**Comment by pierre-24** [comment]
Ça et #58, évidement ;)

**Comment by pierre-24** [comment]
C'est presque bon, ici

**Comment by artragis** [comment]
il manque quoi ici?

**Comment by pierre-24** [comment]
De la QA et le fait que je dois gérer cette histoire de téléchargement d'image (sinon la génération des PDFs plante).

**Comment by artragis** [comment]
J'ai fait l'export md. même si je ne suis pas convaincu de cette idée. L'export sous forme d'archive serait bien meilleure.

**Comment by pierre-24** [comment]
?

**Comment by artragis** [comment]
bah les "extra_contents" dont celui qui est en ".md", il faut bien le faire non?

**Comment by artragis** [comment]
En fait j'ai tout cassé...

2015-05-15 14:05 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by pierre-24** [comment]
Surtout qu'il est déjà fait :o 

(c'est juste que c'est réservé aux admins)

**Comment by artragis** [comment]
Ah, je l'avais pas vu alors?

Bon bah j'essaierai de voir si je peux pas faire la fameuse archive zip d'ici peu, je pense savoir comment faire.

**Comment by pierre-24** [comment]
Yep, [c'est là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/utils.py#L380) :)

C'est la base pour faire les autres "extra-machins", parce que pandoc part de ce fichier là pour la suite. Par contre, le ZIP; c'est effectivement pas encore fait :)

**Comment by artragis** [comment]
Je m'en occupe plus tard du coup.

**Comment by pierre-24** [comment]
On est pas pressé. Je pense que je vais essayer de me pencher sur la partie image ce weekend, perso.

(["No. Try not. Do... or do not. There is no try."](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/tests/tests_views.py#L3325))

**Comment by Vayel** [comment]
Que faut-il faire pour la QA ?

**Comment by pierre-24** [comment]
Rien pour le moment. Je vais essayer de voir ce que je peux faire pour les images et je reviendrai par ici après :)

**Comment by artragis** [comment]
Tu en es où pierre?

**Comment by pierre-24** [comment]
On est "bon" :-)

Maintenant qu'on gère les images comme il se doit, on a bien les "extras content" à tout les coup, on a les redirections et on a le(s) T.U.(s), donc je pense qu'on est clairement bon sur celle-ci :)
