### ISSUE TITLE
Manifest.json dans les diffs d'un tutoriel

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#270]
Serveur : Bêta
Version : test_zep12/fb381a2
Système : OS X
Navigateur : Chrome

---

Scénario :
- Affichez les diff d'un tutoriel sur des changements de structure du tutoriel.
- Constatez que le manifest figure aussi dans les diffs alors que ce fichier devrait être un fichier interne à ZdS et non visible à l'utilisateur (jamais il ne le visualise sur le site).

**Comment by artragis** [comment]
Mouais, bof. C'est un truc pour l'auteur seulement.

**Comment by DevHugo** [comment]
C'est juste un if, en même temps, si tu veux, je le fais.

**Comment by artragis** [comment]
fais, fais. Mais les "c'est juste" sont rapidement le meilleurs moen de ne
pas sortir le produit.

Le 21 août 2015 10:58, Hugo Courtecuisse notifications@github.com a écrit
:

**Comment by DevHugo** [comment]
O.k, je comprend ton point de vue.

**Comment by artragis** [comment]
Mais si tu penses avoir le temps, fais le.

**Comment by pierre-24** [comment]
Moi je suis partagé. Effectivement, l'auteur s'en balance théoriquement. D'un autre coté, c'est la réalité, ce fichier existe et est modifié, et il est de toute façon dans l'archive que l'auteur télécharge, donc à quoi bon le "cacher" ?

**Comment by GerardPaligot** [comment]
Je ne veux pas rentrer dans le débat de devoir le faire ou non. Je veux juste donner mon avis s'il faut afficher où non des fichiers comme le manifest.

Pour moi la réponse est non. Non parce qu'il faut se poser la question : "A quel type d'utilisateur est destiné ma fonctionnalité ?". A cette question, nous connaissons tous la réponse : les auteurs. Les auteurs sont des personnes qui n'ont pas forcément des connaissances techniques en informatique et qui préfère des fonctionnalités ergonomiques plutôt que de bidouiller les choses par eux-même.

Dans cette optique de rendre une fonctionnalité ergonomique, même si le fichier est une réalité, il est plus souhaitable de le cacher à l'auteur pour éviter de l'embrouiller avec un fichier dont il n'a pas connaissance et qu'il n'a jamais vu parce qu'il aura très probablement écrit son site de bout en bout sur le site web.

Après, relativisons : nous parlons d'**un** fichier présent dans des diffs **spécifiques**. Si vous ne mettez pas en oeuvre ma proposition, je ne vais pas en mourir. :)

**Comment by pierre-24** [comment]
Je me range à ton argumentaire. Puis la PR #278  le fait, alors allons-y :)

**Comment by DevHugo** [comment]
Du coup, on ferme, vu que la PR est passé ?

**Comment by pierre-24** [comment]
C'est ça :)
