### ISSUE TITLE
La licence des anciens tutoriels est modifiée

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#271]
> **Attention :** Je considère cette issue comme bloquante car elle touche des points juridiques.

Serveur : Bêta
Version : test_zep12/fb381a2
Système : OS X
Navigateur : Chrome

---

Scénario :
- Rendez-vous sur un tutoriel v1 avec une licence différente de "Tous droits réservés".
- Constatez que la licence a été modifié pour "Tous droits réservés".

**Comment by artragis** [comment]
en effet, la migration a foiré à ce propos.

**Comment by GerardPaligot** [comment]
Le bug ne semble pas toucher les articles.

**Comment by artragis** [comment]
En effet, je l'ai corrigé sur ma copie locale (assez facilement). Le fix
sera pushé ce midi.

2015-08-21 11:07 GMT+02:00 Gérard Paligot notifications@github.com:

**Comment by artragis** [comment]
corrigé. Cela apparaîtra au prochain pull de sandhose.
