### ISSUE TITLE
Question sur la suppression d'un contenu

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#273]
J'aurais une question sur la suppression d'un contenu. Je tente de supprimer un contenu publié en bidouillant un peu les choses.

Quand je récupère l'URL depuis le site pour supprimer un contenu, j'obtiens celle-ci : `http://beta.zestedesavoir.com/contenus/655/test-12/#delete-content`.

Or, d'après vos routes et vos vues, non seulement vous ne traité jamais `#delete-content` mais vous n'avez aucune route qui y ressemble. Par contre, vous avez des routes "supprimer/..." qui ne semblent pas utiliser.

Quelqu'un pour m'expliquer ce que j'ai loupé ?

**Comment by artragis** [comment]
@pierre-24

**Comment by pierre-24** [comment]
Quand tu emplois l'url `http://beta.zestedesavoir.com/contenus/655/test-12/#delete-content`, tu appelles la modale qui te demande si tu veux effectivement bien supprimer ton tuto, modale qui contient un formulaire qui pointe bien vers le bon truc.

Preuve en image:

![screenshot from 2015-08-21 16 25 49](https://cloud.githubusercontent.com/assets/7889675/9410575/4dcd2358-4821-11e5-936c-cebba79f3f23.png)

(champ `action=` dans la ligne en bleu)
