### ISSUE TITLE
Les miniatures des articles n'existent pas

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#274]
> **Information :** C'est possible que ce n'est pas votre faute mais comme je n'ai pas le bug sur les tutoriels, je crée quand même une issue.

Serveur : Bêta
Version : test_zep12/fb381a2
Système : OS X
Navigateur : Chrome

---

Scénario :
- Rendez-vous sur un article v1 avec une miniature.
- Constatez qu'il n'y en a aucune.

**Comment by DevHugo** [comment]
C'est pseudo-normal, enfait les images n'existent pas sur le disque en beta. Si tu regarde la liste des articles, certains articles ont des miniatures car les images existaient sur le disque mais pas tous. 

J'ai cru à un bug aussi mais après une longue discutions, on s'est rendu compte que non :P

**Comment by artragis** [comment]
je ferme, c'est à cause de la béta ellem ême.
