### ISSUE TITLE
Possibilité d'ajouter des sections à un article

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#275]
Serveur : Bêta
Version : test_zep12/fb381a2
Système : OS X
Navigateur : Chrome

---

Scénario :
- Rendez-vous sur un article v1.
- Ajoutez une section.
- Constatez que c'est possible, que son style diffère du reste et qu'il est possible de le supprimer/déplacer/éditer contrairement au contenu existant.

**Comment by GerardPaligot** [comment]
Oh, je viens de comprendre que le contenu des anciens articles n'est qu'un chapitre avec une introduction où on y place tout le contenu. D'où la possibilité de mettre des sections.

Je n'ai pas de solution mais c'est quand même sacrément moche. =/

**Comment by artragis** [comment]
Attention, c'est un poil plus complexe que ça : 
- SI l'ancien article possède des titres de niveau 1 alors il est splitté en sections
- Sinon tout est dans l'intro.

C'est voulu.
