### ISSUE TITLE
Mauvais titre du MP créé pour la mise en bêta d'un article

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#276]
Serveur : Bêta
Version : test_zep12/fb381a2
Système : OS X
Navigateur : Chrome

---

Scénario :
- Rendez-vous dans un article v1 ou v2, peu importe.
- Activez la bêta.
- Consultez vos MPs.
- Constatez que le titre du MP est "Tutoriel en bêta" plutôt que "Article en bêta" ou "Contenu en bêta".

**Comment by artragis** [comment]
@Vayel, tu les aimes ces corrections là :p 

Je regarde ce midi.

**Comment by artragis** [comment]
fixé, ça apparaîtra la prochaine fois que sandhose fera le pull.
