### ISSUE TITLE
Impossible de déplacer un chapitre au même niveau qu'une partie

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#285]
Serveur : Bêta
Version : zep-12/3d868cc
Système : OS X
Navigateur : Chrome

---

Scénario :
- Dans un tutoriel avec des parties, des chapitres et des extraits, placez vous dans la première partie.
- Cliquez sur "Déplacer" du premier chapitre dans la partie.
- Tentez de le déplacer avant la partie dans laquelle vous vous trouvez.
- Constatez l'erreur suivante :

``` console
GitCommandError at /contenus/deplacer/
'git mv --dry-run 323_fragmenter-vos-projets/1795_fragment fragment' returned with exit code 128
stderr: 'fatal: bad source, source=323_fragmenter-vos-projets/1795_fragment, destination=fragment/1795_fragment'
```

> **Information :** Avant de tomber sur cette erreur, j'ai eu une 404 avec exactement la même manipulation.

**Comment by pierre-24** [comment]
Pour le coup, c'est probablement une vraie erreur, puisque tu l'as effectuée sur "l'autre tuto", celui dont je suis à peu près certain que le manifest est juste.

**Comment by artragis** [comment]
> Information : Avant de tomber sur cette erreur, j'ai eu une 404 avec exactement la même manipulation.

la 404 était-elle une page personnalisée ou bien le message d'erreur apparaissait-il?

**Comment by GerardPaligot** [comment]
@pierre-24 Oui, j'ai fais le déplacement avec mon tuto Android valide (pas celui dans un état incertain).

@artragis 

Voici ce que me dit la 404 : 

> The specified tree is invalid.

**Comment by artragis** [comment]
Elle dit ça sur la nouvelle version?

= c'est strictement impossible sauf si la branche n'a pas été tirée depuis
des lustres.

2015-08-24 9:22 GMT+02:00 Gérard Paligot notifications@github.com:

**Comment by GerardPaligot** [comment]
Tout ce que je dis ici est fait sur la bêta de la version zep-12/3d868cc (comme mentionné dans mon premier message). Après, je ne sais pas à quoi ça correspond chez vous.

**Comment by artragis** [comment]
C'est une version qui est dérivée de notre branche et non tirée de manière
brute. Je ne peux rien te dire.

**Comment by pierre-24** [comment]
> = c'est strictement impossible sauf si la branche n'a pas été tirée depuis
> des lustres.

Je ne serait pas aussi affirmatif. Je sais que c'est codé de manière relativement robuste et testé de même, mais puisque cette fois-ci c'est sur un "vrai" tuto, je n'excluerais pas la possibilité d'un bug.

**Comment by GerardPaligot** [comment]
Si vous avez un environnement à jour quelque part, je peux y importer mon tutoriel et faire la manipulation.

**Comment by artragis** [comment]
> Je ne serait pas aussi affirmatif. Je sais que c'est codé de manière relativement robuste et testé de même, mais puisque cette fois-ci c'est sur un "vrai" tuto, je n'excluerais pas la possibilité d'un bug.

Non, ce que je veux dire c'est que j'ai fait en sorte d'ajouter des
précisions au message d'erreur. Donc, si la précision n'apparait pas c'est
qu'on est sur une vieille version.

**Comment by artragis** [comment]
@GerardPaligot comme toujours http://zds.francoisdambrine.me

**Comment by GerardPaligot** [comment]
La manipulation de cette issue fonctionne sur ton instance. Si elle est à jour par rapport à avec ZEP, vous pouvez fermer ici.

**Comment by pierre-24** [comment]
Tu peux re-tester sur la bêta, maintenant ?

**Comment by GerardPaligot** [comment]
Tout fonctionne.
