### ISSUE TITLE
Page blanche à la suppression d'un tuto publié

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#286]
Serveur : Bêta
Version : zep-12/3d868cc
Système : OS X
Navigateur : Chrome

---

Scénario :
- Dans la version offline d'un tutoriel publié, tentez de le supprimer avec l'URL de suppression dans le navigateur. Par example : `http://beta.zestedesavoir.com/contenus/supprimer/201/introduction-aux-tests-android-avec-espresso/`
- Constatez une page blanche.

A mon avis, c'est simplement que la requête `GET` de votre vue n'est pas protégée.

**Comment by pierre-24** [comment]
[Elle l'est](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_contents.py#L311), mais je crois que du coup, Django renvoi une 405 (?) qui ne correspond à aucune page chez nous, donc on se mange une page blanche.

**Comment by GerardPaligot** [comment]
Il faudrait vérifier mais je vois rien dans ma console Chrome.

**Comment by pierre-24** [comment]
Je sais, et c'est comme ça depuis toujours. J'avoue que je me suis pas trop penché sur le problème, vu que c'est pas sencé arriver, mais je ferais une petite recherche tantôt.

**Comment by GerardPaligot** [comment]
On est d'accord. La priorité est super basse mais faudrait quand même vérifier parce que si ça se trouve, vos vues ne sont pas (toujours) protégées dans certains verbes et peut alors entrainer des problèmes à l'avenir (ou même maintenant pour les gens tordues qui cherchent des bugs).

**Comment by pierre-24** [comment]
[on pourrait définir une page d'erreur custom](http://stackoverflow.com/a/4634795), mais est ce que c'est pas hors-scope de la ZEP-12 ?

(dans tout les cas, cette vue là est bien protégée).

**Comment by artragis** [comment]
Je ferme car il suffit de créer une page custom et c'est hors scope zep-12

**Comment by pierre-24** [comment]
Je tagge "évolution" pour qu'on s'en souvienne.
