### ISSUE TITLE
Search down

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#287]
Serveur : Bêta
Version : zep-12/3d868cc
Système : OS X
Navigateur : Chrome

---

Scénario :
- Tentez de faire une recherche.
- Constatez l'erreur suivante :

``` console
OperationalError at /rechercher/
(1054, "Unknown column 'search_searchindexcontent.pub_date' in 'field list'")
```

**Comment by pierre-24** [comment]
De fait, c'est ma faute. J'ai demandé à @sandhose de remettre la ZEP-12, mais j'ai oublié de lui demander de faire un `python manage.py migrate` ;)

**Comment by pierre-24** [comment]
Ok !
