### ISSUE TITLE
Mauvais affichage de la pagination

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#288]
Serveur : Bêta
Version : zep-12/3d868cc
Système : OS X
Navigateur : Chrome

---

Scénario :
- Rendez-vous sur la page qui liste les tutos ou les articles.
- Constatez que l'affichage de la pagination est mauvais.

<img width="1078" alt="capture d ecran 2015-08-23 a 23 44 44" src="https://cloud.githubusercontent.com/assets/1913901/9430328/23d159c6-49f1-11e5-984f-5b3b0e0ea8e1.png">
<img width="1089" alt="capture d ecran 2015-08-23 a 23 44 49" src="https://cloud.githubusercontent.com/assets/1913901/9430329/28a248a2-49f1-11e5-8cb7-01364c8fdeb3.png">

**Comment by pierre-24** [comment]
Oublié de faire un `npm run gulp -- build`, parce que je suis quasi certain d'avoir vu passer le commit corrigeant ça :)

**Comment by artragis** [comment]
La correction a été faite mais comme on n'est effectivement pas sur un processus de release le front n'est pas automatiquement généré et sandhose a oublié de faire un gulp build.
