### ISSUE TITLE
PDF indisponible sur les tutoriels publiés

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#289]
Serveur : Bêta
Version : zep-12/3d868cc
Système : OS X
Navigateur : Chrome

---

Scénario :
- Rendez-vous sur ce [tutoriel](http://beta.zestedesavoir.com/tutoriels/201/introduction-aux-tests-android-avec-espresso/).
- Constatez que le PDF n'est pas disponible.

> **Complément :** J'étends cette issue à la version Markdown.

**Comment by pierre-24** [comment]
On a probablement oublié de re-générer les PDFs, parce que j'ai bien un PDF en local:

![screenshot from 2015-08-24 08 19 43](https://cloud.githubusercontent.com/assets/7889675/9433919/ef0cfc0c-4a38-11e5-95af-99bce3021d1f.png)

(des fois, c'est simplement pandoc qui a pas envie)

**Comment by artragis** [comment]
Notons que pandoc n'aime pas les chemin windows avec les antislash, si tu en a mis un dans ton tuto, ça peut foirer :p

**Comment by GerardPaligot** [comment]
Je n'aurais pas fermé cette issue parce que je vois 2 problèmes :

> (des fois, c'est simplement pandoc qui a pas envie)

Faudrait un mécanisme pour relancer pandoc.

> Notons que pandoc n'aime pas les chemin windows avec les antislash, si tu en a mis un dans ton tuto, ça peut foirer :p

Ce qui est un bug.

**Comment by artragis** [comment]
> Ce qui est un bug.

Ce qui est un bug déjà en prod, c'est donc sur le github de zds que ce
rapport doit se trouver, pas ici.

**Comment by pierre-24** [comment]
> Faudrait un mécanisme pour relancer pandoc.

J'ai peur que le "mécanisme" en question ne lance pandoc en boucle si il y a une erreur. Vu la "stabilité" du système pour le moment, je préfère pas.

> Ce qui est un bug déjà en prod, c'est donc sur le github de zds que ce rapport doit se trouver, pas ici.

Ce qui, de tête, est déjà le cas :)
