### ISSUE TITLE
Le nombre de résultat par page pour la recherche n'est pas cohérent

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#291]
https://beta.zestedesavoir.com/rechercher/?q=...............&page=1

Deux résultats sur la première page, mais plusieurs page aprés.

**Comment by pierre-24** [comment]
... Bien vu, mais uniquement sur ce terme là, à priori.

**Comment by pierre-24** [comment]
Alors maintenant, c'est carément des pages vides :o

**Comment by DevHugo** [comment]
C'est pas liés à ça: https://github.com/zestedesavoir/zds-site/issues/2902.

J'ai pas d'environnement de dev, près mais si ça ne marche pas sur la branche dev, tu ferme.

**Comment by artragis** [comment]
c'est à cause des accès je pense.

**Comment by DevHugo** [comment]
Je confirme, c'est artragis qui avait raison, la mise en page prend pas en compte que certains sujets et messages ne sont affichable.

Ça été confirmé par Pierre, qui lui voit les sujets et les messages car il est le seul dans le staff (c'est un bleu !).

**Comment by pierre-24** [comment]
Je confirme :p 

(je suis staff "par erreur", à mon avis sandhose en avait marre de me voir râler).

Plus sérieusement, je parie que la correction tient à un

``` python
disallowed_forums =[f.pk for f in  Forum.object.filter(group__isnull=False).all()]
queryset = Topic.objects.exclude(forum__pk__in=disallowed_forums) # ... et la suite
```

**Comment by DevHugo** [comment]
Je sais pas du tout pourquoi, c'est comme ça, quand je coche la case tutoriel à droite, j'ai une page vide, … : https://beta.zestedesavoir.com/rechercher/?q=...................&models=tutorial&page=1

**Comment by pierre-24** [comment]
Ah, ce coup-ci, j'ai une page vide aussi, donc je peux pas t'aider :/

**Comment by DevHugo** [comment]
Je pense que ça serait pas mal d'aller voir dans l'interface de Solr ce qui est retourné ! Je vais aller souler Sandhose pour ça. 

EDIT: MP envoyé.

**Comment by DevHugo** [comment]
Apparemment, ils ont bloqué l’accès à l'interface admin de Solr, dommage, va falloir trouver un autre moyen de debug.

**Comment by DevHugo** [comment]
J'ai demandé à Sandhose, d'afficher la variable résultat directement (rajouter une ligne la 79 avec {{ result }} dans le templates/search/search.html) et c'était toujours la même chose, j'en conclus, que c'est pas liés au conditions dans le template.

**Comment by DevHugo** [comment]
Je viens de découvrir quelque chose de drôle. Sur cet exemple, https://beta.zestedesavoir.com/rechercher/?q=...................&models=tutorial&page=1. Au début, la barre nous affiche que la 5éme est la dernière, si on clique sur celle-ci, il nous affiche que la page 6 est la dernière. 

Sur l'exemple, que j'ai donné au début, (https://beta.zestedesavoir.com/rechercher/?q=...............&page=1) même principe, si on est sur la page une, la dernière page est la 2509, si on clique sur la troisième page, la dernière est la 2510. Alors qu'on a deux pages vides au départ.

**Comment by DevHugo** [comment]
@pierre-24, tu pourrais me donner l'id d'un sujet qui ne s'affiche pas en tant que membres mais pour les admins, oui ?

Comme ça, on pourrais l'exporter depuis la pré-prod, sur une instance de dev et arriver à reproduire le souci au moins pour les sujet et topic après, on verra pour les tutoriels.

**Comment by pierre-24** [comment]
889, par exemple. Ceci dit, le bug m'as l'air "facile" à reproduire, il suffit de créer un forum "privé" et de poster dedans puis d'indexer.

**Comment by pierre-24** [comment]
Petite avancé (ou pas): je n'ai aucun résultat quand je cherche ".." via l'interface de solr

![screenshot from 2015-09-05 22 47 45](https://cloud.githubusercontent.com/assets/7889675/9701232/38e26d94-5420-11e5-82e2-1463dac16aaf.png)

**Comment by DevHugo** [comment]
Regarder ce que j'ai trouvé en prod : https://zestedesavoir.com/rechercher/?q=%3C (rechercher des "<" ou des ">")

Le bug étant présent en prod, ce n'est pas de la responsabilité de la ZEP-12.

**Comment by DevHugo** [comment]
@Artragis et @pierre-24 , je ferme donc.
