### ISSUE TITLE
Extrait des articles dans la recherche

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#292]
La recherche ne permet pas de s'effectuer sur les extraits des articles (pas l'option), alors qu'ils sont bien indexés.

**Comment by DevHugo** [comment]
Que les informations sont dans les tables de la recherche (C'est ça que tu veux dire pas indexes) ?

**Comment by pierre-24** [comment]
Oui :)

**Comment by DevHugo** [comment]
Tu peux donner un exemple ?

**Comment by pierre-24** [comment]
Eh bien par exemple, [si je cherche "limonène"](https://beta.zestedesavoir.com/rechercher/?q=limon%C3%A8ne), qui est renseigné [dans mon article pour le CdS](https://beta.zestedesavoir.com/articles/75/philae-a-la-recherche-de-lorigine-de-la-chiralite-du-monde/#4-limportance-de-la-chiralite-dans-la-vie), je tombe effectivement bien au bon endroit, mais c'est renseigné comme "article" et non comme "extrait" (bon, le système est cohérent, si je sélectionne "article", je tombe bien dessus).

**Comment by artragis** [comment]
not a bug amha.

**Comment by pierre-24** [comment]
C'est pas un "bug" dans le sens ou ça fonctionne, plutôt quelque chose de pas logique :)

**Comment by DevHugo** [comment]
Y'a quand même souci qui se pose:
- Que fait-on des articles qui ont été copiées dans l'introduction ?

**Comment by pierre-24** [comment]
Ben l'introduction est aussi indexée, non ?

**Comment by DevHugo** [comment]
Sinon je viens de penser à une méthode de faignasse, ce matin on rajoute le mot "des tutoriels" après extraits. Ça donne comme critères de recherche "extraits des tutoriels", et comme ça, plus de souci et la correction est facile à faire.

**Comment by pierre-24** [comment]
Je suis d'accord avec la "correction de feignasse". À noter qu'entre temps, extrait → section :)

**Comment by artragis** [comment]
+42

**Comment by pierre-24** [comment]
C'est déjà le cas ;)
