### ISSUE TITLE
Certain tutoriel sont introuvable à partir de la recherche

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#293]
Tenter de rechercher le tutoriel "Une introduction à Ruby", il est impossible à trouver.

**Comment by pierre-24** [comment]
Ben ... Si ! https://beta.zestedesavoir.com/rechercher/?q=ruby&models=tutorial

![screenshot from 2015-08-25 15 36 28](https://cloud.githubusercontent.com/assets/7889675/9467916/10b1ce9e-4b3f-11e5-8d80-45c569c341c9.png)

**Comment by DevHugo** [comment]
Bizarre, y'a 30 secondes, y'avais aucun résultat …

**Comment by DevHugo** [comment]
Je suis passé au moment de son indexation ?

**Comment by pierre-24** [comment]
Possible :o

**Comment by GerardPaligot** [comment]
D'ailleurs, vous vous basez sur quoi pour lister les résultats ? Si je fais une recherches "android", j'ai certains tutos dans les premiers résultats (pas les miens :'() et quand je liste simplement les tutoriels, je n'arrives pas trouver comment vous ordonnez la liste.

**Comment by pierre-24** [comment]
C'est Solr qui choisi, et j'ai aucune idée de ces critères :o

**Comment by GerardPaligot** [comment]
C'est sans doute hors scope à votre ZEP mais c'est dommage parce que, pour l'instant, Solr remontent plutôt des vieux contenus au détriment de nouveaux.

**Comment by DevHugo** [comment]
On peut dire à Solr que certains champs sont plus important que d'autre, dans leurs langages, ils appellent ça le boost d'un résultat. [Plus d'information](http://django-haystack.readthedocs.org/en/latest/boost.html). 

Ça serait bien qu'on le fasse nous.

**Comment by GerardPaligot** [comment]
Je t'autorise à appliquer un boost impressionnant quand le contenu est de moi ... :-°

**Comment by artragis** [comment]
mais à le diminuer que ça concerne un OS de google (quitte à troller :p)

**Comment by pierre-24** [comment]
Bon, plus sérieusement, rien de plus à faire, ici, non ? :)
