### ISSUE TITLE
Erreur de comptage en page d'acceil

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#296]
> "Il y a 194 tutoriels sur Zeste de Savoir.
> Pourquoi pas le vôtre ?"
> Source: [la page d'acceil](https://beta.zestedesavoir.com/)

... Non, pas que je sache (à tout casser 100, et encore, pas sur la bêta) ^^

Mais [on compte aussi les redirections](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/pages/utils.py#L47), donc on en compte de trop ;)

**Comment by artragis** [comment]
easy à corriger ça :p

**Comment by artragis** [comment]
done.

**Comment by pierre-24** [comment]
NIce :)
