### ISSUE TITLE
Merge non cohérent dans le fichiers search/utils.py

### ISSUE THREAD

**Issue by DevHugo** [artragis/zds-site#298]
Y'a deux fois, les mêmes lignes: 

```
    search_index_content.type = published_content.content_type.lower()
    search_index_content.save()
```

https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/search/utils.py#L262

**Comment by pierre-24** [comment]
C'est ma faute, je pense que j'ai été trop vite dans mon "nettoyage"

**Comment by pierre-24** [comment]
Tient, au passage, il y a plein de commentaires à supprimer dans ces fichiers là.

**Comment by pierre-24** [comment]
Ok :)
