### ISSUE TITLE
Le markdown dans les titres des articles n'est plus interprété

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#299]
Dans le contenu des articles avant on avait des titres formatté. Ce qui fait qu'on pouvait passer en italique un terme du titre. Après migration zep-12, les titres ne sont plus formattés.

Exemple de ce problème : http://beta.zestedesavoir.com/articles/30/a-la-decouverte-de-lunivers-du-big-data/#2-le-big-data-aujourdhui

Une solution possible pour ce problème serait de faire sauter tout formattage (et donc de virer les étoiles mardkwon ) avant de réécrire le titre comme le fait le script de migration.

**Comment by artragis** [comment]
@pierre-24

**Comment by pierre-24** [comment]
Je suis surtout en train d'avoir la réflexion inverse : pourquoi ne pas supporter le markdown dans les titres en mode _inline_, comme pour les signature ?
