### ISSUE TITLE
Rediriger les URL

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#30]
Pour l'instant le nouveau module pointe vers /contenus/ qui est une sorte d'alias de /tutoriels/ (dans le sens où il n'affiche que les listes de tutoriels pour les vues "en liste")

Il faudra donc migrer tout ça vers /tutoriels/ et /articles/ Nécessite la création d'un fichier url_articles.py qui redirige vers les bons contrôleurs (exemple `DisplayArticle`)

**Comment by pierre-24** [comment]
en partie fait par #56 :)

**Comment by pierre-24** [comment]
Fait, du coup !

**Comment by artragis** [comment]
Ah bon? tu l'as géré?

**Comment by pierre-24** [comment]
J'ai peut être mal compris le problème, mais je pense que c'est exactement ce que j'ai fait dans `urls_*.py`, non ? À moins que tu ne mentionnais le fait de remplacer les anciennes URLs par les notres ?

**Comment by artragis** [comment]
Oui.

**Comment by pierre-24** [comment]
Oups, alors ça rentre dans le "boss final de la ZEP-12" ;)

**Comment by pierre-24** [comment]
Me semble que tu l'as fait, ça, du coup ?

**Comment by artragis** [comment]
Je passe en needqa si c'est ça qui s'est passé.

**Comment by Vayel** [comment]
Ca semble bon ici. Bien sûr, il y a un 2 qui se balade, mais j'imagine que c'est voulu.

**Comment by Vayel** [comment]
Up

**Comment by artragis** [comment]
en effet, c'est bon désolé.
