### ISSUE TITLE
Depuis une version d'un chapitre de tutoriel, on a pas de lien pour revenir a la version en brouillon

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#300]
Lorsque je parcours une version d'un chapitre d'un tutoriel [celui-ci par exemple](http://beta.zestedesavoir.com/contenus/434/creer-un-jeu-html5-avec-quintus/272_decouverte-de-la-librairie/1553_se-familiariser-avec-quintus/?version=d28c954892e572ad10536a7c2375733986ecb852), je n'ai aucun lien pour revenir a la version brouillon du chapitre en question.

**Comment by artragis** [comment]
on peut le faire en prod ça?

**Comment by pierre-24** [comment]
[Non](https://zestedesavoir.com/tutoriels/beta/1101/les-neurosciences-de-zero/1343/le-plan-dorganisation-du-systeme-nerveux/5318/systeme-nerveux-peripherique/).

**Comment by artragis** [comment]
Donc je ferme.
