### ISSUE TITLE
Erreur 500 sur la redirection d'une url de tutoriel

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#301]
url impactée : http://beta.zestedesavoir.com/tutoriels/234/creer-un-jeu-html5-avec-quintus/356/mettre-en-place-un-niveau/1904/des-ennemis-parce-quil-en-faut/

J'ai essayé de vérifier que la redirection des anciennes urls fonctionne et j'ai une erreur 500. :(

**Comment by artragis** [comment]
Oui, ça je le corrige maintenant, je sais pourquoi ça fait ça.
