### ISSUE TITLE
L'export d'un tutoriel ne contient plus sa date de publication

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#303]
Un exemple d'export markdown d'un tutoriel après zep-12 : http://beta.zestedesavoir.com/tutoriels/md/473/une-introduction-a-ruby.md

Un exemple d'export du même tutoriel avant zep-12 : zestedesavoir.com/tutoriels/telecharger/md/?tutoriel=373

On voit bien que la date de publication est absente après la liste des auteurs. Ce qui fait que l'on se retrouve avec un pdf dont la coverpage ne contient plus de date.

**Comment by artragis** [comment]
non, on ne voit pas bien. 404 sur zep12 et 403 sur prod.

**Comment by artragis** [comment]
j'aimerais vraiment voir si cela existe en prod et sous quelle forme.

**Comment by firm1** [comment]
Voici ce qu'on voit sur l'export markdown de la **zep12** : 

> ``` text
> % UNE INTRODUCTION À RUBY 
> % __forever, baptisteguil, Karnaj
> % 
> 
> 
> 
> 
> 
> # Introduction
> 
> Vous rêvez d’apprendre un langage de programmation simple ?  
> Pourquoi ne pas apprendre le Ruby ? Ruby est un langage de programmation **libre** et **dynamique**, qui met l'accent sur la **simplicité et la productivité**. Sa **syntaxe** élégante en facilite la lecture et l'écriture.
> ```

Voici ce qu'on voit sur l'export markdown en **prod** : 

> ```
> % UNE INTRODUCTION À RUBY
> % __Forever, Baptisteguil, Karnaj, 
> % 02 juin 2015
> 
> 
> 
> # Introduction
> Vous rêvez d’apprendre un langage de programmation simple ?  
> Pourquoi ne pas apprendre le Ruby ? Ruby est un langage de programmation **libre** et **dynamique**, qui met l'accent sur la **simplicité et la productivité**. Sa **syntaxe** élégante en facilite la lecture et l'écriture.
> ```

Le problème se situe donc au niveau de la date

**Comment by artragis** [comment]
Ah ok ça devrait pas être trop complexe donc.

**Comment by pierre-24** [comment]
Indirectement, je viens de remarquer un second bug dans le même coin:  y'a que les admins qui ont accès au markdown, plus les auteurs (régression)

**Comment by artragis** [comment]
Les auteurs n'y avaient pas accès sur la prod et je pense que c'est
souhaitable qu'ils y ait accès sur la zep12

**Comment by pierre-24** [comment]
Tout un moment, ils y avaient accès. Je crois que c'est ma PR sur les permissions qui a cafouillé quelque part.

**Comment by pierre-24** [comment]
À vérifier au prochain wipe+migration, parce qu'en local, j'arrive pas à reproduire
