### ISSUE TITLE
Le canonical n'est pas pris en compte

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#304]
Tutoriel d'exemple : http://beta.zestedesavoir.com/tutoriels/255/le-tri-par-selection/

On voit bien en inspectant le code source html que le contenu de la page n'a pas de "rel=canonical" alors que la source de ce tutoriel est OC et que ça a été précisé lors de la validation.

Un bug qui a un impact négatif sur le SEO donc.

**Comment by artragis** [comment]
@pierre-24 ?

**Comment by pierre-24** [comment]
Ce qu'il dit, c'est qu'en fait, notre script de migration ne migre pas le champ `source` des [tutos](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorial/models.py#L53), donc effectivement, on a plus de _canonical_ :) (correction d'une ligne)

**Comment by artragis** [comment]
ok je fais.
