### ISSUE TITLE
Les liens de la beta postés dans les forums ne sont pas redirigés avec la zep12

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#305]
[Cette url](http://beta.zestedesavoir.com/tutoriels/beta/941/creez-une-single-page-app-avec-nodejs-et-meteor/) devrait rediriger le lecteur vers la version beta du tutoriel au lieu de ça, on a une 404.

Si les anciennes urls de beta ne sont pas supportées il faudra un script qui met à jour le contenu des messages du forum de beta pour pas que les auteurs aient à modifier eux même.

**Comment by artragis** [comment]
on va les supporter ça sera relativement facile.

**Comment by pierre-24** [comment]
En effet. Ça tient toujours, ton histoire de table de redirection ?

**Comment by artragis** [comment]
oui.

**Comment by artragis** [comment]
j'y regarde demain midi si j'ai le temps.

**Comment by artragis** [comment]
c'est bon, c'est corrigé.

**Comment by pierre-24** [comment]
Je confirme !
