### ISSUE TITLE
Le texte de mise en beta d'un article n'est pas bon

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#309]
Au delà du style utilisé qui me dérange un peu, le texte de mise en beta d'un article à quelques défaut de fond.

Pour exemple, voici ce que j'ai : 

> Tout le monde se secoue ! :D
> 
> J'ai commencé (il y a 6 minutes) la rédaction d'un tutoriel au doux nom 
> de « Mon article » et j'ai dans l'objectif de proposer en validation 
> un texte aux petits oignons. Je fais donc appel à votre bonté sans 
> limite pour dénicher le moindre pépin, que ce soit à propos 
> du fond ou de la forme. Vous pourrez consulter la bêta à votre guise à 
> l'adresse suivante :
> 
> -> [À présent, c'est à vous !](lien) <-
> 
> Merci !
- Il y'a 4 lignes d'espaces vides au début et deux lignes d'espace vide à la fin
- je demande la beta d'un article, mais le texte me dit que je propose un tutoriel

**Comment by firm1** [comment]
Je retire ce que j'ai dis pour cette remarque : 

> je demande la beta d'un article, mais le texte me dit que je propose un tutoriel

Il s'agit d'un tutoriel et non d'un article que j'ai crée

**Comment by artragis** [comment]
Pour le ton il est temps de se réveiller, ça fait des plombes qu'on a demandé des avis et que personne ne s'y est intéressé.
