### ISSUE TITLE
[TEST] Tester les scripts de migration sur des vrais contenus

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#31]
Il faudra tester le bon fonctionnement des scripts sur des vrais contenus quitte même à le faire sur un dump de la base actuelle.

**Comment by GerardPaligot** [comment]
# Problème 1

J'ai voulu testé votre ZEP et j'ai donc voulu importer mon big tuto Android sur une instance locale. J'ai lu et j'ai suivi tout ce que vous avez mentionné dans votre documentation :
1. J'ai téléchargé l'archive de mon tutoriel sur zestedesavoir.com
2. J'ai décompressé l'archive
3. J'ai exécuter la commande : `python manage.py upgrade_manifest_to_v2 ~/Downloads/aller-plus-loin-dans-le-developpement-android/`
4. J'ai re-compressé le même dossier
5. Je l'ai soumis à `http://localhost:8000/tutoriels/importer/` dans la première section "Envoi d'une archive"
6. Il m'a demandé de spécifier un tutoriel hôte (pourquoi ?). J'ai donc créer vite fait un tutoriel et je l'ai spécifié.

Réponse :

> L'archive n'a pas pu être importée car le fichier manifest.json (fichier de métadonnées est introuvable).

Qu'est ce que j'ai fais avant :
1. J'ai mis à jour les requirements de mon environnement de dev.
2. J'ai fais un syncdb pour avoir vos tables

# Problème 2

Dans votre documentation, juste après, vous informez que vous avez développé un script pour migrer les bases de données. J'ai d'abord copié-collé ce qui est spécifié :

```
python manage.py migrate_to_zep12.py
```

Je soupçonne le .py en trop à la fin de la commande. Je l'ai donc retiré et j'obtiens la réponse : 

``` console
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/gerard/Documents/workspace-django/zdsenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/gerard/Documents/workspace-django/zdsenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/gerard/Documents/workspace-django/zdsenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 238, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/Users/gerard/Documents/workspace-django/zdsenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 41, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/gerard/Documents/workspace-django/zds-site/zds/tutorialv2/management/commands/migrate_to_zep12.py", line 12, in <module>
    from zds.tutorialv2.models import PublishableContent, Extract, Container  # , VersionedContent
ImportError: cannot import name PublishableContent
```

**Comment by pierre-24** [comment]
Ouille, il va falloir qu'on repase par là. Tu pointes là un problème très simple, c'est que comme on a eu tout les problèmes de doc, on a un peu laissé tombé le maintient de la doc pour le moment. En l'occurence, `http://localhost:8000/tutoriels/importer/` n'est pas la bonne URL (ça, c'est encore dans l'ancien système, d'où la demande d'un "tutoriel hôte"), c'est probablement `http://localhost:8000/contenus/importer/archive/nouveau/` (et c'est là que je me rend compte que cette URL est un peu moche).

Pour le deuxième point, c'est "facile à régler", mais je m'étonnes que PyCharm n'y aie pas pensé de lui-même quand j'ai fait mon gros déplacement.

Dans tout les cas, il va falloir qu'on aie refaire un tour dans ce coin là (ne serait-ce que parce que maintenant, l'interface d'import accepte également les tutos/articles V1, ce qui va probablement simplifier le code). D'ailleurs, cette partie là gère pas encore les commentaires, de mémoire.

**Comment by GerardPaligot** [comment]
Ok, j'ai refais un test avec l'URL que tu m'as donné et le message est tout pareil concernant le manifest alors qu'il est bien présent à la racine de mon archive.

**Comment by pierre-24** [comment]
Ok, je note. Je pense que la ZEP-12 ne t'aimes pas, et j'en suis vraiment désolé, je te jure que c'est pas fait exprès ^^

**Comment by artragis** [comment]
Etrange, le script est maintenant testé et chez nous... ça marche.

**Comment by artragis** [comment]
(je parle des tests unitaires)

**Comment by GerardPaligot** [comment]
Vous l'avez testé avec des archives ? Perso, même avec des tutos simples ([celui-ci](https://zestedesavoir.com/tutoriels/457/introduction-a-linjection-de-dependances-en-java/) par exemple), il refuse d'importer le tutoriel.

**Comment by artragis** [comment]
Pour l'import direct, oui, c'est testé avec une archive.
Pour la migration du manifest, c'est identique, nous avons décompressé 
des archives de la prod puis nous lançons la commande, enfin nous 
testons que le manifeste est bien migré et en ordre de marche.

Vérifie que tu utilises bien le chemin absolu vers le manifeste quand tu 
fais la migration.

**Comment by GerardPaligot** [comment]
Rien à faire, la migration échoue. Voici les étapes précises que je fais :
1. Je télécharge cette [archive](https://zestedesavoir.com/tutoriels/telecharger/?tutoriel=457&online)
2. Je la décompresse et j'execute cette commande : `python manage.py upgrade_manifest_to_v2 /Users/gerard/Downloads/introduction-a-linjection-de-dependances-en-java/manifest.json`
3. Je recompresse le même dossier et je le soumets.

> Cette archive ne contient pas de fichier manifest.json

Je crois que @pierre-24 a raison. Votre ZEP me boude.

**Comment by pierre-24** [comment]
:'( 

... Ceci étant dit, avant d'abandonner, je vais quand même te demander de vérifier que le manifest.json est bien à la racine de l'archive et qu'il est pas dans un dossier dans l'archive (Linux me fait ça)

**Comment by GerardPaligot** [comment]
Non, il est bien à la racine de l'archive.

**Comment by pierre-24** [comment]
Ok. Tu saurais me donner l'archive "transformée" ? (Dropbox, MP, mail si tu veux, ce que tu veux). Je vais chercher à comprendre.

**Comment by GerardPaligot** [comment]
Bien sûr : https://www.dropbox.com/s/eb8cgoyga92f3cu/introduction-a-linjection-de-dependances-en-java.zip?dl=0

**Comment by pierre-24** [comment]
Ah, mais le contenu du tuto n'est pas _à la racine_ de l'archive comme c'est le cas dans l'archive d'origine:

![screenshot from 2015-05-14 13 32 20](https://cloud.githubusercontent.com/assets/7889675/7637680/b7eec9bc-fa3d-11e4-8f2a-edb9f3f370a6.png)

Après, peut être que Mac OSX force les archives ZIP à ressembler à ça, mais c'est pas le format attendu :s

**Comment by GerardPaligot** [comment]
Oh que j'aime OS X. :)

Alors pour vous expliquez, j'ai compressé le dossier avec l'utilitaire par défaut d'OS X, donc celui que 99% des utilisateurs OS X utilisent. 2 solutions :
1. Dire dans la doc que OS X c'est de la merde et de télécharger un autre outil pour compresser. C'est tentant mais sachant que nous nous adressons à des auteurs, je vois mal leur imposer ça.
2. Être compatible avec les archives OS X.

**Comment by pierre-24** [comment]
Au delà de ça, cette commande est un peu moins utile depuis que le _back_ gère les archives V1 (vérifie, tu verra que tu peux importer l'archive non transformée). Bref, faut qu'on réfléchisse à ça (une autre soluce est de regénérer une archive direct via la commande)

**Comment by GerardPaligot** [comment]
Effectivement, l'import direct des archives téléchargées depuis ZdS fonctionne (vous devriez donc retirer ce script). A l'exception de cette [archive](https://zestedesavoir.com/tutoriels/telecharger/?tutoriel=191) qui me dit :

> Le fichier "1377_fragment/introduction.md" n'existe pas dans l'archive

**Comment by pierre-24** [comment]
Pas accès ;)

Plus sérieusement, tu souleve un point intéréssant en disant que les gens sous mac ne pourront pas ré-importer leur archive (parce que c'est ce qui a de bien avec cette fonctionalité). Si ça casse pas tout et que c'est "facile" à faire, promis je tente de le mettre (je peux faire de la QA sur un vieux mac dans un mois).

**Comment by GerardPaligot** [comment]
> Pas accès ;)

https://www.dropbox.com/s/ltd4322h9mhnuxt/aller-plus-loin-dans-le-developpement-android.zip?dl=0

> Plus sérieusement, tu souleve un point intéréssant en disant que les gens sous mac ne pourront pas ré-importer leur archive (parce que c'est ce qui a de bien avec cette fonctionalité). Si ça casse pas tout et que c'est "facile" à faire, promis je tente de le mettre (je peux faire de la QA sur un vieux mac dans un mois).

Oui, je viens de me rendre compte que vous acceptez les archives pas que pour migrer un tuto v1 vers v2 mais aussi pour mettre à jour le contenu d'un tuto v2 tout simplement. Donc oui, il faudra trouver une solution pour les utilisateurs OS X ou proposer une solution alternative.

**Comment by pierre-24** [comment]
Le manifest est très très très très bizarre. Question, quand tu dit "archive direct téléchargées depuis ZdS", j'imagine que tu parles d'archive de tuto publique ? Alors que l'archive là qui foire, c'est celle d'un tuto en cours d'édition.

Well ... Il semblerai que cette commande soit utile après tout, je viens de découvrir que le manifest v1 n'était même pas cohérent avec lui-même: dans un manifest téléchargé à partir d'un _draft_, les chemins des intro/conclusions des chapitres sont écris en relatif par rapport au dossier de la partie, alors que c'est écris de manière absolue pour un tuto en ligne. Fait ch*** :o

**Comment by pierre-24** [comment]
... Sauf que quand je teste avec des big-tutos non-publiés à moi, ça le fait pas. D'où question: est ce que les chapitres du tuto en questions sont éditables ? Parce que le manifest.json est complètement pas normal :o 

![screenshot from 2015-05-14 21 57 15](https://cloud.githubusercontent.com/assets/7889675/7645512/2efdfb2c-fa84-11e4-98d9-6b5a385bfe41.png)

**Comment by GerardPaligot** [comment]
J'ai cherché la merde en prenant ce tutoriel. :)

C'est un tutoriel hors ligne, qui n'a jamais été soumis à la validation (et qui ne le sera jamais) et qui a été importé par le script de migration .tuto -> ZdS.

**Comment by artragis** [comment]
C'est justement pour ce genre de cas que cette tâche existe. ^^

**Comment by pierre-24** [comment]
Maintenant on sait ;)

**Comment by Eskimon** [comment]
On peut aider ici ?

**Comment by artragis** [comment]
- va chez toi
- lance python manage.py load_fixtures high
- lance python manage.py migrate_to_zep12

dis-nous où ça plante (car ça plantera, je n'ai fait que des tests basiques
à la main sur ce script)

2015-06-17 12:09 GMT+02:00 Eskimon notifications@github.com:

**Comment by Eskimon** [comment]
Alors je ne pourrais pas tester, le load_fixtures high est beaucoup trop long pour moi sur mon pc perso et beacoup trop lourd en memoire pour ma VM en ligne :(

**Comment by artragis** [comment]
C'est bon j'ai les logs :

! Missing $ inserted.
<inserted text>
                $
l.263 bits, il n'y a que \$ 2^{}{32} = 4 \times

pandoc: Error producing PDF from TeX source

**Comment by artragis** [comment]
mauvais topic.

2015-06-17 13:34 GMT+02:00 francois dambrine artragis@gmail.com:

> C'est bon j'ai les logs :
> 
> ! Missing $ inserted.
> <inserted text>
>                 $
> l.263 bits, il n'y a que \$ 2^{}{32} = 4 \times
> 
> pandoc: Error producing PDF from TeX source
>

**Comment by artragis** [comment]
BOn, actuellement, le script ne fonctionne pas vraiment très bien avec certains big tuto. C'est dû au fait qu'il n'utilise pas la vraie puissance de la zep12 et va chercher la blinde d'objet en bdd. 

Il va falloir qu'on revoie ça mais il faut bien comprendre que quoi qu'il arrive, il faudra utiliser certains objets bdd pour voir quand il y a eu publication etc.

La dernière erreur en date sur les big tuto est : 

``` console
(zds-env)francois@ns364219:~/zds-site$ python manage.py migrate_to_zep12
Le chemin physique vers /home/francois/zds-site/articles-data/1_paire-de-manche n'existe plus..........................] 0/11
Exporting articles[####################################################################################################] 11/11
Exporting mini tuto[####################################################################################################] 11/11
Traceback (most recent call last):......................................................................................] 0/10
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/home/francois/zds-site/zds/tutorialv2/management/commands/migrate_to_zep12.py", line 385, in handle
    migrate_big_tuto()
  File "/home/francois/zds-site/zds/tutorialv2/management/commands/migrate_to_zep12.py", line 325, in migrate_big_tuto
    current_extract = Extract(extract.title, extract.text[:-3].split("/")[-1])
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by pierre-24** [comment]
D'un autre côté, les arguments de `Extract` sont bizarre: https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/models/models_versioned.py#L746 ... C'est pas `str(extract.pk) +' _' + extract.slug` que tu veux employer ?

**Comment by artragis** [comment]
honnêtement, je sais pas, là j'ai juste testé. Il semble passer tous les articles, tous les minituto mais il me plante ça sur un bigtuto.

Ajoutons que nous n'avons pas de "vrai contenu" sur ma bdd. Va falloir que je demande aux gens de me passer des .tuto et que je les importe à la main puis tout tester.

**Comment by pierre-24** [comment]
Tu peux utiliser toutes les archives de tutos publié de ZdS que tu veux, pour rappel ;)

**Comment by artragis** [comment]
ces archives ne sont pas importables dans l'ancien model.

**Comment by pierre-24** [comment]
De fait. Fait ch*** ...

**Comment by artragis** [comment]
Les problèmes ont été résolu, je ferme l'issue, qui est bien mieux détaillée par #145 .
