### ISSUE TITLE
Un sujet de beta n'est pas recrée lorsque l'ancien sujet passe en corbeille

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#310]
Actuellement en prod, lorsque le sujet de beta d'un tutoriel est déplacé dans un autre forum que celui de la beta (la corbeille par exemple), lors de la prochaine activation de la beta, un nouveau sujet est recrée. Ce qui permet à un auteur de demander aux modos la mise à la poubelle d'un ancien topic de beta (pour diverses raisons) et ainsi recrée un topic propre.

Avec la zep-12 on a perdu cette fonctionnalité

**Comment by artragis** [comment]
c'est quelle vue qui est appelée pour le passage en corbeille?

**Comment by pierre-24** [comment]
>  lors de la prochaine activation de la beta, un nouveau sujet est recrée

Ça m'étonne. Dans mon souvenir, c'est le contenu (article/tuto) qui est rataché au topic et plus l'inverse. Du coup, malgré que le topic soit déplacé, il devrait toujours être rataché au contenu, vu que "la corbeille" est juste un fofo caché, ou je me trompe ?

**Comment by artragis** [comment]
Justement, c'est là qu'est le problème : il dit que comme le lien est concervé, même quand il est en mode poubelle le sujet est dit comme existant donc ça merde.

**Comment by pierre-24** [comment]
Ah, j'avais compris le problème dans l'autre sens. Bon, ben .. Faut détacher le topic le cas échéant ;)

**Comment by pierre-24** [comment]
Ah, je viens de regarder vite fait, [c'est à priori cette vue là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/forum/commons.py#L56), en conjugaison avec [ce morceau de code là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorial/views.py#L690), qui s'attend à ce que le topic soit dans le forum bêta, et donc qui recrée un topic si ce n'est pas le cas.

La solution, pour moi, c'est pas de modifier la vue de déplacement, mais plutôt d'aller mettre une condition dans la vue d'édition des bêta pour vérifier que le topic est toujours bien dans le bon forum. Ça me semble "plus propre".

**Comment by artragis** [comment]
je te laisse faire
