### ISSUE TITLE
Cohérence de vocabulaire entre les menus et la recherche

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#311]
La zep-12 supprime le concept d'extrait normalement (remplacé par le terme section - que je trouve moins évident-), mais dans la recherche, on retrouve encore l'utilisation du terme extrait, ce qui peut prêter à confusion.

Il faudrait harmoniser le vocabulaire.

**Comment by pierre-24** [comment]
Je suis d'accord avec l'idée d'harmonisation.

Pour ce qui est du vocabulaire, il est directement emprunté à LaTeX :-)

**Comment by firm1** [comment]
> il est directement emprunté à LaTeX

Je sais bien, mais ça ne veut pas dire que ça le rend plus évident.

Surtout que ça peut créer beaucoup de confusion quand on sait que Microsoft Office [utilise le terme de section pour désigner ce qu'on appelle une partie dans la zep-12](http://www.commentcamarche.net/contents/1656-word-sauts-de-section). Microsoft Word étant plus populaire que LaTex ...

A ce jeu là, je trouve toujours le vocabulaire "extrait" plus évident que "section".

**Comment by pierre-24** [comment]
Ce jeu là peut continuer longtemps et a déjà fait débat à l'époque, à plusieurs reprises, la conclusion était  ["chaipa"](https://github.com/artragis/zds-site/issues/49). Je trouve qu'une logique vaut l'autre, objectivement, extrait étant pas beaucoup mieux.
