### ISSUE TITLE
Impossible de naviguer d'un article à un autre sur la zep12

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#313]
Actuellement en prod, lorsqu'on arrive au bout de la lecture d'un article, on a deux lien en dessous qui nous indique l'article suivant, et l'article précédent.

Avec la ZEP-12 cette fonctionnalité a disparu. C'est voulu ?

**Comment by pierre-24** [comment]
Euuuh ... Non, c'est juste que j'y avais jamais fait plus attention que ça. Ceci étant dit, est-ce vraiment utile ?
