### ISSUE TITLE
Mauvais compte sur la page d'acceuil

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#315]
La page d'acceuil sur la zep12 affiche "Il y a 107 tutoriels sur Zeste de Savoir.". Le problème c'est qu'elle compte à la fois les tutoriels et articles ici.

Donc on a un bug.

**Comment by pierre-24** [comment]
D'une part, si tu te base sur la bêta, elle note "196", ce qui est effectivement un bug déjà réglé (mais on est plus du tout _iso_ avec la branche de la ZEP-12 sur la bêta, au secours @sandhose).

D'autre part ... [non](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/pages/utils.py#L48) :)

**Comment by firm1** [comment]
Je me basais bien sur la beta, mais vu que c'est réglé .. ok
