### ISSUE TITLE
Sécurité : il est possible de consulter les tutoriels en rédaction d'un auteur

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#317]
En allant sur l'url : https://beta.zestedesavoir.com/contenus/tutoriels/2/

J'arrive a visualiser la liste des contenus de ShigeruM publié et non publiés. J'ignore si c'est parce que j'ai des droits admin, mais quoiqu'il en soit, en prod on ne peut pas faire ça.

Un auteur ne veut pas forcément que l'on voit tous les tutos qu'il a en cours de rédaction.

**Comment by pierre-24** [comment]
C'est effectivement parce que tu as les droits admin. C'est _iso_-prod, de ce que je peux en voir en local, à moins que je me trompe.

**Comment by firm1** [comment]
En prod je ne peux pas faire cette magie :)

Le jeu. 27 août 2015 19:43, Pierre Beaujean notifications@github.com a
écrit :

**Comment by artragis** [comment]
effectivement, c'est pas isoprod. On a tellement rationalisé les choses qu'on a ajouté cette possibilité qu'il faudrait enlever.
