### ISSUE TITLE
L'importation ne gère pas l'import d'archive d'image

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#32]
Nous ne savons pas encore importer une archive d'image comme on le faisait dans l'ancien module. Nous ne gérons pour l'instant que l'import d'une archive ZIP avec le markdown à l'intérieur.

**Comment by artragis** [comment]
@firm1 tu penses que tu auras le temps ou pas?

**Comment by firm1** [comment]
Ce dont je suis sur c'est que je ne peux pas m'y coller avant au moins deux semaines. Si c'est pressé, ne m'attendez surtout pas, c'est le genre de truc pour lequel il faut que je me mobilise au moins 2 heures devant mon pc, c'est pas trop possible en ce moment.

**Comment by artragis** [comment]
Merci d'avoir prévenu.
Je ne pense pas avoir le temps de le faire avant ça donc à mon humble avis
on t'attendra.
De toute façon vue le nombre de rebase à faire avant que je puisse faire la
PR sur le dépôt officiel, je dirais que mes semaines vont être pas mal
occupées.

**Comment by artragis** [comment]
suport expérimental ajouté.

**Comment by pierre-24** [comment]
Ça m'as pas l'air déconnant :)

Faudra juste bien penser à noter ça quelque part dans la doc. Et d'utiliser la fonction magique qui change les SVG en PNG (parce que à priori, Pillow aime pas les SVG :) )

**Comment by artragis** [comment]
l'import des SVG n'est pas supporté et ne doit pas l'être.

**Comment by pierre-24** [comment]
ok :)

**Comment by pierre-24** [comment]
Il manque le champ en question:

![screenshot from 2015-05-23 20 13 56](https://cloud.githubusercontent.com/assets/7889675/7786169/4626393a-0188-11e5-9b89-f8beea57f6f2.png)

Par ailleurs, la même option n'est pas possible quand on fait "importer un nouveau contenu", uniquement quand on veut le mettre à jour :)

**Comment by artragis** [comment]
oui, j'ai oublié de mettre à jour ce qui gère le CreateFromArchive.

**Comment by artragis** [comment]
je viens de corriger ces deux erreurs.

**Comment by artragis** [comment]
Il semblerait que l'erreur soit toujours présente (pas de deuxième champ affiché), si quelqu'un peut s'en occuper svp.

**Comment by pierre-24** [comment]
Je me l'assigne pour pas oublier :)

**Comment by pierre-24** [comment]
Bon, voilà, y'a plus qu'à attendre l'avis de Travis. Mais avant de merger, petite question: est ce que le préfixe `archive:` aurait pas plus de sens que `image:` ? Comme ça, on comprend instinctivement que les fichiers proviennent de l'archive, non ?

**Comment by artragis** [comment]
pas faux. je dirais que ça serait bien que ce préfix soit paramétrable 
pour que spacefox choisisse en fonction de l'existant.

**Comment by pierre-24** [comment]
J'vais tenter ça :)

**Comment by pierre-24** [comment]
Voilà, c'est fait. Comme ça, si on change d'avis, on peut toujours le changer ;)

**Comment by artragis** [comment]
Rapport de QA:

Scénario:

un tuto tout neuf envoyé avec ce manifeste:

``` json
{
    "object": "container", 
    "slug": "asynchrone-net", 
    "title": "L'asynchrone et le multithread en .NET", 
    "introduction": "introduction.md", 
    "conclusion": "conclusion.md", 
    "children": [
        {
            "object": "extract",
            "slug": "await-async-un-couple-inseparable",
            "title": "await/async, un couple inséparable",
            "text": "await-async-un-couple-inseparable.md"
        }
    ], 
    "version": 2, 
    "description": "async et await sont vos amis.", 
    "type": "TUTORIAL", 
    "licence": "CC-BY-SA"
}
```

Dans l'intro, on trouve : 

``` markdown
En informatique, il existe un besoin constant dans les programmes : la performance. Plus précisemment, le but
est d'accomplir le plus rapidement possible une liste de tâches.

Très souvent, les performances sont apportées par un algorithme de meilleure qualité. Mais il n'est pas rare que
l'engorgement subsiste. Certains vous encourageront alors à passer à des "langages performant" tels que le C++.

Ce comportement n'est pas forcément adapté à votre besoin, développer dans ces langages peut, parfois, s'avérer
très complexe. En plus changer de technologie, c'est long.

Alors, continuez à utiliser C# ! VOus n'aurez pas besoin d'un doctorat en programmation système pour rendre vos
programmes performant. C# possède plein d'outils qui vous permettront d'optimiser tout ça **simplement**.

Avant tout, je vous propose de vous poser trois questions :

- Combien de temps mon programme passe-t-il à attendre?
- Y a-t-il plusieurs traitements que je puisse faire en parallèle?
- Mon programme utilise-t-il aux mieux les ressources de l'ordinateur (exemple : un processeur multicoeur)?

Vous vous rendrez vite compte qu'en informatique, on peut tout à fait faire un bébé en un mois du moment qu'on a 10 femmes,
et que cela est rendu possible par les technique d'asynchronisme.

![netlogo](archive:net-logo.jpg)

```

dans une archive .zip avec à l'intérieur un image net-logo.png

Voici ce que j'obtiens : 
- le tuto est créé
- la gallerie est créée
- l'image net-logo a été envoyée
- **MAIS** dans mon introduction (/contenus/editer/295/lasynchrone-et-le-multithread-en-net/ sur mon site) on a encore le archive:net-logo.jpg et donc l'image n'apparait pas.

Notons aussi que j'avais fait exprêt de mettre un cas d'erreur (un manifest mal foutu) et le truc m'a donné une erreur super compréhensible, bravo !

**Comment by artragis** [comment]
J'ai identifié le bug, je m'en occupe.

**Comment by artragis** [comment]
et du coup ça marche.
Je peux pas supprimer le "needqa" comme j'ai touché au code. Mais bon là c'est tout comme. Si @Vayel, @firm1 ou autre ont la volonté pour faire un import et nous dire quoi.

**Comment by Vayel** [comment]
J'ai importé une archive tout court et ça fonctionne. Mais c'est quoi cette histoire d'images ? C'est pour créer la galerie ? Comment génère-t-on l'archive ?

**Comment by artragis** [comment]
En fait maintenant tu peux importer un tuto et les images qui vont avec.
Il suffit pour ça de mettre dans le tuto les images avec ce code `![légende](archive:nom_de_l_image.ext)` puis donner un second .zip lors de l'importation qui contient toutes les images.

**Comment by Vayel** [comment]
J'ai bien mes images dans la galerie, mais les url dans le tutoriel n'ont pas changé.

**Comment by artragis** [comment]
quel texte as-tu mis?

2015-07-06 14:38 GMT+02:00 Vincent notifications@github.com:

**Comment by Vayel** [comment]
```
![Miaou](archive:tigre.jpg)
```

C'est là (user) : http://zds.francoisdambrine.me/contenus/300/qa32tuto-1/

Au passage, il s'est passé cela : 
- Création qa32tuto
- Exportation qa32tuto
- Création archive images
- Importation qa32tuto + images
- Création **deuxième** qa32tuto et galerie qa32tuto

**Comment by artragis** [comment]
On rit?
http://zds.francoisdambrine.me/contenus/301/qa32tuto-2/

comment as-tu créé ton archive? Quelle est sa structure?

**Comment by Vayel** [comment]
J'ai mis mes images dans un même dossier puis : `zip -r nom_archive dossier/`.

Par contre, il faudra qu'on parle de ça : 

> Création d'un deuxième qa32tuto et d'une galerie qa32tuto

Ici ou dans une autre issue ?

**Comment by artragis** [comment]
Ok, essaie de faire ça "à la main" en sélectionnant toutes les images puis
click droit, compresser.

2015-07-06 15:24 GMT+02:00 Vincent notifications@github.com:

**Comment by Vayel** [comment]
J'ai pas ça sous GNOME.

**Comment by artragis** [comment]
ou à l'inverse, ajoute le nom du dossier dans les :[](archive:)

**Comment by artragis** [comment]
Donc au lieu de "archive:tigre.png" mets "archive:nom_du_dossier/tigre.png".

**Comment by Vayel** [comment]
Ca va tout de suite mieux. :P

**Comment by artragis** [comment]
On peut fermer?

2015-07-06 15:37 GMT+02:00 Vincent notifications@github.com:

**Comment by Vayel** [comment]
Oui.

Par contre, les SVG ne sont pas gérés. C'est normal ?

**Comment by artragis** [comment]
as usual. on ne les a jamais géré.

**Comment by pierre-24** [comment]
Oui, les SVG, faudrait que ça soit géré par les galleries, donc c'est pas nos oignons ;)
