### ISSUE TITLE
Erreur 500 lorsqu'on importe un contenu dont le json est illisible

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#321]
Scénario : 
- Je vais sur un article, je télécharge le contenu
- J'ouvre le manifest.json et je l'enregistre. Mon éditeur (bloc note) l'enregistre en forçant en utf-8 (avant il était en ANSI as UTF-8)
- Je ferme et je zippe tout
- Je tente une nouvelle importation

=> boum : **500**
- Visiblement le code n'arrive pas à lire le fichier au format utf-8
- Au lieu de donner un message explicite il crashe juste une 500

**Comment by pierre-24** [comment]
Je hais python 2 :p
