### ISSUE TITLE
L'import d'un article ne fonctionne pas comme attendu

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#322]
Scénario:
- Je télécharge l'archive zip d'un tutoriel
- Je modifie le manifest.json comme ceci : 

avant

```
       {
            "object": "extract", 
            "slug": "le-continuous-delivery-quen-penser", 
            "title": "Le Continuous Delivery, qu'en penser ?\n", 
            "text": "le-continuous-delivery-quen-penser.md"
        }
```

après

```
       {
            "object": "extract", 
            "slug": "1-le-continuous-delivery-quen-penser", 
            "title": "Le Continuous Delivery, qu'en penser ?\n", 
            "text": "le-continuous-delivery-quen-penser.md"
        }
```

Dans l'optique de ne modifier que le slug.

Je me fait jeter à l'importation avec le message `Le fichier "1-le-continuous-delivery-quen-penser.md" n'existe pas dans l'archive.`

Le fichier est censé être l'attribut "text", et là j'ai l'impression qu'il pense que le fichier est l'attribut "slug" auquel on rajoute un "md" à la fin.

**Comment by pierre-24** [comment]
Alors, j'ai trouvé, c'est tout bête.

Par contre, avant de faire un commit, j'imagine que tu t'attend à ce que le slug reste celui là ? Parce que c'est pas le comportement par défaut, pour pas ce casser la tête sur l'unicité des _slugs_, on en redonne un d'office.

**Comment by firm1** [comment]
> Par contre, avant de faire un commit, j'imagine que tu t'attend à ce que le slug reste celui là ?

Oui.

> on en redonne un d'office.

si on a pas le choix, c'est tjours ça de pris.

**Comment by pierre-24** [comment]
Je vais voir ce que je peux faire. De toute façon, si le slug n'est pas unique, un nouveau sera redonné, mais je pense pouvoir faire en sorte que si c'est unique, le système le prenne.

**Comment by pierre-24** [comment]
Bon, désolé, ça ne marchera pas, ça casse tout.
