### ISSUE TITLE
On n'est pas prévenu lorsque l'on renseigne dans le manifest.json une licence qui n'existe pas

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#323]
Scénario : 
- Je télécharge une archive de contenu
- Je la dezippe et je modifie le manifest.json pour remplacer la licence existante par une licence qui n'est pas répertoriée sur zds
- J'importe mon contenu sur zds
- Zds importe bien le dit contenu avec la licence par défaut, mais aucun message ne me préviens que la licence que j'ai mis dans le manifest n'a pas été prise en compte.

**Comment by pierre-24** [comment]
Pas faux :)
