### ISSUE TITLE
Problème d'affichage des +1/-1 dans les commentaires d'un article

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#325]
Le problème est simple, lorsque j'ai voté pour un commentaire le pouce est censé être coloré. Ce n'est pas le cas actuellement avec la zep-12, le pouce se colore au moment du clic, mais à l'actualisation, il est de nouveau grisé.

Il suffit de regarder comment ça marche dans les forums pour voir comment ça devrait fonctionner.

**Comment by pierre-24** [comment]
@artragis : un effet pervers de l'optimisation ?

**Comment by artragis** [comment]
bon j'en ai mare de ça. ça fait trois fois que je le corrige et que c'est validé à chaque fois. Il serait de bon ton d'arrêter de changer les choses là.

J'y regarderai plus tard. J'ai casiment un après midi complet mercredi prochain.

**Comment by pierre-24** [comment]
Ben surtout que j'ai pas trop l'impression qu'on chipote à quelque chose dans ce coin là o_O

**Comment by artragis** [comment]
oui et c'est ça qui me soule. à tout les coups j'ai fait une merde sans le voir. en attendant je confirme le bug.
