### ISSUE TITLE
[TEST]Faire un benchmark

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#33]
Histoire de voir si on n'a pas créer de nouveau bottleneck.

**Comment by pierre-24** [comment]
Très intéressant. Mais je n'ai aucune idée de comment on fait ça ^^

**Comment by Eskimon** [comment]
ping @SpaceFox , il aura ptet une idee ayant benchmarke le site a une epoque (ou @firm1 ?)

**Comment by SpaceFox** [comment]
jMeter, à faire sur la préprod après avoir déployé le bon tag et mis à jour la base et les tutos.

Y'a un début ici : https://github.com/zestedesavoir/zds-site/tree/tests-charge/tests/jMeter (mais ça ne teste pas assez large)

**Comment by Eskimon** [comment]
C'est complique a mettre en oeuvre ? Car @artragis a son serveur perso il me semble (et donc pourrait le faire en avance de phase s'il veut jouer avec ca)

**Comment by SpaceFox** [comment]
PS : Idéalement, il faut faire d'abord un test avec la version actuelle pour avoir un point de comparaison fiable.

C'est pas super simple à mettre en place par contre, surtout si on veut faire évoluer le script pour avoir des résultats fiables.

**Comment by artragis** [comment]
j'essaierai de voir ce que je peux faire, pour l'instant priorité aux TU.

**Comment by artragis** [comment]
Etant donné la difficulté d'avoir un truc fiable en terme de mesure et en sachant que nous avons déjà quelques indicateurs sur certaines pages qui tendent à montrer qu'on a tout ce qu'il faut en terme d'appel de perf, je ferme pour que ça ne pollue pas le dashboard.

**Comment by pierre-24** [comment]
Je suis d'accord. Au pire, on le fera durant la PR.
