### ISSUE TITLE
Impossible de rajouter 2 auteurs à un tutoriel

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#334]
Serveur : Bêta
Version : zep-12/f5637af
Système : OS X
Navigateur : Chrome

---

Scénario :
- Rendez-vous sur un tutoriel non publié (pas testé avec un tuto publié).
- Cliquez sur "Ajouter un auteur"
- Commencez à taper les premières lettres d'un pseudo.
- Sans cliquer sur le tuto voulu, cliquez sur enter pour sélectionner le premier tuto.
- Renseignez un second pseudo en séparant les 2 pseudos avec une virgule (aucune auto completion pour le second pseudo, tapez le jusqu'à la fin).
- Cliquez sur "Ajouter" et constatez l'erreur.

**Comment by pierre-24** [comment]
Bug du SMTP de la bêta, je ferme :)
