### ISSUE TITLE
Le contenu du sitemap.xml est erroné

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#336]
Lien incriminé : http://beta.zestedesavoir.com/sitemap-tutos.xml

Les dates de dernière modifications sont identiques quelques soit le tutoriel (le 30 aout) et pourtant les tutoriels n'ont pas bougé depuis longtemps.

ça a donc un impact négatif coté SEO car on fait croire à Google que tous nos tutoriel on été mis à jour ce qui n'est pas le cas.

**Comment by pierre-24** [comment]
Oui, alors ça, c'est un "bug" (ou pas) qui va être un peu pénible à gérer: les tutos sont effectivement tous mis à jours par la ZEP-12 (et en particulier le processus de migration). Techniquement, le sitemap ne ment pas, puisqu'on met à jour la `update_date`. De plus, toutes les adresses changent (oui, c'est bien les dernières en date qui sont employées, et pas les anciennes, t'imagine le bordel pour gérer ça ?).

D'un autre côté, tu as raison. N'étant pas spécialiste en SEO, je te laisse me dire ce que tu en pense.

**Comment by pierre-24** [comment]
(à noter que dans certains cas, c'est même bénéfique, puisqu'on corrige par exemple des erreurs dans les tutos importés à l'époque par l'importateur de .tuto, dixit les pavés dans #267)

**Comment by firm1** [comment]
> les tutos sont effectivement tous mis à jours par la ZEP-12 (et en particulier le processus de migration)

Il me semblait que le contenu n'était pas modifié par la migration de la zep 12. Le contenu que détectera Google avant et après le passage de la zep-12 sera a 99% le même.

La date de modification est là pour notifier d'une mise à jour de contenu et non d'une mise à jour de l'url. D'ailleurs la redirection permanente entre les anciennes et les nouvelles urls font que l'on ne peut pas vraiment dire que les adresses ont bougé.

J'aurai tendance a dire qu'il faut conserver les anciennes dates d'un point de vue SEO

**Comment by pierre-24** [comment]
Bon, le plus simple à faire pour ne pas trop ce casser la tête, c'est alors de mentir et de ne pas mettre à jour `update_date`, comme ça le sitemap reste plus ou moins celui de l'ancienne version (sinon, ça va être un bordel monstre à gérer)

Au delà de ça, je trouve l'argument des 99% assez bizarre: il arrive souvent que les validateurs corrige des fautes d'orthographes très rapidement, en passant ça en "correction mineure", ce qui a pour impact de changer le sitemap (dixit code actuel). L'impact de cette pratique me semble exactement le même o_O

**Comment by firm1** [comment]
> Au delà de ça, je trouve l'argument des 99% assez bizarre: il arrive souvent que les validateurs corrige des fautes d'orthographes très rapidement, en passant ça en "correction mineure", ce qui a pour impact de changer le sitemap (dixit code actuel)

Mon avis est que les corrections mineures ne devraient pas provoquer de mise à jour du sitemap. si le code actuel fait ça, j'aurai tendance a dire que c'est un bug.

**Comment by pierre-24** [comment]
[et bien il le fait](https://github.com/zestedesavoir/zds-site/blob/dev/zds/urls.py#L26) :)

**Comment by firm1** [comment]
C'est donc un bug :)

**Comment by artragis** [comment]
mais pas dans la zep12. Je ferme. Met ce bug sur le bug tracker de zds et explique que c'est un bug et non une évol.
