### ISSUE TITLE
La création de contenu en v2 fait appel à la page d'aide de la v1

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#337]
Url incriminée : http://beta.zestedesavoir.com/contenus/nouveau-tutoriel/

On a le message suivant : "Si vous avez besoin d'un coup de main,sélectionnez une ou plusieurs catégories d'aide ci-dessous et votre tutoriel apparaîtra alors sur [la page d'aide](http://beta.zestedesavoir.com/oldtutoriels/aides/)."

On voit bien le lien qui pointe sur `http://beta.zestedesavoir.com/oldtutoriels/aides/`

C'est pas bon du tout si on veut planquer les vieilles urls.

**Comment by artragis** [comment]
c'est surtout que c'est un bug :p on s'en occupe.
