### ISSUE TITLE
La création de tutoriel accepte des images un peu trop grosses

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#338]
Lorsque j'essaye de créer du contenu, j'ai un truc pas cohérent. On me dit ceci "Sélectionnez le logo du tutoriel (max. 1024 Ko)."

Par contre, lorsque j'edite mon tutoriel, je renseigne une image de 1.24 Mo et l'outil l'accepte alors qu'il ne devrait pas.

**Comment by artragis** [comment]
@pierre-24

**Comment by pierre-24** [comment]
J'imagine qu'il manque une condition quelque part ^^

**Comment by pierre-24** [comment]
À noter que le bug est _isoprod_ (je viens de tester, pas de condition en prod' non plus), donc je le fais parce que c'est chiant sinon.
