### ISSUE TITLE
La page d'aide des auteurs a perdu son coté responsive

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#339]
Sur mobile on retrouve encore des precedents/suivants sur la pagination au lieu des simples fleches.
## Screen prod :

![screenshot_2015-08-31-12-33-53](https://cloud.githubusercontent.com/assets/6066015/9576962/3d89fc28-4fdd-11e5-8653-af5b1f3254ed.png)
## Screen zep12

![31 aout 2015 123513 gmt 0200](https://cloud.githubusercontent.com/assets/6066015/9576972/587a5f0a-4fdd-11e5-89c1-b9ea5747ea08.jpg)

**Comment by pierre-24** [comment]
@situphen et @sandhose : ou ce qu'on c'est planté ?

**Comment by Situphen** [comment]
@pierre-24 : c'est pas vous c'est un bug connu depuis longtemps !

**Comment by artragis** [comment]
Le bug est apparu quand on est passé de [misc/pagination.part.html](https://github.com/zestedesavoir/zds-site/blob/dev/templates/tutorial/tutorial/help.html#L27) à [misc/paginator.html](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorialv2/view/help.html#L49).

**Comment by Situphen** [comment]
Je fais une PR sur upstream comme ce n'est pas lié à cette ZEP.

**Comment by artragis** [comment]
Du coup je ferme ici puisqu'on peut considérer que c'est un bug de l'upstream.

**Comment by pierre-24** [comment]
Toutafé. D'ailleurs, techniquement, tant que notre PR est mergable, on est même pas tenu de faire un rebase :)
