### ISSUE TITLE
Les dates dans les pdf sont en anglais

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#341]
En téléchargeant le pdf suivant : https://beta.zestedesavoir.com/articles/pdf/142/essai.pdf

J'ai remarqué que la date est en anglais, alors que le site est francophone.

Bug donc.

**Comment by pierre-24** [comment]
Bon, c'est partout pareil. Hors ça peut pas être nous, [c'est un _templatetag_ qui gère ça](https://raw.githubusercontent.com/artragis/zds-site/zep_12_double_stack/templates/tutorialv2/export/content.md). Du coup, on a "juste" un problème de langue. _any suggestions_ ?

**Comment by pierre-24** [comment]
Je dirais même plus: j'ai pas le bug en local !?!

**Comment by pierre-24** [comment]
J'ai validé un tuto et [la date est en français](https://beta.zestedesavoir.com/tutoriels/pdf/181/tp-la-pierre-de-lait.pdf). Est ce que ça viendrait pas de l'emploi de l'outil de migration, qui serait lié au fait que la _locale_ soit alors reconnue comme anglaise à ce moment là ?

**Comment by pierre-24** [comment]
Bon, pour avancer. Sur la bêta, quand @sandhose fait un `generate_pdf`, la date est aussi en anglais.

**Comment by artragis** [comment]
Ok, il y a donc un problème de locale quand on utilise le virtualenv.

**Comment by pierre-24** [comment]
Ah, bien vu pour le virtualenv, j'avais pas pensé à lui demander.

**Comment by DevHugo** [comment]
On en est ou ? j’investigue ou c'était le coup du virtualenv ?

**Comment by artragis** [comment]
Tu peux investiguer, le virtualenv de pierre lui donne une date en 
français donc ce n'est pas ça.

**Comment by DevHugo** [comment]
Je promet rien mais je regarde.

**Comment by DevHugo** [comment]
On avance, je commence à avoir une idée du pourquoi, les faits sont les suivants:
- Si on republie le tutoriel aprés la migration, c'est bon !
- Si on regarde à l'intérrieur du fichier .md qui sert à la génération du pdf, on a la date en anglais. Exemple: 

``` md
% LA LATÉRALISATION CÉRÉBRALE 
% admin
% 13 september 2015

# Introduction
```

Donc ça vient de la migration, on peut le nier. Je pense que la date de publication n'est pas mise à jours ou/et n'est pas correcte pendant la migration. Je pense à une histoire de cast ou de truc comme [ça](https://docs.djangoproject.com/en/dev/ref/settings/#std:setting-USE_L10N).

**Comment by DevHugo** [comment]
Donc si on fait dans une commande Django, 

```
print render_to_string('test.html', {'test': datetime.now()})
```

et que dans le templates, on a 

``` html
% {{ test|date:"d F Y" }}
```

la date sera renvoyé en anglais.

Reste plus qu'a comprendre comment on peut faire pour la faire apparaître en français !

PS: Un bon conseil utiliser le code suivant dans la fonction generate_pdf pour tester 

```
print "Test:"
print render_to_string('test.html', {'test': datetime.now(), 'LANGUAGE_CODE':'fr-fr'})
```

avec le template suivant: 

```
{% load i18n %}

{{ test|date:"d F Y" }}
```

**Comment by DevHugo** [comment]
J'ai trouvé comment faire mais j'ai pas complétement testé tous les cas, voila [le diff qui permettrait de résoudre le souci](https://github.com/zestedesavoir/zds-site/commit/da0c4599123a1b2e27ad0d5c7af23ece61d89800). 

J'ai pas le temps de faire des tests qu'il faidrait. Pour tester correctement, il faudrait refaire une migration complète et tester que ça marche quand on publie post zep12. On n'a pas besoin de faire ça en beta, en local, ça suffit.
J'ai pas le temps de faire la PR non plus sur le dépôt principal. Si quelqu'un veut reprendre le diff, allez y. Je laisse le diff sous licence WTFPL - Do What the Fuck You Want to Public License.  

@artragis @pierre-24

**Comment by DevHugo** [comment]
J'ai fait la PR, finalement. J'ai besoin d'une QA, de manière assez urgente car il faudrait pas que ça passe après la migration.

@pierre-24 @artragis

**Comment by DevHugo** [comment]
Je confirme que c'est bon, on ferme.

**Comment by pierre-24** [comment]
C'est parti :)
