### ISSUE TITLE
Petit souci d'affichage dans le formulaire d'edition d'un message sur mobile

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#342]
Comme on peut le voir sur le screen les bouton Envoyer/Apercu son affichés un peu en decalé.

![screenshot_2015-08-31-13-32-17](https://cloud.githubusercontent.com/assets/6066015/9577866/7f2cf6e6-4fe5-11e5-894a-aa18d6bf1fc0.png)

**Comment by pierre-24** [comment]
mmmh, une fois encore, @situphen ? (désolé de t'invoquer comme ça, mais moi et le front, ça fait 42)

**Comment by Situphen** [comment]
@firm1 : ~~Comment tu as fait pour trouver ce bug ? Je n'arrive pas à le reproduire !~~ C'est lors de l'édition d'un message.

**Comment by pierre-24** [comment]
Certes, et ... Je dois faire quoi ?

**Comment by Situphen** [comment]
Ce n'est pas dû à cette ZEP, mais à ma PR https://github.com/zestedesavoir/zds-site/pull/2916.

**Comment by Situphen** [comment]
Plus précisément, c'est parce que vous vous basez sur une autre _template_ qu'avant et qu'il y a une classe `article-content`. Mais je vais faire une PR sur votre dépôt (demain soir sûrement) pour changer le SCSS ajouté via https://github.com/zestedesavoir/zds-site/pull/2916 car il est trop permissif  !

**Comment by artragis** [comment]
on en est où là?
