### ISSUE TITLE
Impossible de poster un commentaire si le JS est désactivé

### ISSUE THREAD

**Issue by Situphen** [artragis/zds-site#343]
Pour reproduire le bug, désactivez le JS. Il y a deux cas possibles :
- soit vous avez écrit quelque chose dans le textarea, et quand vous appuyez sur "Aperçu", le message est posté
- soit le textarea est vide et dans ce cas là on arrive sur une page avec deux messages d'erreurs
  ![capture d'écran](https://i.gyazo.com/cb3c2e4a30d33318a2288272cf5250cc.png)

**Comment by artragis** [comment]
hum. encore un casse tête. Par contre celui-là est hyper important.

**Comment by pierre-24** [comment]
Mmmmh, non, pas tellement. "Apercu" est bien un bouton, il faut donc aller vérifier si ce bouton est bien dans `POST` et agir en conséquent. [C'est ce qui est fait pré-ZEP-12](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorial/views.py#L3647).
