### ISSUE TITLE
Un membre du staff ne peut pas ajouter un conteneur à un tutoriel

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#344]
Aujourd'hui en prod, les membres du staff on la possibilité de modifier un tutoriel sans forcément en être les auteurs.

Avec la zep-12 ce n'est plus possible. Le staff voit bien le lien "Ajouter partie", "Ajouter chapitre", etc. Mais en cliquant dessus on se tape une 403. c'est pô juste.

**Comment by pierre-24** [comment]
Attention que je sais pas si notre ami @sandhose a fait la manip qui va bien sur la bêta pour te le permettre (mettre les bons droits). Si tu n'as pas la validation dans le menu, c'est que la manip' n'as pas été faite et que donc le bug est à confirmer à postériori. 

Mais comme tu es super-user sur la bêta, tu peux le faire, non ? ([voir fin du fichier update.md](https://github.com/artragis/zds-site/blob/zep_12_double_stack/update.md#zep-12-aka-apocalypse))

**Comment by firm1** [comment]
le super user a par défaut tous les droits. La preuve en est que je vois bien le fameux menu de validation et j'arrive a valider, mais je ne peux pas faire d'ajout de conteneur à un contenu qui ne m'appartient pas.

**Comment by pierre-24** [comment]
Je confirme effectivement le bug, voilà qui est très étrange (on a du oublier un `authorized_for_staff=True` quelque part, ça va probablement prendre 30 secondes à corriger)

**Comment by pierre-24** [comment]
Tient, HS: si tu es super-user, est ce que tu pourrais valider le tuto C de Taurre et cie ? On a un truc à confirmer sur celui là. J'espère juste que la validation ne va pas se vautrer à cause du PDF.

**Comment by firm1** [comment]
La version en validation de ce tuto date du "19/04/15", je ne pense pas que c'est sur celui là que tu souhaites réaliser tes tests

**Comment by pierre-24** [comment]
Je ne sais pas quand date celle qui pose problème en prod, mais à priori,  j'ai envie de dire que si. Je demanderai à Taurre de quoi il retourne quand ce sera validé.

**Comment by artragis** [comment]
fixed
