### ISSUE TITLE
Perte de place lors de la visualisation d'une partie d'un big tuto

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#345]
On perd de la place avec l'affichage des parties depuis la zep12 comme peut le montrer les screens suivants : 
## En prod

![part-view-prod](https://cloud.githubusercontent.com/assets/6066015/9578756/f0fbded4-4fec-11e5-9b94-28d321b339de.PNG)
## Zep-12

![part-view-beta](https://cloud.githubusercontent.com/assets/6066015/9578759/f53b5344-4fec-11e5-94e3-5d088cd99baf.PNG)

**Comment by pierre-24** [comment]
Ah, oui, tient, j'avais jamais titlé que les parties s'affichent aussi en mode comme ça.

**Comment by pierre-24** [comment]
Par contre, je ne le ferait pas en navigation mode "édition", parce que sinon, on a plus les boutons de déplacement et d'édition.
