### ISSUE TITLE
Le style des citations sourcées dans les contenus n'est pas cohérent avec le reste

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#346]
La source d'une citation est toujours en italique à l'affichage sur tout le site. Avec la ZEP-12 on n'a plus cet italique dans les tutoriels, et on perd donc un peu de cohérence de style.
## La vue en prod

![view-prod](https://cloud.githubusercontent.com/assets/6066015/9578853/aa6e8966-4fed-11e5-8d75-d20c658a510a.PNG)
## La vue de la zep12

![view-beta](https://cloud.githubusercontent.com/assets/6066015/9578856/b82931a0-4fed-11e5-8f7c-725b70168bf7.PNG)

**Comment by pierre-24** [comment]
Style, @situphen et @sandhose ^^

**Comment by Situphen** [comment]
Ça vient du Markdown je pense car le HTML diffère entre les deux !

https://beta.zestedesavoir.com/tutoriels/473/une-introduction-a-ruby/497_les-bases/2487_introduction/
https://zestedesavoir.com/tutoriels/373/une-introduction-a-ruby/497/les-bases/2487/introduction/

**Comment by pierre-24** [comment]
ah. Techniquement, on ré-invente pas la roue et on se base sur `emarkdown`, est ce qu'il y aurait eu des modifs récement ?

**Comment by pierre-24** [comment]
En fait, le problème est un non-problème:

![screenshot from 2015-09-03 16 26 09](https://cloud.githubusercontent.com/assets/7889675/9660971/cbcefb0a-5258-11e5-89c6-b0de4fa1488c.png)

Comme on peut le voir, le code diffère --"
