### ISSUE TITLE
Gestion de l'ancienne version du parser

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#35]
- Pause de problèmes de simplicité
- Pause d'éventuels problèmes de perf
- Pause des problèmes avec les béta
- Pause des problèmes avec les "revert" de git

Un petit résumer ici ; http://zestedesavoir.com/forums/sujet/2826/zep-12-de-la-perenite-de-nos-anciens-historiques-et-du-reste/

**Comment by pierre-24** [comment]
Les perfs, j'ai envie de dire "tant pis", pour la simple et bonne raison que ce cas n’apparaîtra que dans deux cas: visualisation de l'historique (et c'est le problème de l'auteur) et import d'un tuto v1.0 (et on peut même interdire ça, mais dans l'absolu c'est possible). 

D'ailleurs, ce genre d'argument tient pour le reste: puisqu'on migre tout (!), les problèmes n’apparaîtrons que pour des auteurs dans des cas très précis et pas critiques. Je serais d'avis de continuer là dessus: on implémente un machin minimal et on écris quelque part que c'est un _failback_ et que si ça fonctionne pas dans certains cas, tant pis.

Et tu peux me l'assigner, parce que ça fait des semaines que j'ai envie de l'écrire, ce morceau de code là (bon, je vais quand même priorétiser la publication avant, sauf si ça te bloque pour la migration).

**Comment by pierre-24** [comment]
L'habitude, j'ai oublié que je pouvais me l'assigner moi-même, ici ^^

**Comment by pierre-24** [comment]
Géré par #68. On peut éventuelement s'amuser à couvrir ça par un TU, mais il disparaitra en même temps que les modules tuto/articles.

**Comment by artragis** [comment]
Bon comme c'est une issue "globale" et sans scénario de QA et que depuis le temps les tests ont été concluant, je clos.

**Comment by pierre-24** [comment]
Il faudra juste s'en souvenir le jour ou on tentera la migration de contenus existant et qu'on visitera l'historique :)

**Comment by artragis** [comment]
la migration... plus j'y pense, plus j'ai peur à cause des trois versions :
draft/beta/public.

Quoi que... est-ce que lorsque tu fais une MEP tu supportes la vieille
version du manifeste?

**Comment by pierre-24** [comment]
Vu l'endroit ou le support est implémenté (à la lecture du manifest), je supporte l'ancien manifest **partout**. Ceci étant dit, vu la manière dont le processus de MEP a été réimplémenté, on ne coupera pas à une re-MEP de tout les contenus (avec la 301 qui va bien pour rediriger les anciennes adresses vers les nouvelles). Du coup, voici comment j'imagine le processsus de migration :

[pour chaque `tuto` dans tutos v1]
- Copie complète du dossier (avec l'historique et tout le bazar)
- Migration du manifest et _commit_ (comme ça, on s'assure que toutes les versions brouillons sont en v2, même si l'historique ne l'es pas)
- Créer un objet `PublishableContent`, ratacher la gallerie, les catégories, la licence et les auteurs (et ce que j'ai oublié)
- Migrer le topic bêta si nécéssaire: le ratacher à l'objet du point précédent et mettre à jour le premier message en mettant un gros **attention, le lien à changé** (il est important de conserver ce que contient ce message, les auteurs se sont pleins). Je pense aussi qu'on devrait systématiquement publier un message dans le topic pour dire la même chose (avec le bot)
- Si publié, tout d'abord créer un `PublishedContent` avec `content_pk` et `current_content_slug` qui pointent sur les anciennes infos, mais sur le bon `PublishableContent`. Puis faire une MEP (pas le choix, ne serait-ce que pour PDF et consœurs), qui va remettre les bonnes infos au bon endroit (à vérifier, mais je pense que dans `publish_content`, le `PublishedContent` déjà existant est récupéré sur base du `PublishableContent` et non du pk ou slug, si c'est pas le cas, on change ça). Comme ça, si un visiteur appelle un ancien tuto, il va normalement tomber sur le premier `PublishedContent`, et si j'ai bien pensé le truc, la 301 va se mettre en place d'elle-même. Hop là ;)
- Migrer les commentaires et tenter le plus possible de ré-abonner les commentateurs aux nouveaux contenus (quoique c'est peut être automatique). Par contre, si il y avait moyen d'éviter l'effet inverse, à savoir que les commentateurs se mange des notifs, ça serait sympa.
- Je pense que j'ai rien oublié.

Puis faire de même pour les articles: c'est presque pareil, mais les noms du modèle sont pas exactement les mêmes ;) (et y'a pas de bêta)

**Comment by artragis** [comment]
> PublishedContent, et si j'ai bien pensé le truc, la 301 va se mettre en place d'elle-même. Hop là ;)

Actuellement, je pensais faire ça : (pour les articles)

``` python
        if current.sha_public is not None and current.sha_public != "":
            publish_content(exported, exported.load_version(current.sha_public), False)
            exported.pubdate = current.pudate
            exported.sha_public = current.sha_public
            exported.save()
            exported.public_version.content_public_slug = current.slug
            exported.public_version.publication_date = current.pubdate
            exported.public_version.save()
```

ce qui devrait suffire non? il ne devrait pas y avoir de redirection autre que le "RedirectSEOView" et les différents trucs qu'on a dans les ContentView qui détectent des problèmes de slugs.

**Comment by pierre-24** [comment]
ça devrait le faire :)

Attention que `publish_content()` fait déjà les 3 dernières lignes.

Dans tout les cas, on verra très vite si ça fonctionne ou pas ^^

**Comment by artragis** [comment]
> Attention que publish_content() fait déjà les 3 dernières lignes.

non ! il met aujourd'hui comme date, alors que la date est vieille.

**Comment by pierre-24** [comment]
Aaaah, ok, j'avais pas compris ^^
