### ISSUE TITLE
Problème de formulation dans l'affichage d'un tutoriel

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#350]
En prod, sur un tutoriel publié, on peut lire la mention "Dernière mise à jour : lundi 18 août 2014 à 13h39 ", avec la Zep-12 on lit "Publié : dimanche 20 juillet 2014 à 10h18".

Il me semble que la première formulation avait été adopté pour mettre en avant le caractère à jour des tutoriel. Y a t-il une raison particulière qui a poussée a changer ce terme ?

**Comment by pierre-24** [comment]
Mmmh, j'imagine que ça a du nous échapper.
