### ISSUE TITLE
Editer un commentaire d'article/tutoriel ne permet de résoudre les alertes

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#351]
Actuellement en prod, lorsqu'un staff édite les commentaires des articles/tutoriels s'il y avait des alertes sur ces commentaires ceux ci sont automatiquement résolus.

Ce principe a été mis en place pour les cas ou un commentaire a plein d'alertes et qu'un modo a envie de tout résoudre d'un coup. La simple édition permet de faire de la résolution de masse.

On a donc une petite regression là.

**Comment by pierre-24** [comment]
Je te crois. Ceci étant dit, c'est un peu pénible ce genre de chose, parce que on ne le sais pas et que c'est documenté nul part (et que lire le code original n'est jamais très drôle).

**Comment by artragis** [comment]
en effet, je tiens à rappeler que nous avons fait la zep 12 avec une documentation qui disait "à venir".

On va tenter de le faire car c'set une régression mais on serait très heureux que tu prennes aussi ton éditeur de code pour régler les choses.
