### ISSUE TITLE
Impossible de savoir qui a édité un commentaire de tuto/article

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#352]
Dans les forums, quand on édite un message, voir à la suite de notre message la mention "Édité par firm1 il y a une seconde".

Quand on édite les commentaire d'un article, on ne voit que la mention "Édité il y a une seconde". On ne sait pas qui est l'auteur de l'édition.

C'est aussi une petite regression.

**Comment by pierre-24** [comment]
[vu que la condition existe](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorialv2/includes/reaction_message.part.html#L195), soit la requête manque du morceau `editor`, soit il y a une _typo_ quelque part.

**Comment by artragis** [comment]
As-tu édité ton propre commentaire ou bien le commentaire d'un autre?
