### ISSUE TITLE
Les urls de beta n'ont pas de redirections permanentes

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#353]
Les urls suivantes : 
- http://beta.zestedesavoir.com/contenus/beta/416/zes/
- http://beta.zestedesavoir.com/contenus/beta/416/bescherelle/
- http://beta.zestedesavoir.com/contenus/beta/416/babouin/
- http://beta.zestedesavoir.com/contenus/beta/416/coucou/

Renvoient toutes le même contenu. Il faudrait idéalement qu'elle redirigent (301) sur l'url associée au bon slug, au pire une 404 si c'est trop compliqué.

**Comment by pierre-24** [comment]
T'es bien conscient que ce que tu nous reproche là, c'est _iso_-prod et implémenté par toi même dans l'ancien code, quand même ?

**Comment by pierre-24** [comment]
([preuve](https://github.com/zestedesavoir/zds-site/blob/dev/zds/tutorial/views.py#L890))

**Comment by pierre-24** [comment]
[et que outre cela, c'est toi qui nous a demandé de rajouter ce comportement](https://github.com/artragis/zds-site/issues/305).

**Comment by firm1** [comment]
Je le sais bien (ça ne servait a rien de trop y toucher pendant vos travaux sur la zep).

Vous avez deja fait le boulot de redirection un peu partout, pourquoi laisser sur les urls de beta le bug ?

**Comment by pierre-24** [comment]
En fait, le pire, c'est qu'il n'y a pas de bug: [on passe bel et bien par une `RedirectView`](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_contents.py#L52), donc il y a bien redirection (à la limite, on pourrait faire en sorte qu'elle soit permanente, si c'est ça qui te dérange)

**Comment by pierre-24** [comment]
EDIT: [même qu'elle est permanente, en fait](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_contents.py#L56)

**Comment by firm1** [comment]
> et que outre cela, c'est toi qui nous a demandé de rajouter ce comportement

La demande etait de rajouter les redirections entre les urls de beta anciennes et les nouvelles. Les non-redirections actuelles ne sont pas top

**Comment by firm1** [comment]
> EDIT: même qu'elle est permanente, en fait

Comment ça se fait alors que lorsque je vais sur les urls sus-citées je ne suis pas redirigé sur l'url/slug originale (la vraie).

**Comment by pierre-24** [comment]
Mouais, effectivement, il y a un truc qui m'échappe.

**Comment by pierre-24** [comment]
Aaaah, ok, ça passe [par là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_contents.py#L209). Je déteste ça, sincèrement.

**Comment by artragis** [comment]
bon on va être clair OSEF/
Les urls de béta ne sont PAS référencée. En effet je rappelle que ces urls ne sont accessibles qu'aux connectés donc on a pris la décision de mettre le robot.txt à jour pour les béta il y a plusieurs mois sur la prod!

alors franchement 302/301 et autres joyeuseté OSEF. Tant que la redirection est faite pour que personne ne tombe dans une 404 alors que la page existe encore, rien ne doit être changé.

> Renvoient toutes le même contenu

c'est logique, elles ont toutes la même PK. Je mime le comprtement V1 qui osef du slug.
