### ISSUE TITLE
Mauvais libellé dans la sidebar mobile

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#354]
Sur la page d'aide des tutoriels et articles, dans la sidebar on a sur mobile le mauvais libellé (besoin au lieu de type) comme on peut le voir sur le screen.

![31 aout 2015 182357 gmt 0200](https://cloud.githubusercontent.com/assets/6066015/9583802/a45339da-500d-11e5-8ac7-f452500f2ef3.jpg)

**Comment by artragis** [comment]
@pierre-24
