### ISSUE TITLE
La licence par défaut n'est pas la bonne

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#357]
Il avait été décidé il fut un temps (et c'est le comportement en prod) que la licence par défaut lorsqu'on crée du contenu serait la licence "tout droit réservé" qui possède son id dans les settings.

Il souci c'est qu'avec la zep 12, ce n'est pas cette licence qui est sélectionnée par défaut lors de la création d'un contenu.

**Comment by pierre-24** [comment]
Je me perd un peu dans tout les commits et pour savoir ou on en est sur la bêta, mais j'ai remarqué ça il y a pas longtemps, et je l'ai corrigé dans la foulée (c'était avec #323). Du coup, je dirais à confirmer à la prochaine remise à niveau de la bêta.

**Comment by artragis** [comment]
Après vérification, non. On est en CC-BY. ou plus précisément, c'est la première licence du dropdown qui est utilisé.

**Comment by pierre-24** [comment]
Ok, bug confirmé, then.
