### ISSUE TITLE
Mauvaise compréhension du None par l'introduction/conclusion

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#358]
Scénario : 
- Je crée un article avec dans l'introduction le texte "None" et dans la conclusion le texte "None".
- Lorsque je visualise mon article il me dit "Il n'y a pas d'introduction." et "Il n'y a pas de conclusion."

Le comportement n'est pas normal

**Comment by pierre-24** [comment]
[Ça vient de là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorialv2/view/content.html#L110), ne me demande pas d'où sortent les guillemets.
