### ISSUE TITLE
Erreur 500 après création d'un article

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#360]
Scénario : 
- Je crée un article dont le titre est "&"
- Je vais ensuite consulter la liste des mes articles

pouf => **erreur 500**

**Comment by artragis** [comment]
@pierre-24 je pense qu'il faut ajouter une condition au formulaire style "si le slug est différent de rien ou -".

**Comment by pierre-24** [comment]
Je vais voir ce que je peux faire :)

**Comment by pierre-24** [comment]
Correction complète : `if slugify(title).replace('-', '').replace('_', '') == ''` !
