### ISSUE TITLE
Disparition de la barre jaune/orange dans la topbar en mode offline

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#361]
Lorsque je consulte mon tutoriel en mode hors ligne, normalement (en prod en tout cas), on a une barre jaune/orange qui vient souligner le terme "tutoriel" et qui nous indique visuellement que l'on est dans sur un tutoriel.

C'est dommage que cette fonctionnalité ait disparu avec la zep 12

**Comment by pierre-24** [comment]
> C'est dommage que cette fonctionnalité ait disparu

Bah non, c'est juste une faute.
