### ISSUE TITLE
Question sur la migration des contenus de 15.7 à 15.8 (ZEP-12)

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#364]
Je me suis posé des questions quand à la migration des contenus avec la ZEP-12:
- Sommes-nous d'accord que vous appliquez votre script de migration à tous les tutos existants (privés et non privés) ?
- Si oui, quelle est la stratégie quand une migration s'est mal passée ? Cela devient du cas par cas ?
- Si oui, il faut absolument tenir au courant la communication parce que les tutos corrompus me semblent les choses à détecter le plus rapidement possible dès la publication de la ZEP effectuée.
- Est-ce que tous les exports vont être à nouveau généré pour les tutoriels publiés (PDF, ePub, etc.) ?
- Si oui, l'issue https://github.com/artragis/zds-site/issues/341 n'est pas bloquante mais elle est très gênante parce que certains tutoriels auront toujours une date anglaise puisqu'ils ne seront jamais mis à jour.

Voilà, voilà. :)

**Comment by pierre-24** [comment]
1. Oui :)
2. C'est effectivement du cas par cas, parce que le nombre de tuto qui vont planter sera relativement faible (on en a détecté à peu près 5 sur la bêta, il y en aura peut-être plus en prod).
3. La procédure de migration en donne la liste. Je compte sur la bonne volonté de la personne qui fait la migration pour les noter (à priori, cette étape peut se faire avant et déjà prévenir les personnes concernées, ceci dit)
4. Oui
5. En effet. @artragis a des pistes, ceci dit, mais pour le moment, rien de probant :/

**Comment by artragis** [comment]
> Est-ce que tous les exports vont être à nouveau généré pour les tutoriels publiés (PDF, ePub, etc.) ?

tous les exports qui sont faits aujourd'hui le seront demain. Par contre s'il y a un bug dans le parsing latex du cours, on ne peut rien faire.

> Si oui, quelle est la stratégie quand une migration s'est mal passée ? Cela devient du cas par cas ?

En fait tant qu'on n'a pas la vraie base de tutoriel de la prod, je peux pas te dire. Dans l'idée : tout se passera bien et si ça foire les quelques tutos touchés seront immédiatement reportés à leurs auteurs.

**Comment by GerardPaligot** [comment]
Merci pour vos réponses les gars !

Est-ce que vous avez renseigné toutes ces étapes de migration dans update.md ?

**Comment by artragis** [comment]
of course. tu peux même vérifier.
