### ISSUE TITLE
Impossible de créer un contenu dont le titre du tutoriel n'est composé que de caractères spéciaux

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#365]
J'ai voulu créer un article dont le titre es "♡♡♡♡-♡♡♡♡" (ou je sais dans la vraie vie je n'aurai pas de tutoriel ainsi). Mais je ne comprends pas pourquoi l'interdire à la saisie.

Python sait gérer ça normalement non ?

**Comment by pierre-24** [comment]
Quel était le message d'erreur exact ? (bien que je m'en doute)

**Comment by firm1** [comment]
Message d'erreur dans le formulaire : "Ce titre n'est pas autorisé, son slug est invalide !" 

Cette règle fait que je n'arrive pas a créer une section/partie/chapitre dans le titre est composé de caractères spéciaux, ou tout simplement de symbole non-ascii

**Comment by artragis** [comment]
> Cette règle fait que je n'arrive pas a créer une section/partie/chapitre dans le titre est composé de caractères spéciaux, ou tout simplement de symbole non-ascii

c'est faux. Tu peux appeler ta partie éèâàùûôî si tu veux, ça marchera. par contre appeler ta partie  ♡♡♡♡-♡♡♡♡ est totallement irréaliste. Ce n'es tpas un bug c'est une feature.

N'oublions pas que le titre de ta partie doit être un titre qui sert au lecteur et qui en plus favorisera la SEO. mettre ♡♡♡♡-♡♡♡♡ ne répond à aucune des deux conditions. Refuser un tel titre est donc totalement normal, voulu et souhaitable.

**Comment by firm1** [comment]
Tu veux dire que c'est totalement irréaliste d'appeler une section de mon contenu ">=" ?

Il y'a toujours moyen de se déboruiller autrement, mais j'ai du mal a comprendre pourquoi c'est refusé. ça ne faisait pourtant pas partie de la spec. :(

**Comment by artragis** [comment]
Oui. une section qui s'appellerait comme ça n'a aucune raison d'exister. 
C'est strictement incompréhensible. "Les comparaisons" est alors le 
titre souhaité.

**Comment by firm1** [comment]
Je sais pas si c'est au logiciel d'imposer un style d'écriture à l'auteur.

**Comment by GerardPaligot** [comment]
> Je sais pas si c'est au logiciel d'imposer un style d'écriture à l'auteur.

_Apple désapprouve cette phrase._

**Comment by firm1** [comment]
Cette phrase était sponsorisée par l'industrie du logiciel libre :)

**Comment by pierre-24** [comment]
Au delà de ça, rien que des caractères spéciaux va générer un slug bizarre, si pas vide donc on risque les ennuis, non ?

**Comment by artragis** [comment]
Le logiciel a un but : gérer du contenu et l'éditer.

Nier ça c'est juste ridicule.

**Comment by GerardPaligot** [comment]
Haha. ^^

Plus sérieusement, je pense que vous vous compliquez la vie. Cette issue peut clairement faire l'objet d'une PR dans le futur. Elle n'est ni bloquante, ni importante pour un auteur. 

... A moins que @firm1 veut nous faire un tutoriel sur les bisounours. Dans ce cas là, va falloir régler cette issue en priorité maximale !

**Comment by artragis** [comment]
On peut toujours essayer de palier à ça d'une manière un peu casse 
gueule mais c'est totalement irréaliste.

**Comment by firm1** [comment]
> ... A moins que @firm1 veut nous faire un tutoriel sur les bisounours. Dans ce cas là, va falloir régler cette issue en priorité maximale !

Moi qui comptait faire un tuto sur les smileys ... c'est raté.

Non plus sérieusement, le problème de fond que montre c'est issue, c'est que le back n'arrive pas à gérer les slug dont le titre n'a que des caractères spéciaux. Ce n'est pourtant pas une contrainte technique insurmontable.

Là actuellement c'est le formulaire qui a l'air de bloquer l'utilisateur, mais je me demande si (pas testé encore) l'import d'archive bloque aussi cette pratique. Si oui ça veut dire que l'on doit avoir du code dupliqué quelque part .. bref, à regarder quand même de plus près avant de fermer le ticket

**Comment by artragis** [comment]
> Non plus sérieusement, le problème de fond que montre c'est issue, 
> c'est que le back n'arrive pas à gérer les slug dont le titre n'a que 
> des caractères spéciaux

ça montre que tu ne sais pas ce qu'est un slug.

**Comment by artragis** [comment]
> . Si oui ça veut dire que l'on doit avoir du code dupliqué quelque part

je ne vois pas le rapport. Au contraire. moins y'a de duplication et 
plus les comportements sont cohérents.

**Comment by firm1** [comment]
Du coup j'ai testé le cas de l'import et visiblement [le système n'est pas cohérent](https://github.com/artragis/zds-site/issues/368), et j'ai recassé mes articles :(

**Comment by artragis** [comment]
Ok donc @pierre-24 va falloir faire une fonction "update_slug" dans le 
modèle qui renvoit une exception quand  slug.replace("-", 
"").replace("_", "") == "". Ensuite on appelle cette fonction quand il faut.
