### ISSUE TITLE
Cohérence entre l'import d'une nouvelle version et le formulaire de création

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#368]
Scénario : 
- Je crée un article
- Je créer une section dont le titre est "..." => le système rejette avec une erreur
- je créer finalement la section avec pour nom "suspension".
- je télécharge l'archive
- je modifie le json pour remplacer le titre "suspension" par "..."
- je réimporte une nouvelle version de mon article
- je système l'accepte et j'ai donc un tutoriel dont la section est "..."

Le système n'est pas cohérent du coup.

**Comment by artragis** [comment]
ah ouai, ça sent bien la duplication de code ça @pierre-24

**Comment by pierre-24** [comment]
... ?

**Comment by artragis** [comment]
ça devrait être corrigé par cette PR (#370)

**Comment by firm1** [comment]
J'ignore si a beta a été synchronisée récemment, mais je tiens à signaler que j'arrive toujours à reproduire l'incohérence.

**Comment by artragis** [comment]
Elle est sensée avoir été corrigée. @pierre-24 avait dit qu'il 
regarderait un truc à propos de la migration qui avait été touché par 
cette correction.
Personnellement, cette incohérence me laisse perplexe en le sens où je 
n'arrive pas à voir d'où ça vient. Je te propose de regarder avec un 
oeil externe ou de laisser @pierre-24 voir.

**Comment by firm1** [comment]
> Je te propose de regarder avec un oeil externe

Quelque soit l'oeil avec lequel je regarde le bug est toujours là. Donc je pense qu'il faut rouvrir l'issue au moins pour le suivi

**Comment by artragis** [comment]
Ah oui, j'avais oublié ce point. Je parlais évidemment du code pour 
l'oeil externe.

**Comment by firm1** [comment]
Si j'ai bien compris, vous raisez une exception de type `ValueError` qui n'est jamais traitée pour renvoyer un message d'erreur a l'utilisateur

**Comment by artragis** [comment]
si, elle l'est.

**Comment by firm1** [comment]
> si, elle l'est.

Sur quelle ligne ?

**Comment by artragis** [comment]
Dans l'importation ou dans la migration?

Dans la migration, on ne le fait pas pour l'instant, dans l'importation 
c'est totalement géré dans la vue UpdateContentWithArchive.

**Comment by firm1** [comment]
Le seul moment ou il est censé être catché c'est [là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_contents.py#L500) et visiblement ce n'est pas `json_reader.loads(manifest)` qui va cracher cette Exception.

**Comment by artragis** [comment]
si si, elle est bien attrapée juste en dessous : 

``` python
 try:
            versioned = get_content_from_json(json_, None, '')
        except BadManifestError as e:
            raise BadArchiveError(e.message)
        except Exception as e:
            raise BadArchiveError(_(u'Une erreur est survenue lors de la lecture de l\'archive : ' + e.message))

```

le "except Exception" attrape bien évidemment la ValueError.

**Comment by pierre-24** [comment]
Vous battez pas les enfants ;)

**Comment by artragis** [comment]
Dis, @firm1 tu peux tester sur mon instance, là je sais que c'est à jour.

**Comment by DevHugo** [comment]
Ça marche pas en local mais j'ai trouvé pourquoi, sur la ligne [854](https://github.com/artragis/zds-site/blob/ba341b1f8e977ee32a085cd8a9c4ecedc55a7da5/zds/tutorialv2/utils.py#L854) et [871](https://github.com/artragis/zds-site/blob/ba341b1f8e977ee32a085cd8a9c4ecedc55a7da5/zds/tutorialv2/utils.py#L871). Tu as 

``` python
                try:
                    slug = slugify_raise_on_empty(child['slug'])
                except (ValueError, KeyError):
                    pass
```

`slugify_raise_on_empty` renvoi une exception `ValueError`, elle est attrapée dans le except mais comme elle est pas relancée, rien ne se passe et il ne va jamais dans la ligne que tu as cité au-dessus.

Comment je corrige cela ? car si j'envois une exeception, l'utilisateur aura une 500 et ça l'aiderais pas plus. Dois⁻je faire un petit template pour les erreurs ?

**Comment by artragis** [comment]
je sais pas trop, il me semble que j'avais fait ça volontairement.

**Comment by DevHugo** [comment]
Je pense que c'est juste un petit oubli =), regarde sur la ligne [864](https://github.com/artragis/zds-site/blob/ba341b1f8e977ee32a085cd8a9c4ecedc55a7da5/zds/tutorialv2/utils.py#L864), 10 lignes plus loin. Tu fait un 

``` python
                try:
                    parent.add_container(new_container, generate_slug=(slug == ''))
                except InvalidOperationError as e:
                    raise BadManifestError(e.message)
```

Tu utilise bien le mot clé raise, encore une fois dans le except ^^ ! Pour bien propager l'erreur !

**Comment by artragis** [comment]
Ok.

**Comment by DevHugo** [comment]
J'ai pas le temps ce soir, ce sera demain soir ou mardi soir.

**Comment by artragis** [comment]
je pense avoir trouvé le bon fil.

**Comment by DevHugo** [comment]
Du coup, tu l'as corrigé le souci  ? (J'ai vu que tu viens de commit)

**Comment by DevHugo** [comment]
Ça m'arrange car je viens de quitter le travail et je suis super fatigué et j'ai pas envie de dev ce soir.

**Comment by artragis** [comment]
je pense l'avoir fait

plus qu'à tester avec le cas de firm1

**Comment by DevHugo** [comment]
Ok, si j'ai le courage l'autre ticket sur la date des pdfs en anglais. J'ai le sentiment que je suis sur la bonne voie.

**Comment by artragis** [comment]
ça c'est cool :)

**Comment by artragis** [comment]
en fait je viens de me rendre compte d'un truc : ceci n'est pas un bug.

l'interface graphique confond actuellement titre et slug (c'est une évolution de les disjoindre), l'importation de manière très souple (logique) les disjoint du coup ça marchera. Faut juste vérifier que les slugs sont bons. Et ça c'est fait. Donc ;: je ferme, le merge peut arriver.

**Comment by GerardPaligot** [comment]
QA : Si je modifie uniquement le slug dans le manifest avec "...", ZdS refuse l'archive à l'importation :

> Une erreur est survenue lors de la lecture de l'archive : slug is incorrect

Faut juste traduire la raison en français sinon c'est bon.

Par contre, et @artragis est au courant, il y a un bug avec l'édition du titre dans le manifest.

**Comment by artragis** [comment]
tout est corrigé. Je ferme y'a plus qu'à ce que @pierre-24 corrige le très léger bug du message d'erreur qui apparait en anglais.
