### ISSUE TITLE
Impossible de créer la base de données

### ISSUE THREAD

**Issue by GerardPaligot** [artragis/zds-site#37]
La création de la base de données ne fonctionne pas. Voici l'erreur :

``` console
$ python manage.py syncdb
Operations to perform:
  Synchronize unmigrated apps: oauth2_provider, tutorialv2, corsheaders, forum, munin, debug_toolbar, sitemaps, rest_framework_swagger, rest_framework, haystack, crispy_forms
  Apply all migrations: forum, sessions, admin, utils, sites, auth, gallery, member, default, contenttypes, mp, article, easy_thumbnails, tutorial
Synchronizing apps without migrations:
  Creating tables...
    Creating table munin_test
    Creating table corsheaders_corsmodel
    Creating table oauth2_provider_application
    Creating table oauth2_provider_grant
    Creating table oauth2_provider_accesstoken
    Creating table oauth2_provider_refreshtoken
    Creating table tutorialv2_publishablecontent_subcategory
    Creating table tutorialv2_publishablecontent_helps
    Creating table tutorialv2_publishablecontent_authors
    Creating table tutorialv2_publishablecontent
    Creating table tutorialv2_contentreaction
    Creating table tutorialv2_contentread
    Creating table tutorialv2_validation
    Creating table forum_category
    Creating table forum_forum_group
    Creating table forum_forum
    Creating table forum_topic_tags
    Creating table forum_topic
    Creating table forum_post
    Creating table forum_topicread
    Creating table forum_topicfollowed
  Installing custom SQL...
  Installing indexes...
Running migrations:
  Applying contenttypes.0001_initial...Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/base.py", line 533, in handle
    return self.handle_noargs(**options)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/commands/syncdb.py", line 27, in handle_noargs
    call_command("migrate", **options)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 161, in handle
    executor.migrate(targets, plan, fake=options.get("fake", False))
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 68, in migrate
    self.apply_migration(migration, fake=fake)
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 96, in apply_migration
    if self.detect_soft_applied(migration):
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/migrations/executor.py", line 140, in detect_soft_applied
    apps = project_state.render()
  File "/Users/Gerard/.virtualenvs/zdsenv/lib/python2.7/site-packages/django/db/migrations/state.py", line 75, in render
    "for more" % new_unrendered_models
django.db.migrations.state.InvalidBasesError: Cannot resolve bases for [<ModelState: 'tutorialv2.ContentReaction'>, <ModelState: 'forum.Post'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.7/topics/migrations/#dependencies for more
```

**Comment by pierre-24** [comment]
@artragis a exactement le même problème, il a dit qu'il s'en occupait demain. La raison étant que va savoir pourquoi, le modèle forum veut pas se faire migrer. Voir #26 :)

**Comment by artragis** [comment]
En fait le problème est plus complexe que ça : même en enlevant tutorialv2 des INSTALLED APPS je ne peux pas builder le tout.
Je vais commiter les changements qui permettent de changer le comportement des béta mais en l'état c'est vraiment la merde pour la bdd.

**Comment by GerardPaligot** [comment]
La raison est assez simple : `tutorialv2` figure dans les apps non migrés et son modèle `ContentReaction` hérite de `Comment` dans le module migré `utils`. Du coup, il est pas content parce que tu tentes d'utiliser des choses d'un module migré dans un non migré.

Reste à savoir ce que veut dire un app migré ou non. La documentation ne dit rien à ce sujet.

**Comment by artragis** [comment]
et comment on fait en sorte que tutorialv2 soit une app migrée? parce que makemigrations me dit que l'app n'existe pas.

**Comment by GerardPaligot** [comment]
Comme je te dis, la documentation ne dit rien à ce sujet. Par contre, après une recherche rapide, je suis tombé là dessus : http://stackoverflow.com/a/25858659/3006692

Est-ce que tu peux essayer la manipulation ?

**Comment by artragis** [comment]
J'ai commenté : 

article
tutorial
tutorialv2
mp

python manage.py migrate <- erreur identique (il arrive pas à faire le forum.POST

**Comment by GerardPaligot** [comment]
Ok et si tu spécifies toutes les applications migrées dans le `settings.py`? https://docs.djangoproject.com/en/1.8/ref/settings/#migration-modules

**Comment by GerardPaligot** [comment]
Cela dit, quand je regarde votre dossier de migration des forums, vous êtes passé du 2 à 7 : https://github.com/artragis/zds-site/tree/zep_12_double_stack/zds/forum/migrations

Comment ça se fait ?

**Comment by artragis** [comment]
bah avant y'avait 6 migrations mais 5 d'entre elles ont été ramenées en 1 lors du passage de django 1.6 à 1.7

**Comment by GerardPaligot** [comment]
Il serait peut-être intéressant de rendre cohérent ces fichiers de migration. Je sais que l'erreur ci-présente a déjà été rencontré dans le module des MPs et a été résolue en remettant à plat ses fichiers de migration.

**Comment by artragis** [comment]
y'a une commande pour ça?

**Comment by GerardPaligot** [comment]
Nope, c'est manuel. C'était firm1 qui avait fait la correction et voici sa PR : https://github.com/zestedesavoir/zds-site/pull/2537/files

**Comment by artragis** [comment]
J'inspecte ça ce midi.

**Comment by artragis** [comment]
Problème réglé en suivant la procédure suivante:
- suppression de toutes les migrations liées au "related_content" dans les forums
- suppression de toutes les migrations **de manière exhaustive** dans le module tutorialv2
- `python manage.py makemigrations`
- `python manage.py migrate`

**Comment by pierre-24** [comment]
M'étonne pas que la solution soit ça, j'avais déjà fini par en arriver par de tels extrèmes pour le module de galerie (mais à l'époque, j'avais telement fait de truc en une fois que j'avais pas forcément relié ça a la solution). Donc ce coup-ci on est bon ? Génial, merci :)

**Comment by GerardPaligot** [comment]
C'est quoi `related_content` ?

**Comment by pierre-24** [comment]
Un remplaçant de la clé qui faisait en sorte que le sujet soit lié à un forum dans le modèle, pour les bêta, un bricolage de Firm1.

**Comment by pierre-24** [comment]
(qui s'appelle, sur _dev_ ... `key`, soit le nom le plus pourris de l'univers pour ça, si c'est possible)

**Comment by artragis** [comment]
Quelque chose qui n'existe plus, issu de ce que @spacefox appellerait "la
basecode moisie".
En fait c'était la solution utilisée au départ pour trouver le forum beta.
Elle était inspirée de la solution créée par firm1 pour les tuto. C'était
la clef qui pointait de Forum vers PublishableContent.

2015-04-16 13:38 GMT+02:00 Gérard Paligot notifications@github.com:
