### ISSUE TITLE
Validation partielle

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#38]
Il serait vraiment utile de pouvoir valider partiellement des big-tuto, en choisissant quels chapitres passer en ligne.

Ça permet aux auteurs de publier un cours avant qu'il ne soit totalement fini, et pour un gros tuto c'est quasi indispensable.

Ça pose également problème pour certains tutos importés, étant donné que le sdz proposait cette fonctionnalité. Par exemple le tuto Zbrush, qui a des chapitres en cours de rédaction.

https://github.com/zestedesavoir/zds-site/issues/1334

**Comment by pierre-24** [comment]
Bon, à réflexion, j'ai deux choses à dire là dessus:
1. C'est une évolution, ça veut dire qu'on est pas tenu de l'implémenter. D'autant que c'est une fonctionnalité qui irait magiquement bien si on ce mettais à gérer les branches (ZEP-08 spotted).
2. Si tout de même on voulais l'implémenter, il y a plusieurs manières de le faire: 
   1. Tenir une liste des trucs à publier et pas publier et faire un peu de magie au moment de la publication, ce quest faisable, mais il va en plus falloir gérer le cas un peu tordu de la validation, pour que les validateurs ne "voient" que ce qu'ils sont sencé valider et pas "tout"
   2. La solution cochonne, et que j'aime pas du tout: on crée un _commit_ qui reprend exactement ce qui doit être validé, et on "supprime" temporairement les parties indésirables, puis on balance cette version là en validation. Ensuite, on reconstruit le contenu à l'origine et on le repasse dans le commit suivant. Si j'aime pas, c'est surtout parce que j'ai l'impression de saloper l'historique, et puis aussi parce que ça va pas être simple pour les corrections éventuelles, mais ça a l'avantage d'être plus facile à implémenter que l'idée précédente
   3. La solution moins cochone dans le même ordre d'idée que la précédente, mais que j'aime encore moins: le code crée un second contenu ne contenant que ce qu'il y a à valider, et balance ça en validation. Problème, c'est qu'il faut faire de la magie noire pour que le tout reste cohérent :o 

Voilà.

**Comment by artragis** [comment]
et dire qu'il suffirait de créer un autre... manifeste.

**Comment by pierre-24** [comment]
J'interprète ta réponse de ~~deux~~ trois manière ^^
1. Soit ça correspond à ce que je propose comme idée "ii"
2. Ou qu'il "suffirait" de rajouter le paramètre `accessible=False` à un conteneur/extrait pour le faire disparaitre ou pas ^^
3. Ou bien tu propose la création d'un manifest alternatif, genre `manifest_publication.json`

J'avoue que la seconde idée, bien qu'elle modifie gentiment notre propre définition du manifest qu'on a mis tant de temps à créer, est séduisante. La troisième idée est encore plus séduisante, ceci étant dit, bien qu'elle pose un autre problème, puisque "manifest.json" est systématiquement écris en dur dans le code ^^

**Comment by artragis** [comment]
on peut aussi ne pas l'implémenter pour l'instant et revenir dans la dev 
zone pour expliquer toutes nos idées.
Mais globalement on a réussi jusque maintenant à faire les choses 
intelligemment. Je posterai demain sur le forum une explication plus 
complète.

**Comment by artragis** [comment]
@Eskimon : penses-tu que la validation partielle doit être mise dans la version 1 de cette ZEP? Ou bien doit-elle être développée après la release?

**Comment by Eskimon** [comment]
- Soit ca vous demande pas trop de travail parce que vous savez deja comment faire et dans ce cas "go for it!"
- Soit c'est un gros morceau et dans ce cas on reste alignee sur l'existant et on fait un ticket "evolution" pour le faire apres coup.

C'est une fonction tres attendu, mais je suis pas sur que vous embeter avec en vaille la peine pour le moment, vous avez deja fait un travail enorme :D .

**Comment by Eskimon** [comment]
Vous avez une reponse par rapport a mes deux options ? (il me semble avoir lu un truc a ce sujet recemment mais je sais plus ou)

**Comment by artragis** [comment]
Evolution AMHA.

2015-05-19 13:53 GMT+02:00 Eskimon notifications@github.com:

**Comment by pierre-24** [comment]
Évolution, effectivement. Ceci dit, on a un peu débroussayé le chemin en proposant des pistes de solution (la plus simple étant la ZEP-08 :) )
