### ISSUE TITLE
Correction du bug 1226

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#39]
Je pense que la correction est là MAIS je n'ai pas fait le test.
Si quelqu'un pouvait écrire le test unitaire + faire la QA.

Je ne sais pas ce qui se passe quand on télécharge une archive de son tutoriel, mais il y a plein de choses qui ne devraient pas s'y trouver. Par exemple, ici :

screen-1

On peut voir que dans l'archive, le dossier concernant l'ancienne partie est dans l'archive alors qu'il n'est plus dans la version du site du tutoriel. La situation est la même pour les tutoriels, comme ont peu le voir sur ce screen :

screenshot-un-big-tuto tar

Quand on renomme les chapitres, le pk reste le même (ce qui est normal) et les dossiers de l'archive sont dupliqués, alors qu'une fois encore, ce n'est pas le cas sur la version du site.

J'en déduis donc que la création de l'archive se fait en prenant TOUT les snapshots du tutos, pour une raison que je ne comprend pas.

https://github.com/zestedesavoir/zds-site/issues/1226

**Comment by artragis** [comment]
ça marche sur les archives des tutos hors ligne.

il ne reste plus qu'à tester ceci:
- créer un tuto avec deux conteneur
- publiez le
- retirer un conteneur
- vérifier que dans l'archive "en ligne" il est bien dispo, et pas dans l'archive "hors ligne"

**Comment by Vayel** [comment]
"créer un tuto avec deux conteneur" : emboîtés ou adjacents ?

**Comment by artragis** [comment]
c'est égal. Si ça te chante tu peux même tester les deux cas.

**Comment by Vayel** [comment]
QA OK.

**Comment by artragis** [comment]
Merci, je ferme!

**Comment by pierre-24** [comment]
M'en doutais ;)

(`git mv` et `git rm` <3 )
