### ISSUE TITLE
Evolution 1319 sur l'inscription des auteurs au suivi des contenu

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#40]
Le suivi (via les notif) des réactions d'un article, d'un tuto et d'un topic de forum n'est pas pareil.

Pour le forum on se base sur une la classe TopicFollowed et TopicRead alors que dans le cas des articles et tutos, on se base uniquement sur ArticleRead ou TutorialRead, en partant du principe que pour suivre il faut poster.

Résoudre cette issue reviendrait donc a crée les tables TutorialFollowed et ArticleFollowed et d'adapter le calcul pour les notification.

Mais très sincèrement, pour éviter de pourrir le modèle de donnée ainsi que les fichiers de migrations, je vous conseille d'attendre le passage de la ZEP 12 vu que cette issue n'est pas urgentissime.

**Comment by pierre-24** [comment]
Bwah deux tables `ContentFollowed` et `ContentRead` et on est bon :)

De tête, c'est pas déjà fait dans le `models.py` mais pas encore relié à quelque chose ?

**Comment by pierre-24** [comment]
Comme je disais sur #45, pas oublier de rajouter les auteurs au fil de conversation.

**Comment by artragis** [comment]
C'est justement l'idée non?

**Comment by pierre-24** [comment]
Comme j'avais compris l'issue, il y avait aussi le fait qu'on doive pouvoir suivre et se désinscrire de la conversation, donc c'est de manière générale.

**Comment by pierre-24** [comment]
Du coup, on est quasi bon, ici, nan ?

**Comment by artragis** [comment]
Oui, plus qu'à gérer le cas des multi notifs.

**Comment by artragis** [comment]
Alors actuellement, j'ai mis un "ContentRead" (pas de ContentFollowed) sur les tutoriels de l'auteur, l'auteur ne peut pas "désuivre" son propre tuto, évolution qui devra venir plus tard. Pour l'instant, Je passe en "need QA".

**Comment by Vayel** [comment]
Je ne vois pas du tout quelle QA il faut faire. Il n'y a aucun bouton "Suivre".

**Comment by artragis** [comment]
non, c'est automatique, dès ton tuto est publié, tu "suis" le tuto.

**Comment by Vayel** [comment]
Nop. 
- Publication d'un tuto avec admin
- Commentaire avec user
- Commentaire affiché mais pas de notification pour admin
- Commentaire avec admin
- Commentaire affiché mais pas de notification pour admin
- Commentaire avec user
- Commentaire affiché mais pas de notification pour admin

**Comment by Vayel** [comment]
Autant pour moi, en fait ça fonctionne, pour les articles et les tutos.

**Comment by artragis** [comment]
habile ! je ferme !
