### ISSUE TITLE
Date de dernière modification

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#41]
https://github.com/zestedesavoir/zds-site/issues/1654#issuecomment-93723607

**Comment by pierre-24** [comment]
Effectivement, "need test", mais il me semble que j'ai bien fait exprès de différencier `create_date` et `update_date` quand j'ai créé le modèle, et qu'on s'amuse bien à changer le second à chaque fois qu'on touche le `sha`. Du reste, j'ai pensé à un truc, c'est que ça devrait se retrouver directement dans la fonction `update()` du modèle lui-même, ça nous simplifierai la vie puisqu'on aurait plus à y penser.

**Comment by artragis** [comment]
hum, pas sûr que je touche à la date d'update quand je déplace un élément. Si tu as une solution automatisée (syle la fonction `update`) je suis friand, parce que ça c'est le genre de bug qu'on va mettre du temps à trouver sinon.

**Comment by artragis** [comment]
> Du reste, j'ai pensé à un truc, c'est que ça devrait se retrouver directement dans la fonction update() du modèle lui-même, ça nous simplifierai la vie puisqu'on aurait plus à y penser.

j'ai modifié la méthode `save`, j'ai ajouté des TU dans la partie "déplacement".
voilà

**Comment by pierre-24** [comment]
Coool :)

Ceci étant dit, il faut savoir que `save()` est appellé un peu partout dans le process de validation (pour mettre à jour `sha_validation`). Est ce qu'il est logique qu'un tuto soit "mit à jour" quand sa validation est demandée/validée/refusée/annulée ?

**Comment by artragis** [comment]
outre le fait que mon test ne soit pas aussi fiable que je le pensais, 
ça peut être en effet un problème mais franchement, à la marge et je 
pense même que ça serait plutôt bon, non?

**Comment by pierre-24** [comment]
On laisse comme ça :)

**Comment by Vayel** [comment]
Quelle est la QA à faire ici ?

**Comment by artragis** [comment]
vérifier que chaque modification change la date de dernier modif.

**Comment by Vayel** [comment]
OK : 
- "Dernière mise à jour" pour un tutoriel pas en bêta
- "Dernière mise à jour" pour un tutoriel en bêta
- "Publié" pour un tutoriel publié

se mettent à jour.
