### ISSUE TITLE
Pas de bouton pour signaler des fautes sur un article (2078)

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#42]
Vérifions que nous pouvons mettre un bouton "signaler les fautes" dans les articles (https://github.com/zestedesavoir/zds-site/issues/2078)

**Comment by artragis** [comment]
Le bouton n'existe nulle part pour l'instant.

**Comment by pierre-24** [comment]
Et la classe qui va bien qui doit se trouver derrière non plus ;)

**Comment by artragis** [comment]
et la fonctionnalité est bien casse couille à coder en plus :(

**Comment by pierre-24** [comment]
Je prend (c'est moi qui l'as codé à l'origine)

**Comment by pierre-24** [comment]
J'avoue que c'était plus lourd à coder que je ne le pensais :o

**Comment by artragis** [comment]
Well done. QA faite, je ferme. \o/
