### ISSUE TITLE
Les tags du tutoriel pour son sujet dans la Bêta-zone

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#43]
https://github.com/zestedesavoir/zds-site/issues/2274

**Comment by pierre-24** [comment]
Pour moi, non. Mais à tester.

**Comment by artragis** [comment]
Effectivement, rien n'est fait pour l'instant.

**Comment by artragis** [comment]
Et voilà ! plus qu'à faire la QA ^^
J'ai mis le TU qu'il faut aussi.

**Comment by artragis** [comment]
Etant le développeur, jen 'ai pas le droit de faire la QA, mais mes tests sont plutôt concluant.

**Comment by artragis** [comment]
Nota : je n'ai pas remis les tag "tutoriel", "beta" et "article". Dois-je les remettre?

**Comment by pierre-24** [comment]
Mmmh, je remetrais au minimum le tag "bêta", parce qu'il est utile. Les tags articles/tutos me semble un peu ridicules puisqu'on peut pas faire de sélections de plusieurs tags à la fois dans la recherche, et puis il me semble pas avoir beaucoup de sens.

**Comment by artragis** [comment]
Je fais ça demain sauf si tu as prévu ton énorme rebase.

**Comment by pierre-24** [comment]
Non, je t'avoue que je suis un peu _busy_ ces temps-ci ^^

(à mon avis, je vais faire ça du weekend, si ça ne t'ennuie pas)

**Comment by artragis** [comment]
Pas du tout. Préviens moi juste pour que je fasse une pause de dev 
pendant quelques heures histoire qu'on ne se tire pas dans les pates.

**Comment by poulp** [comment]
J'ai testé la création d'un sujet et sa modification et ça fonctionne de mon côté

**Comment by artragis** [comment]
merci, je ferme.
