### ISSUE TITLE
 Erreur 500 sur le diff d'un nouveau tutoriel

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#44]
https://github.com/zestedesavoir/zds-site/issues/2308

Devrait être implémenté mais non testé.

**Comment by artragis** [comment]
Devrait être bon, j'ai même ajouté un TU.

**Comment by Eskimon** [comment]
Je confirme en QA à la main, pas de crash :)

**Comment by artragis** [comment]
Merci Eskimon pour cette QA, je ferme !
