### ISSUE TITLE
Inscrire un auteur aux reactions de tutos/articles

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#45]
[Via Eskimon](https://github.com/zestedesavoir/zds-site/issues/1319#issue-38993369)

> Lorsqu'un auteur publie un article (et idem pour tuto ?) il n'est pas automatiquement ajouté aux suivis des reactions (tant qu'il ne poste pas). C'est dommage !

https://github.com/zestedesavoir/zds-site/issues/1319

**Comment by artragis** [comment]
duplicat de #40

**Comment by pierre-24** [comment]
Pas exactement, mais il suffit de mettre à jour la description de #40 :)
