### ISSUE TITLE
Gérer les diffs

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#46]
Pour moi, la libraire de diff utilisée fait actuelement n'importe quoi (en plus du fait que ce qu'elle génère n'est ni beau, ni pratique). Je ne sais ceci dit pas si c'est le problème de la ZEP-12 ou une évolution.

**Comment by pierre-24** [comment]
(relié à https://github.com/zestedesavoir/zds-site/issues/1443)

**Comment by Eskimon** [comment]
Evolution.

**Comment by pierre-24** [comment]
Ok :)
