### ISSUE TITLE
On peut déplacer un conteneur avant le conteneur parent lui-même

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#47]
Voir ici:

![untitled](https://cloud.githubusercontent.com/assets/7889675/7182441/5292aca2-e41f-11e4-919f-05cff1783dac.png)

Il est proposé de déplacer le chapitre avant le tuto lui-même. Évidement, ça ne fonctionne pas ;)

**Comment by artragis** [comment]
Pas normal ! il est sensé y avoir des garde fous !
Si tu valides, le serveur fait l'opération ou pas? S'il ne la fait pas, il faudra juste vérifier la fonction `get_tagged_tree_container` c'est elle qui doit valider la partie front.

**Comment by pierre-24** [comment]
Il renvois une erreur (disant qu'il arrive pas à faire `split()` de tête) et ça marche pas (heureusement). Et à mon avis, la solution doit être toute bête, mais je préfère le signaler :)

**Comment by pierre-24** [comment]
De manière tout à fait générale, remarque en passant: est ce que c'est vraiment utile de mettre cette ligne, puisqu'on déplace toujours dans le contenu lui-même ?

Partant de toute façon du principe que si on commence à autoriser des déplacement inter-contenus (et c'est clairement hors-scope de la ZEP-12), il faudra de toute façon employer un autre formulaire ?

**Comment by artragis** [comment]
En effet, il suffit alors de : 
- mettre un try/catch sur le split (ou la fonction qu'il arrive pas à faire) pour envoyer une erreur au cas où quelqu'un trafiquerait le formulaire
- surcharger la méthode get_tagged_tree du VersionnedContent pour qu'elle ne yield pas le contenu lui même.

**Comment by artragis** [comment]
ça devrait être bon !

**Comment by Eskimon** [comment]
Pour un article:
- Déplacements d'extraits dans tout les sens : OK

Pour un tuto:
- Avec uniquement des extraits : OK
- Autres cas : en cours

J'ai réussi à avoir une 404 en faisant le cheminement suivant:

Je crée un tuto avec 1 conteneur (C1) qui possede un extrait (E1) et un deuxieme conteneur (C2) qui possede lui meme un conteneur (CA) qui possede deux extraits (E2, E3). On a donc la hierarchie suivante:
- C1
  - E1
- C2
  - CA
    - E2
    - E3

Je déplace E2 au dessus de E1 : OK
- C1
  - E2
  - E1
- C2
  - CA
    - E3

A ce moment je déplace E1 au dess(o)us de E3 et j'obtiens une 404.

**Comment by artragis** [comment]
Ok, je check ça.

**Comment by Eskimon** [comment]
# QA Time !!

Convention de nommage : E=Extrait, C=Chapitre, P=Partie

## Pour les articles
- Tout Roule \o/

## Pour les tutos

### "Mini-tuto" (que des E)
- Tout Roule \o/

### "Moyen-tuto" (plusieurs C et avec chacun des E, pas de P)
- On ne peut pas déplacer un E de C1 vers C2 si C2 est vide
- Sinon tout roule, chapeau !

### "Big-tuto" (plusieurs P avec chacune plusieurs C et avec chacun des E)
- J'ai réussi à reproduire la même 404 que mon message de QA précédent :(
- J'ai pas été plus loin pour l'instant

(sinon à part ca quand on a un seul extrait (dans un conteneur ou pas) l'option "descendre est toujours dispo bien qu'elle ne fasse rien)

**Comment by artragis** [comment]
> On ne peut pas déplacer un E de C1 vers C2 si C2 est vide

Hum, je vois même pas comment c'est possible. Peux-tu importer le tuto 
qui te sert de test sur zds.francoisdambrine.me/contenus pour que je 
vois ce qu'il se passe avec les accès serveur?

> J'ai réussi à reproduire la même 404 que mon message de QA précédent :(

strange, je vérifie

> (sinon à part ca quand on a un seul extrait (dans un conteneur ou pas) l'option "descendre est toujours dispo bien qu'elle ne fasse rien)

idem

**Comment by Eskimon** [comment]
> Peux-tu importer le tuto qui te sert de test sur zds.francoisdambrine.me/contenus pour que je vois ce qu'il se passe avec les accès serveur?

J'ai simplement créer deux chapitres, un avec des exraits et l'autre sans et tenter de déplacer. Je retest sur ton serveur...

EDIT : Yep je confirme, l'option étant grisé le C2 est inaccessible. voir mon tuto "test Eskimon" sur ton serveur et essaie de déplacer un extrait de C1 vers C2.

**Comment by artragis** [comment]
> J'ai réussi à reproduire la même 404 que mon message de QA précédent :(

Ouf, je viens de le corriger. J'en ai mare des bugs d'intégration :(

**Comment by artragis** [comment]
@Eskimon tu peux QA ça?

**Comment by Eskimon** [comment]
YaY la 404 a disparu sur mon test precedent ! Ca c'est bien !

Par contre j'ai toujours mon souci sur moyen-tuto:

> On ne peut pas déplacer un E de C1 vers C2 si C2 est vide

Tu peux tester en essayant de déplacer l'extrait entre C1 et C2 ici (compte `user`) : http://zds.francoisdambrine.me/contenus/2/moyen-tuto-petit-test/

---

Je continu a tester des deplacements sur des gros tutos...

**Comment by artragis** [comment]
> On ne peut pas déplacer un E de C1 vers C2 si C2 est vide

Not a bug, a feature, sry guy (plus précisément : pour l'instant on ne peut
pas déplacer "dans" seulement "avant" et "après", on verra plus tard pour
"dans")

**Comment by Eskimon** [comment]
# Big Tuto

Strucutre
- P1
- P2
  - P2C1
- P3

Si je veux déplacer P2C1 je me prend des 404 (en mode _monkey test_, je vois des options pas grises alors je clic :D )

---

Meme souci si j'ai deux chapitres dans P2 et que je veux les inverser

---

Je peux pas continuer le test avec des extrits car nginx me renvoi un 502 tout le temps

**Comment by artragis** [comment]
Ouai, il te revoie des 502 car le serveur a stoppé (je suis en proxy pass)
je regarde ça ce soir, mon dernier commit a cassé beaucoup de choses.

**Comment by Eskimon** [comment]
Les déplacements d'extraits intra/inter chapitres/parties marchent bien sinon :)

Donc a part les commentaires précédents ca me semble pas mal :) Beau boulot les gars !

**Comment by artragis** [comment]
> Si je veux déplacer P2C1 je me prend des 404 (en mode _monkey test_, je
> vois des options pas grises alors je clic :D )

bug non reproductivle actuelleent.

**Comment by pierre-24** [comment]
J'suis d'accord avec Eskimon:

Quand tu va là: http://zds.francoisdambrine.me/contenus/8/deplacement/p2/ (avec `admin`), et que t'essaye de bouger "P2C1", t'as une 404. Ceci étant dit, je crois savoir pourquoi tu te mange pas d'erreur dans tes tests (à prononcer 10x très vite): c'est le code de la modale qui est pas bon:

![screenshot from 2015-05-06 14 35 17](https://cloud.githubusercontent.com/assets/7889675/7500691/3a1dde74-f3fd-11e4-8b52-0d1de6ddb18b.png)

... Pour moi, t'es pas censé avoir un `first_level_slug` dans ce cas-ci, puisque tu bouge un chapitre et pas un extrait. Je me trompe ?

**Comment by pierre-24** [comment]
(d'ailleurs, j'avais pas vu, mais le formulaire en question s'appelle `#move-extract` alors que c'est bien un chapitre, donc y'a un truc qui cloche dans la _template_).

**Comment by artragis** [comment]
yep, en effet.

**Comment by artragis** [comment]
copier coller foireux tous ça. Du coup c'est invisible dans les TU 
puisque là c'est de la pure intégration.

**Comment by pierre-24** [comment]
C'est tout de même plutôt rassurant, ça veux dire que les tests sont ok :)

**Comment by artragis** [comment]
Oui. Et maintenant, ils sont même complets, faudrait que je dépile ce 
ticket soit dit en passant.

**Comment by Eskimon** [comment]
Du coup je dois tester un truc ici ?

**Comment by artragis** [comment]
Pour l'instant, non, je n'ai pas corrigé le bug qui crée le 404.

2015-05-07 14:30 GMT+02:00 Eskimon notifications@github.com:

**Comment by pierre-24** [comment]
Le bug d'intégration est corrigé, donc @Eskimon, la balle est dans ton camp ! :)

**Comment by Eskimon** [comment]
En reprenant la structure :
- P1
- P2
  - P2C1
- P3

J'ai deplace P2C1 avant P2 et du coup mon chapitre est devenu une partie. C'est normal ou pas ?

**Comment by artragis** [comment]
> J'ai deplace P2C1 avant P2 et du coup mon chapitre est devenu une partie.
> C'est normal ou pas ?

Bah oui. En le déplaçant avant P2 tu le mets au même niveau que P2, donc ça
devient une partie.

**Comment by Eskimon** [comment]
Ok, pourquoi pas, mais alors attention:
- P1
  - C1
- P2
  - C2
- P3

Si j'essaie de deplacer P1 apres P2-C2 (le systeme me le propose alors je clic !!) j'ai une erreur !

```
Exception Type: InvalidOperationError
Exception Value:    Cannot add another level to this container
```

**Comment by artragis** [comment]
ça c'est encore un bug d'intégration... normellement P1 ne peut pas être
déplacé après C2 (le back répond bien, le front, non)

**Comment by Eskimon** [comment]
Du coup j'ai l'impression que j'ai peter la page `/contenus` de user...

**Comment by artragis** [comment]
Oui le problème est ultra blocant là.

Apparemment, malgré le refus de déplacer, le déplacement a quand même eu
lieu !

2015-05-15 11:21 GMT+02:00 Eskimon notifications@github.com:

**Comment by artragis** [comment]
C'est bon, ça devrait être corrigé. J'ai supprimé le tuto gênant de mon
serveur par la même occasion histoire que tu puisse reprendre la main si ça
te chante.

**Comment by Vayel** [comment]
https://github.com/artragis/zds-site/issues/47#issuecomment-102327271 semble bon : 
- P1
  - C1
- P2
  - C2
- P3

Déplacement après P2 (C2 est grisé).
- P2
  - C2
- P1
  - C1
- P3

**Comment by pierre-24** [comment]
Si c'est bon, on ferme :)

**Comment by pierre-24** [comment]
EDIT: @artragis : est ce que le "need-TU" étais valable ?

**Comment by artragis** [comment]
Depuis le temps, non, j'ai juste oublié de MAJ.
