### ISSUE TITLE
URL renvoyé quand on déplace quelque chose

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#48]
J'ai l'impression qu'il y a pas de règle sur ce quoi on tombe quand on déplace un truc: parfois on est renvoyé sur ce qu'on a déplacé, parfois on est renvoyé à l'endroit ou on était.

À vérifier et s'accorder sur une règle le cas échéant ;)

**Comment by Eskimon** [comment]
J'ai le sentiment qu'on tombe toujours sur l'element deplace (et a sa nouvelle place bien sur) non ?

**Comment by pierre-24** [comment]
En effet, et à priori c'est ce qui me chiffone. Pour moi, quand on déplace un chapitre dans une partie, on devrait rester sur la page de la partie. Non ?

**Comment by Eskimon** [comment]
Ah bon ? Moi ca me gêne pas d’atterrir la ou on déplace XD . Je suppose que les deux approches sont possible en fait ^^

**Comment by pierre-24** [comment]
Dans ce cas, c'est deux contre un, je m'incline ;)
