### ISSUE TITLE
Vocabulaire employé dans l'interface

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#49]
Très très naïvement, nous avons réemployé le vocabulaire mis en place pour la ZEP, à savoir "contenu", "conteneur" et "extrait", sauf que ça ne veux absolument rien dire pour l'auteur lambda. À savoir que "section" a déjà été proposé pour remplacer "conteneur".

**Comment by Eskimon** [comment]
Contenu -> section -> article ? (pour reprendre le vocabulaire html)
Contenu -> section -> chapitre ?
Contenu -> chapitre -> section ?

**Comment by pierre-24** [comment]
J'essaye de comprendre ce que tu as voulu dire par là ^^

**Comment by Eskimon** [comment]
:D 

J'essayais de proposer une terminologie !! Car je confirme, l'interface est pas toujours très clair avec juste les termes "conteneur" et "extrait".

Du coup pourquoi pas garder partie > chapitre > extrait(ou section) ?

Ou alors Chapitre > Section > Extrait ?

**Comment by pierre-24** [comment]
Je vois ce que tu essaye de faire, et j'apprécie la seconde proposition. Comme t'as pu le constater, on ne demande pas à l'avance à l'auteur la taille de son tutoriel, donc on ne peut pas "deviner" (tout du moins au début) comment va s'appeler ce qu'on ajoute. 

Premièrement, j'aime bien l'idée d’appeler quoiqu'il arrive un conteneur de premier niveau un "chapitre". C'est un peu contre-intuitif envers ce qui se fait actuellement, mais ça peut être plus robuste au final :) (et plus simple à mettre en place).

Sinon, il y a la proposition bateau : Section > sous-section > Extrait (mais je pique l'idée au LaTeX, là)

**Comment by artragis** [comment]
> Sinon, il y a la proposition bateau : Section > sous-section > Extrait (mais je pique l'idée au LaTeX, là)

Partie/chapitre/extrait était tellement plus original comme idée :p 

ça peut se faire, je propose de créer une méthode dans le conteneur avec cette implémentation : 

``` python

def get_contextual_name(self):
    """Resolve this container's contextual name relatively to its position in the content.
    if it is a first level container, it is a "chapter" and a "section" if it is deeper. 
   base names are in french but can be internationalized thanks to ugettext module
    :returns: the container's contextual name
    :rtype: unicode
    """"
    if self.get_tree_depth() == 1:
        return _(u"Chapitre")
    elif self.get_tree_deph() > 1:
        return _(u"Section")
    else:
        return _(self.type)  # this is root content (depth == 0)
```

**Comment by pierre-24** [comment]
On perd rien à essayer ;-)

**Comment by Eskimon** [comment]
Du coup quelle est la décision finale ? Perso je vote pour la hiérarchie suivante :

Partie > Chapitres > Section

(en gros comme l'actuelle sauf que Section remplace Extrait, ca me semble sémantiquement plus correcte)

**Comment by artragis** [comment]
J'ai mis ça dans mon dernier commit.

**Comment by Eskimon** [comment]
Merfi :)

**Comment by Eskimon** [comment]
Mais du coup les choses s'affichent mal dans la sidebar j'ai l'impression (mais la nginx me plante)

**Comment by artragis** [comment]
Apparemment y'a de la merde, en effet. Pas letemps de corriger là.

2015-05-05 14:42 GMT+02:00 Eskimon notifications@github.com:

**Comment by pierre-24** [comment]
À mon avis, t'as oublié de corriger la _template_ des conteneurs:

![screenshot from 2015-05-06 07 13 43](https://cloud.githubusercontent.com/assets/7889675/7492215/836e9f0c-f3bf-11e4-89f3-af9bd5a2e982.png)

(d'ailleurs, dans un big-tuto, j'ai "ajouter une partie" partout, voir http://zds.francoisdambrine.me/contenus/3/test-dans-un-gros-tuto/p1/ avec `user`). Par ailleurs, faudra pas oublier de faire le changement dans les templates `/edit/container.html`, `/edit/extract.html`, `/new/container.html` et `/new/extract.html` (titre et fil d'ariane)

**Comment by artragis** [comment]
Non, c'est juste uqe j'ai pas encore maj mon serveur perso.

**Comment by pierre-24** [comment]
Ok en local, mais pas oublier ma remarque sur les templates de modification/création de conteneur/extraits.

**Comment by artragis** [comment]
sur la création, en effet oO.

**Comment by artragis** [comment]
On peut fermer?

**Comment by Eskimon** [comment]
Il faut verifier les templates ou pas encore ?

**Comment by artragis** [comment]
Juste le temps de mettre à jour mon serveur et ça sera bon ^^

**Comment by artragis** [comment]
en fait c'est bon ^^

**Comment by pierre-24** [comment]
Ou presque :) 

(testé avec "admin" sur http://zds.francoisdambrine.me/contenus/4/blablabla/ )
- Quand je clique sur "créer une partie" dans un tutoriel, j'ai "nouveau TUTORIAL" ?
  
  ![screenshot from 2015-05-14 11 10 31](https://cloud.githubusercontent.com/assets/7889675/7634598/085d1a5c-fa2a-11e4-8d48-b8383c027e32.png)
- Quand je vais sur un chapitre, le menu de gauche indique deux fois "ajouter un chapitre", mais les liens sont bon, ça devrait être "ajouter une section" : 
  
  ![screenshot from 2015-05-14 11 10 52](https://cloud.githubusercontent.com/assets/7889675/7634629/3923f002-fa2a-11e4-8695-266b7909efbb.png)
- Quand je clique pour créer un chapitre, la page d'ajout m'indique "créer une partie" (probablement lié au premier point)
- Quand j'ajoute une section, la page dit toujours "ajouter un extrait" (par contre, j'ai bien "éditer la section" :) )
- Quand j'édite une partie (http://zds.francoisdambrine.me/contenus/editer-conteneur/4/blablabla/p1/), le mot "Partie" dans le fil d'ariane est en majuscule (détail, j'avoue). Pareil pour "Chapitre" (http://zds.francoisdambrine.me/contenus/editer-conteneur/4/blablabla/p1/another/)
  
  ![screenshot from 2015-05-14 11 16 32](https://cloud.githubusercontent.com/assets/7889675/7634736/cd7afa3e-fa2a-11e4-98f7-b79da36775f4.png)
- L'erreur qu'on a quand on édite "p2c1" (http://zds.francoisdambrine.me/contenus/editer-conteneur/4/blablabla/p2c1/) N'EST PAS UNE ERREUR, c'est un test qui a mal tourné il y a longtemps, donc faux positif. De manière générale, faudra virer ce tuto après ce ticket-ci pour éviter d'avoir des histoires :p

**Comment by artragis** [comment]
ça devrait être bon pour ça.

**Comment by pierre-24** [comment]
Pour moi c'est bon. J'ai fait deux fix cosmétiques, mais dans l'idée c'est parfait. Je ferme :)
