### ISSUE TITLE
Les index de Solr

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#51]
Pour l'instant notre fichier d'index est copié/collé du vieux module de tuto.

Il faudra l'adapter pour qu'il découvre:
- le tutos
- les titres des sections
- les extraits des tutos
- les articles
- les extraits des articles

en faisant en sort qu'il différencie vraiment les tutos et articles (sauf si on veut changer cette partie là du module de recherche)

**Comment by artragis** [comment]
je ping juste @DevHugo car il nous avait dit avoir une bonne piste pour cette fonctionnalité.

**Comment by DevHugo** [comment]
J'ai pas eu du tout le temps de regarder désolé.  Je suis en partiel jusqu'à Jeudi. Si tu veux te lancer vas y

**Comment by pierre-24** [comment]
T'avais dit "la semaine prochaine", et ça tient toujours, donc te fout pas la pression pour ça, surtout :)

(artragis te pinge juste pour t'indiquer "la bonne issue", j'imagine ;) )

**Comment by artragis** [comment]
> (artragis te pinge juste pour t'indiquer "la bonne issue", j'imagine ;) )

exactement. Et aussi pour moi même suivre les choses. Le non dit est
toujours source de confusion. Je te mets juste dans la boucle pour que tu
sois au courant qu'on pense à toi et en même temps, nous ça nous évite de
nous y mettre et d'entrer en conflit de code avec toi.

**Comment by DevHugo** [comment]
J'ai cherché pendant longtemps et j'ai pas trouvé de solution satisfaisante, donc je reviens vers vous les mains vide.

Tout d'abord, il faut répondre à la question, "pourquoi on ne pas faire comme avant ?" qui était ma première solution. Aujourd'hui, quand on indexe un tutoriel, on indexe quatre objets différents: tutoriel, parts, chapter et Extract.

Pour indexer du contenu, on doit créé une classe et un fichier de template. Le fichier de template, qui ressemble à ça: 

```
(templates/search/indexes/nomDeLobjet/nomDeLobjet_text.txt => templates/search/indexes/tutorial/tutorial_text.txt)
{{ object.get_conclusion_online }}
{{ object.get_introduction_online }}
{{ object.description }}
{{ object.title }}
```

Dans ce template, on a les données à indexer, par-exemple, les données indexés ici sont le titre, la description, l'introduction et la conclusion.

Maintenant la classe python,

``` python
(search_indexes.py)
class ContentIndex(indexes.SearchIndex, indexes.Indexable):
    text = indexes.CharField(document=True, use_template=True)
    title = indexes.CharField(model_attr='title')
    description = indexes.CharField(model_attr='description')
    sha_public = indexes.CharField(model_attr='sha_public')

    def get_model(self):
        return PublishableContent

    def index_queryset(self, using=None):
        """Only tutorials online."""
        return self.get_model().objects.filter(sha_public__isnull=False) 
```

Le premier champ sert à charger notre templates avec les données indexés.
Les autres champs de la classe, ne sont pas indexés par-défaut, et permette de servir de critère de recherche. Par exemple, on pourrais dire qu'on veut rechercher uniquement sur le titre, ou sur la description ou sur le sha_public. Ces champs sont accessible aussi lors des résultat, ça permet d’éviter d'aller chercher les informations dans la base de données quand on affiche les résultats.

Deux méthodes sont à implémenter: `get_model(self)` et `index_queryset(self, using=None):`: 
-  `get_model(self)` renvoi un type de classe qui étend django.db.Model. On peut tricher et étendre cette classe sans être un objet de la base de donnée.
-  `index_queryset(self, using=None)` doit renvoyer [OBLIGATOIREMENT un QuerySet](https://github.com/django-haystack/django-haystack/blob/master/haystack/indexes.py#L184). Un truc de la base de donnée et j'ai n'est pas trouvé comment on créé un QuerySet à la main. Sachant que les parts, chapter, extract ne sont pas dans la base de données.

La deuxième solution est d'utiliser qu'un seul objet, celui en base de donnée, ça donne ça :

[La classe python](https://github.com/DevHugo/zds-site/blob/67f51b846ce6eed03e765d9c97c70a9e63e0f42a/zds/tutorialv2/search_indexes.py)

[Le template](https://github.com/DevHugo/zds-site/blob/67f51b846ce6eed03e765d9c97c70a9e63e0f42a/templates/search/indexes/tutorialv2/publishablecontent_text.txt)

MAIS y'a un gros gros désavantage, c'est que dans les résultat de la recherche, on a aucun moyen de savoir ou est l'endroit ou le contenu recherché se trouve. On a juste l'objet content mais on ne ne sait pas dans quel extract, chapter, parts, le contenu recherché est. Pour l'utilisateur cela signifie que l'on doit obligatoirement le rediriger vers le tutoriel et non vers un extrait. Pas cool, si c'est un big tuto, l'utilisateur est obligé de chercher dans toutes les parties à la main.

La troisième solution est d'utiliser une autre API.

EN GROS, C'EST LA MERDE.

**Comment by artragis** [comment]
Une solution serait donc de créer des classes style PublishedPart
PublishedChapter PublishedExtract, liées à PublishedContent et qui
implémentent les bonnes données.
Le problème c'est que c'est un poil casse pied de faire ça juste pour la
recherche et juste pour les tutos moyens/big.

Sachant que finalement, cesont surtout les extraits qui comptent (et non
les parties/chapitres) on peut aussi se contenter d'un simple
PublishedExtract en bdd.

Le 11 juin 2015 16:54, Hugo Courtecuisse notifications@github.com a écrit
:

**Comment by DevHugo** [comment]
> Une solution serait donc de créer des classes style PublishedPart
> PublishedChapter PublishedExtract, liées à PublishedContent et qui
> implémentent les bonnes données.
> Le problème c'est que c'est un poil casse pied de faire ça juste pour la
> recherche et juste pour les tutos moyens/big.

Ça me parait pas évident, il faut implémenter plein de méthode, style, la méthode filter, order et tout. À mon avis, c'est pas viable.

> Sachant que finalement, cesont surtout les extraits qui comptent (et non
> les parties/chapitres) on peut aussi se contenter d'un simple
> PublishedExtract en bdd.

Mais on ne pourra jamais rediriger l'auteur sur le bon extrait (cf la remarque à partir du MAIS dans les derniers paragraphes). C'est quand même embêtant.

**Comment by artragis** [comment]
Pourquoi on ne pourrait pas? je passe ce soir sur le topic de la zep12 pour
te faire une proposition.

Le 11 juin 2015 17:10, Hugo Courtecuisse notifications@github.com a écrit
:

**Comment by DevHugo** [comment]
De quelle solution tu parle ?

**Comment by pierre-24** [comment]
Tu l'as surement déjà lue, mais _quid_ [de ça](http://django-haystack.readthedocs.org/en/latest/rich_content_extraction.html) ?

**Comment by DevHugo** [comment]
C'est le même souci, tu va pouvoir indexer le contenu du tutoriel mais quand l'utilisateur va faire la recherche. Tu va pas avoir accès à quelles parties du tuto est concernés. C'est un extract ? un chapter ? un parts ? lequel et ou ?

Le seul moyen d'avoir l'info, c'est d'indexés les modèle extract, parts, chapter, tutorials. Ce que je sais pas faire.

**Comment by pierre-24** [comment]
Je vois le problème. Et revenir en arrière en recréant la séquence Part/Chapter/Extract, ce serait complètement revenir en arrière et se ré-attacher le boulet qu'on avait soigneusement mis de coté (les appels à la bdd).

Fait ch*** ...

**Comment by DevHugo** [comment]
Peut-être que le truc @artragis va marcher on va voir.

**Comment by pierre-24** [comment]
Le problème, si j'ai bien suivi l'idée de mon collègue, ce serait de remettre un _subset_ des infos de chaque extrait en base de donnée (avec, j'imagine, un lien pour pointer dessus qu'on sache ou il est). Ça peut marcher comme ça peut marcher, mais ça laisse de coté le fait d'indexer les titres des parties/chapitres, et donc ce sera quand même limite.

C'est dommage, parce que tout ce qu'il te faut est dans le `manifest.json`, qui est de lui même une forme de base de donnée un peu particulière. Et effectivement, pas moyen de forger un `QuerySet` à la main, c'est vexant :/

**Comment by DevHugo** [comment]
Peut-être que la solution la plus simple est de passer à une autre librairie. 

Perso, j'ai vraiment pas envie de remettre les parts/chapter/index dans la base de données. Surtout pour ça.

**Comment by artragis** [comment]
Ma réponse https://zestedesavoir.com/forums/sujet/846/zep-12-refonte-du-principe-des-tutoriels-et-articles/?page=20#p60881

**Comment by DevHugo** [comment]
La solution est bonne et va marcher pour moi ! du coup, on fait quoi de `PublishedContent`, on l'indexe ou pas ?

**Comment by artragis** [comment]
Oui, c'est du coup publishedcontent que publishable qu'il faut indexer.

2015-06-11 19:23 GMT+02:00 Hugo Courtecuisse notifications@github.com:

**Comment by DevHugo** [comment]
Ça fessait quelques jours que j'y réfléchissait et je trouvais pas de solution satisfaisante. Bravo, à toi  @artragis. 'My bad' d'avoir pas cru en ta solution. Tu as mes excuses. Je me demande après, si garder Haystack et Solr est une bonne solution. Nos besoins ont changé et pour moi ça mérite de challenger la techno ! ^^

**Comment by pierre-24** [comment]
Considérons ça comme une rustine le temps de _challenger_ une meilleure techno. Parce que qui dis meiilleure techno dit les compétences techniques qui vont avec ;)

**Comment by DevHugo** [comment]
Comment on va faire pour l'introduction et la conclusion des chapitres et parties ?

**Comment by artragis** [comment]
- possibilité 1 : on l'abandonne silencieusement, ce sont des intro, il est
  peu probable qu'un élément intéressant de recherche s'y trouve
- possibilité 2: on crée des PublishedExtract avec les intro et on met les
  abolute_url égaux aux get_absolute_public_url des chapitre et parties
- possibilité 3: je sais pas

2015-06-12 10:39 GMT+02:00 Hugo Courtecuisse notifications@github.com:

**Comment by DevHugo** [comment]
- possibilité 4: on l'indexe avec le tutoriels et on renvoi vers le sommaire

**Comment by artragis** [comment]
Fais celle qui te va le mieux, j'ai l'impression que solr c'est déjà assez prise de tête, alors fais en sorte que ça soit simple pour toi.

**Comment by artragis** [comment]
Tu avances? Tu as besoin d'aide? Simplement de temps?

**Comment by DevHugo** [comment]
Je t'avoue que en se moment, c'est un peu chaud avec les études. Y'a pas de souci, si c'est pressé et que tu as du temps, fais le et je continuerai au pire.

**Comment by artragis** [comment]
Non, on a le temps, c'est juste que j'aime bien savoir où ça en est et si
ça bloque pour raison de manque de temps ou bien à cause de pb technique.

2015-06-16 11:17 GMT+02:00 Hugo Courtecuisse notifications@github.com:

**Comment by artragis** [comment]
Salut @DevHugo , as-tu un pb technique ou bien es-tu toujours en manque de temps?

**Comment by DevHugo** [comment]
J'avance doucement. Ça serait prêt pour la fin de la semaine, aprés faudrait bien tester, vu qu'on a pas vraiment de tests unitaires.

**Comment by artragis** [comment]
OK, merci ! Dis moi dès que je peux tester que je mettes ça sur mon
serveur. De même dis-moi les commandes à exécuter.

Le 29 juin 2015 13:49, Hugo Courtecuisse notifications@github.com a écrit
:

**Comment by artragis** [comment]
Comme je sais que tu n'as pas le temps en ce moment @DevHugo , tu peux nous faire un topo de ce qu'il reste à faire?

**Comment by artragis** [comment]
(voire faire une PR histoire qu'on corrige nous même les bugs qu'on découvrirait)

**Comment by DevHugo** [comment]
Comme dit dans le MP, il reste ça à faire:

> Pour la recherche en générale, ce qui manque:
> - Tester la migration et voir comment vous compter la faire.
> - Tester la commande Django permettant d'indexer le contenu.
> - Faudrait ajouter les tags dans les résultats de la recherche ou empêcher de rechercher dessus.
> - Je suis pas certain que ce que j'ai fait pour les Thread va fonctionner comme je le souhaite. En gros, je lance le thread pour indexer les données à la fin mais le souci est que si le thread principal se ferme avant que le thread d'indexation à finis. Le thread d'indexation va être tué par ngnix et du coup, on va se retrouver avec un quart de tutoriel indexés.
> - Pour l'instant, l'algo pour indexer les données ce résume à on supprime toutes les anciennes valeurs et on insère tout on utilise les ressources suivantes:
>   - IO: 2 + (2*number of containers) + number of extracts.
>   - Suppression dans la bd: 1+number of containers+number of extracts, Ajout dans la bd: 1+number of containers+number of extracts.
>   - La documentation
> - La suite de ligne 124 à 130 peut créé des doublons dans la table SearchIndexTag, faudrait corriger ça. Il faut avant l'insertion, tester si le tag existe, sinon l'ajouter. Lors de la suppression des données dans la table sur la ligne 100, il faut supprimer le tag à la main en testant si il n'impacte pas d'autre tutoriel.
> - Le css des résulats de la recherche n'est pas optimal et y'a quelques trucs à corriger.
> - On peut toujours merger dans la branche zep_12 et corriger après, y'a aucun souci avec ça.

**Comment by artragis** [comment]
> La suite de ligne 124 à 130 peut créé des doublons dans la table
> SearchIndexTag, faudrait corriger ça. Il faut avant l'insertion, tester si
> le tag existe, sinon l'ajouter. Lors de la suppression des données dans la
> table sur la ligne 100, il faut supprimer le tag à la main en testant si il
> n'impacte pas d'autre tutoriel.

lance la PR sur mon dépôt dès que tu te sens prêt, et je m'occuperai de ça
:)

Le 29 juillet 2015 14:00, Hugo Courtecuisse notifications@github.com a
écrit :

**Comment by artragis** [comment]
Je passe en mode "QA". Il y a du debug à faire et des optis à apporter mais ça devrait aller.

**Comment by artragis** [comment]
des choses à faire @pierre-24 ?

**Comment by pierre-24** [comment]
Oui, et ça vient :)

**Comment by Vayel** [comment]
Si la QA peut se faire sur l'instance d'artragis, sonnez-moi.

**Comment by pierre-24** [comment]
Bon. Tout compte fait, la copie du dépôt ce justifie et je n'ai rien à corriger.

**Comment by Vayel** [comment]
Du coup, il y a de la QA ?

**Comment by artragis** [comment]
on attend les petites modifs de la part de pierre mais tu peux déjà 
faire. Pour l'instant rien n'est automatique, donc si tu veux indexer un 
truc faut me le demander.

**Comment by pierre-24** [comment]
Comme je l'ai dit, j'avais pas lu le code dans son ensemble, donc je comprenait pas pourquoi le dépot entier était copié. En l'occurence, pour le moment, il n'y a pas moyen de faire autrement, du coup, je n'ai pas de modifications à apporter. J'ai bien une idée, mais c'est clairement une évolution, donc ça attendra.

_Let's go QA_ :)
