### ISSUE TITLE
Jsfidle

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#53]
Pas oublier que ça existe, pas oublier d'en tenir compte à la publication

**Comment by artragis** [comment]
Actuellement, c'est déjà possible de l'ajouter, je passe en need TU et need QA.

**Comment by pierre-24** [comment]
Eh bien ça ne fonctionne pas/plus (ou j'ai cassé quelque chose pendant mon travail sur la publication)

**Comment by pierre-24** [comment]
... Seconde option ;)

**Comment by artragis** [comment]
Selon le moment où tu feras ton push sur la publication, je regarderai ce qu'il s'est passé si tu veux.

**Comment by Eskimon** [comment]
Pour un article (j'ai pas testé pour un tuto) erreur 405 (Method Not Allowed) lorsque je clique sur valider pour la checkbox "activer jsfiddle" (adresse en cause : `/contenus/activer-js/`)

**Comment by pierre-24** [comment]
Merci :)

**Comment by artragis** [comment]
J'ai corrigé l'erreur de 405 et j'ai fait un test unitaire assez complet de la fonctionnalité.
Je passe en need QA.

**Comment by pierre-24** [comment]
Ah, merci :)

Par contre, je suis pas sur que ça marche si on le publie (il y a un argument `js=True` à mettre quelque part, de mémoire)

**Comment by artragis** [comment]
js_support? si c'est le cas, c'est déjà fait
https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views.py#L1252

2015-04-20 14:06 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by pierre-24** [comment]
Oui, mais je veux dire dans la commande `emarkdown` au moment de la publication: https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/utils.py#L303 ? 

Si tu me dis que ça marche, tant mieux, ceci dit :)

**Comment by artragis** [comment]
d'où le "need QA"...

**Comment by artragis** [comment]
j'ai testé, ça marche pas http://zds.francoisdambrine.me/tutoriels2/19/les-balises-audio-et-video-en-html5/

**Comment by pierre-24** [comment]
Je m'en doutais ;)

Voir `zds/tutorialsv2/utils.py` et la fonction `publish_content()`, y'a un paramètre à rajouter par là :)

**Comment by pierre-24** [comment]
Quand j'utilise la modale pour activer jsfiddle:
- Si je coche rien et que je clique sur "valider", j'ai une "MultiKeyErrror", ce qui n'as parfaitement aucun sens vu le test qui est fait o_O
- Et pas moyen d'activer jsfiddle (pareil, ça n'as absolument aucun sens !)

Voir http://zds.francoisdambrine.me/contenus/19/les-balises-audio-et-video-en-html5/

**Comment by artragis** [comment]
> Et pas moyen d'activer jsfiddle (pareil, ça n'as absolument aucun sens !)

ce bug est corrigé

> Si je coche rien et que je clique sur "valider", j'ai une "MultiKeyErrror", ce qui n'as parfaitement aucun sens vu le test qui est fait o_O

ce bug est corrigé

par contre le jsfiddle n'est PAS interprété dans les tutos en ligne http://zds.francoisdambrine.me/contenus/19/les-balises-audio-et-video-en-html5/

**Comment by pierre-24** [comment]
> par contre le jsfiddle n'est PAS interprété dans les tutos en ligne http://zds.francoisdambrine.me/contenus/19/les-balises-audio-et-video-en-html5/

Je sais, je sais. Je prend :) (vu #75, je dois retourner faire un tour dans la fonction de publication, et j'en profiterai pour voir si j'ai pas moyen d'implémenter simplement l'histoire avec les images)

**Comment by pierre-24** [comment]
Hop, on est normalement bon, ici. Vous pouvez QA comme suis:
- Créez un article
- Rajouter le JSFiddle `!(https://jsfiddle.net/tmjosu22/20/)` dans l'intro, la conclusion et un extrait
- ~~constatez que @Eskimon a bien travaillé et que c'est beau~~
- Vérifiez que le JSFiddle est interprété partout
- Publiez et faites la même vérification sur la version publique
- Faites la même vérification sur un tutoriel, en particulier au moins un moyen tuto (il faut appeller la template `view/container.html`).

Par contre, ça ne marche évidement pas dans le PDF/EPUB/..., mais ça, c'est pas notre problème, c'est la ZEP-05 :)

**Comment by Eskimon** [comment]
Pourquoi la phrase est rayée ? J'ai pas bien travaillé et/ou c'est pas beau ? :(

**Comment by artragis** [comment]
Je sais pas, mais en tout cas ça marche \o/

2015-05-04 8:09 GMT+02:00 Eskimon notifications@github.com:

**Comment by pierre-24** [comment]
> Pourquoi la phrase est rayée ? J'ai pas bien travaillé et/ou c'est pas beau ? :(

C'est très beau, mais ça ne fait pas avancer la QA ^^

(pour la petite histoire, c'est le dernier JSFiddle de ton tuto sur les vidéos HTML5, d'ou le point)

**Comment by Eskimon** [comment]
Compris !

Et tfacon artragis dis "ca marche" donc ca me semble bien avancé !! (et on sait pas, ptet que la beaute du tuto l'a aide a QA  !?)

**Comment by artragis** [comment]
je ferme bravo @pierre-24 pierre et @Eskimon . (je vous ping pour vous punir de vos disputes, nah)
