### ISSUE TITLE
Gestion des auteurs

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#54]
... Pour pas oublier que ça existe ;)

**Comment by artragis** [comment]
En étant plus précis?

**Comment by pierre-24** [comment]
Ajouter/supprimer un auteur, et pas oublier de gérer le bordel correspondant avec les galeries.

**Comment by artragis** [comment]
ok, je m'assigne donc.

**Comment by artragis** [comment]
ça avance, un TU plus le back de l'ajout d'auteur,
reste à faire
- intégration de l'ajout
- création de la suppression de l'auteur
- TU de la suppresion
- intégration de la suppression
- QA !!!

**Comment by pierre-24** [comment]
Nice ;)

**Comment by artragis** [comment]
~~intégration de l'ajout~~

**Comment by artragis** [comment]
- ~~intégration de l'ajout~~
- ~~création de la suppression de l'auteur~~
- ~~TU de la suppresion~~

j'ai un problème sur l'intégration de la suppression.
ensuite il faudra faire la QA.

**Comment by artragis** [comment]
Ca fonctionne MAIS:
- il faut de la QA
- j'aimerais bien que quelqu'un qui s'y connait un peu en bonnes pratique du front vienne voir mon code car là c'est moche je pense (ping @sandhose @situphen)

**Comment by Situphen** [comment]
Pourquoi passer par du JS ? On fait très bien sans actuellement.

**Comment by artragis** [comment]
Parce que j'ai voulu simplifier les choses côté back et du coup je me suis
fait avoir parce que les données envoyées sont différentes. J'ai néanmoins
réussi à rechanger des trucs dans le <button> pour que ça marche.

**Comment by artragis** [comment]
J'ai enlevé le JS, plus qu'à faire la QA (ça prend 5/6 minutes histoire de voir que le mp d'ajout est bien reçu, que les droits sont les bons (même sur les galleries, ce qui me fait penser qu'à tout les coups c'est pas encore le cas oO)

**Comment by artragis** [comment]
Le bug des galleries devrait être corrigé maintenant, désolé de m'en être rendu compte si tard.

**Comment by pierre-24** [comment]
Rapport de QA
- Ajouter un auteur, OK
- On ne peut pas se supprimer des auteurs soit-même. Bien :) (peut-être un petit `messages.error()` ?)
- On peut virer un auteur. Et en plus, il perd son droit d'accès à la galerie, OK
- On peut ajouter un _bot_ comme auteur, **pas OK** (oui, c'est à nous à gérer cette partie coté _back_, le fait que le formulaire donne la possibilité de sélectionner un bot dans la liste n'est pas de notre ressort, par contre)
- On a bien le "vous êtes seul" quand on est seul auteur, OK
- Le mec viré à bien plus accès ni au tuto (403) ni à la galerie (403)

C'est presque bon, donc :)

**Comment by pierre-24** [comment]
(et oui, j'ai bien recu le MP d'ajout, donc ça c'est parfait. Pourquoi pas un MP de suppression, par contre ?)

**Comment by artragis** [comment]
> On peut ajouter un _bot_ comme auteur, _pas OK_ (oui, c'est à nous à gérer
> cette partie coté _back_, le fait que le formulaire donne la possibilité de
> sélectionner un bot dans la liste n'est pas de notre ressort, par contre)

Ok, je vois très bien comment faire ça. idem, ce week end.

> (et oui, j'ai bien recu le MP d'ajout, donc ça c'est parfait. Pourquoi pas
> un MP de suppression, par contre ?)

je n'étais pas sûr qu'il fallait en mettre.

2015-04-30 16:13 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by pierre-24** [comment]
> je n'étais pas sûr qu'il fallait en mettre.

Moi non plus, c'est une suggestion. Oh, et si t'y pense, j'aime bien quand les MPs sont rangés là : https://github.com/artragis/zds-site/tree/zep_12_double_stack/templates/tutorialv2/messages (ensuite, on les appellent avec `render_to_string()`, et c'est magique :)

L'avantage le plus évident, c'est que les mecs qui corrigent l'orthographe et mettent en forme lesdits MP n'ont plus à chercher dans le code ou c'est, et on évite d'avoire 20 lignes identéés, coupées n'importe ou et des `\n` qui traînent :p

**Comment by artragis** [comment]
+1000 ! tu as vraiment pensé à tout #ilovezep12

**Comment by artragis** [comment]
> On peut ajouter un _bot_ comme auteur

corrigé

> j'aime bien quand les MPs sont rangés là 

corrigé

Je n'ai toujours pas mis de mp de suppression.

**Comment by pierre-24** [comment]
Pour moi, question QA, c'est bon, ici :)

**Comment by artragis** [comment]
Ok, je ferme
