### ISSUE TITLE
Conversion tuto <-> article

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#55]
Parce que ça a été demandé à plusieurs reprises.

Théoriquement possible (c'est juste une méta-information à changer), un peu plus _tricky_ en pratique (il faut vérifier qu'on a pas de conteneur dans le conteneur principal et vérifier que le modèle tient). En gros, pas très compliqué à mettre en place. La question est surtout de savoir si on le considère ou si on le laisse comme "évolution future".

**Comment by Eskimon** [comment]
Evolution future.

**Comment by pierre-24** [comment]
Pour.
