### ISSUE TITLE
Commentaire sur les contenus

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#57]
Parce que #56 ne l'as pas fait ;)
- [x] Pagination (mauvais template) (#80)
- [x] +1/-1 
- [x] Ajout de note
- [x] Modification (vue prête mais manque le template)
- [x] "signaler"(#96)
- [x] masquer
- [x] citer
- [x] "aucun commentaire" et les deux barres de paginations qui sont pas censé apparaître si elles sont vides
- [x] inscrire les auteurs au flux de commentaires de leurs contenus à la publication
- [x] Notifications
- [x] Optimiser les requêtes sur les permissions

**Comment by artragis** [comment]
J'ai pas mal avancé sur la question. Il ne manque plus que : 
- la pagination
- les TU
- les alertes.

**Comment by pierre-24** [comment]
Awesome :)

**Comment by pierre-24** [comment]
J'ai fixé ton test. J'aime pas quand Travis râle :p 

(par contre, ça te coûtera un petit `manage.py migrate`)

**Comment by artragis** [comment]
merci (j'allais le faire aujourd'hui)

**Comment by artragis** [comment]
Voilà, plus qu'à faire la QA. Et si quelqu'un a envie de tester plus en profondeur (notamment pour l'antispam, j'ai pas de TU).

**Comment by pierre-24** [comment]
Bon, je sens que je vais faire de la QA, ce matin ;)

(c'est déployé sur ton serveur ou je fais ça à la maison ?)

**Comment by artragis** [comment]
Sur mon serveur ^^

**Comment by poulp** [comment]
J'ai cette erreur quand j’envoie un commentaire (en local) : 

```
Request Method: GET
Request URL: http://localhost:8000/contenus/reactions/ajouter/?page=1

Traceback:
File "/home/alex/programmation/github/zdsenv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/alex/programmation/github/zdsenv/local/lib/python2.7/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/home/alex/programmation/github/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  29.             return bound_func(*args, **kwargs)
File "/home/alex/programmation/github/zdsenv/zds-site/zds/member/decorator.py" in _can_write_and_read_now
  27.         return func(request, *args, **kwargs)
File "/home/alex/programmation/github/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  25.                 return func.__get__(self, type(self))(*args2, **kwargs2)
File "/home/alex/programmation/github/zdsenv/zds-site/zds/member/decorator.py" in dispatch
  66.         return super(LoggedWithReadWriteHability, self).dispatch(*args, **kwargs)
File "/home/alex/programmation/github/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  29.             return bound_func(*args, **kwargs)
File "/home/alex/programmation/github/zdsenv/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)
File "/home/alex/programmation/github/zdsenv/local/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  25.                 return func.__get__(self, type(self))(*args2, **kwargs2)
File "/home/alex/programmation/github/zdsenv/zds-site/zds/member/decorator.py" in dispatch
  56.         return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)
File "/home/alex/programmation/github/zdsenv/zds-site/zds/tutorialv2/mixins.py" in dispatch
  301.         self.public_content_object = self.get_public_object()
File "/home/alex/programmation/github/zdsenv/zds-site/zds/tutorialv2/views.py" in get_public_object
  1799.             .filter(content_pk=int(pk))\

Exception Type: TypeError at /contenus/reactions/ajouter/
Exception Value: int() argument must be a string or a number, not 'NoneType'

```

**Comment by artragis** [comment]
Corrigé.

**Comment by pierre-24** [comment]
Tout d'abord, très bon travail, et te laisse surtout pas abatre par ce qui va suivre !
- +1 et -1 fonctionnent <3
- J'imagine que c'est normal que les notifs marchent pas encore
- La pagination ne fonctionne pas: http://zds.francoisdambrine.me/articles2/3/philae-a-la-recherche-de-lorigine-de-la-chiralite-du-monde/#p24 (contient plus de 20 commentaires, et si je tente d'en rajouter, je tombe sur une 404 sur la page 2)
- Régler le comportement de "signaler", "masquer"citer" (le premier et le second finissent par renvoyer sur une 404, le dernier ne fait rien)
- "éditer" ne fonctionne pas (manque une page)
- Quand on balance un message vide, on se mange `TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'`, et dans ce cas-ci, il y avait une page qui permettait de faire des éditions et tout le bousin. Manque une page, quoi ;)
- Coté _front_, y'a encore une ou deux bricoles, quand même  ("aucun commentaire" et les deux barres de paginations qui sont pas censé apparaître si elles sont vides) : 

![screenshot from 2015-04-30 09 34 53](https://cloud.githubusercontent.com/assets/7889675/7413734/2b46cd6a-ef1c-11e4-935d-931d0eab803b.png)

... Mais une fois encore, énorme boulot, donc merci !

**Comment by artragis** [comment]
Merci, je règle ça ce weekend.

**Comment by artragis** [comment]
> J'imagine que c'est normal que les notifs marchent pas encore

yep, tout est enregistré en bdd, mais c'est pas encore intégré au compteur de notif.

**Comment by artragis** [comment]
> La pagination ne fonctionne pas: http://zds.francoisdambrine.me/articles2/3/philae-a-la-recherche-de-lorigine-de-la-chiralite-du-monde/#p24 (contient plus de 20 commentaires, et si je tente d'en rajouter, je tombe sur une 404 sur la page 2)

j'avoue que je ne comprenais pas pourquoi.

Puis j'ai vu que dans ta pr qui fixait mon test, tu faisais
`self.success_url = reaction.get_absolute_url()`
si nous allons voir `get_absolute_url`, que nous dit-il?
`page = int(ceil(float(self.position) / settings.ZDS_APP['forum']['posts_per_page']))`

Et la pagination, comment est-elle faite?̀

``` python
paginator = Paginator(ContentReaction.objects.filter(related_content=self.object),
                              settings.ZDS_APP["content"]["notes_per_page"])
```

or, `settings.ZDS_APP["content"]["notes_per_page"]` vaut 25 là où `settings.ZDS_APP['forum']['posts_per_page']` vaut 20. 

Le bug est donc expliqué.
Que dois-je faire?

**Comment by pierre-24** [comment]
C'est ce qu'on appelle un copier/coller foireux ^^

La solution, c'est de mettre `settings.ZDS_APP["content"]["notes_per_page"]` partout, bien entendu ;)

**Comment by artragis** [comment]
Bon, c'est bon. Le seul problème qui reste sur la pagination c'est l'abscence des nombres (on a juste le "précédent/suivant"

**Comment by pierre-24** [comment]
T'y est presque, crois moi. Juste que la template de pagination s'attend à une variable `pages` et une variable `nb`, et si j'ai bien lu, tu ne les donne pas. [Regarde comment c'est fait pour les aides](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views.py#L1303-L1304) et le procédé doit être très semblable :)

**Comment by pierre-24** [comment]
(oups, correction, c'est juste `pages` que tu donne pas, donc c'est même encore plus simple)

**Comment by artragis** [comment]
et voilà !

Pour ce bug là : 

> Quand on balance un message vide, on se mange TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()', et dans ce cas-ci, il y avait une page qui permettait de faire des éditions et tout le bousin. Manque une page, quoi ;)

tu l'as encore, même après ta PR ou bien c'est bon?

**Comment by pierre-24** [comment]
> tu l'as encore, même après ta PR ou bien c'est bon?

J'ai pas touché à ça, et je t'explique pourquoi: en _prod_, quand on clique sur "éditer", on arrive sur une page séparée. Ça veut dire que cette page doit exister chez nous aussi (et donc qu'il faut faire une template pour ça). Pareil, en prod, quand on met un message vide, on tombe sur cette page et un zoli message d'erreur. Je t'invite à aller tenter de commenter le premier article/tuto qui te passe sous la main pour voir de quoi je parle :)

En prod, il s'agit de [cette template là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorial/comment/edit.html) quand on édite et de [cette template là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorial/comment/new.html) quand on crée un nouveau message mais qu'un truc ce passe (genre une personne a commenté avant).

**Comment by pierre-24** [comment]
Par ailleurs, j'ai réussi à trouver d'ou venait le fait que la toolbar django ne s'affichait pas sur les contenus en lignes (voir #79). Ce qui m'as permis de découvrir qu'il fallait faire un peu de `prefetch_all()` sur les commentaires, à mon avis:

![screenshot from 2015-05-01 18 29 36](https://cloud.githubusercontent.com/assets/7889675/7438330/b403fcd0-f030-11e4-873a-f8899fb13b2c.png)

Et là, c'est avec 5 commentaires, je te laisse imaginer ce que ça donne sur la page à 25 commentaires :o (je la trouvais un peu lente sans raison, c'est pourquoi j'ai creusé ça). Ça rajoute à peu près 4 requêtes par commentaire.

**Comment by artragis** [comment]
J'ai réussi à faire baisser la charge en terme de tuto mais les likes et dislike prennent toujours autant. Il faudrait voir sur la branche de dev si c'est aussi comme ça.

**Comment by pierre-24** [comment]
Leur charge augmente aussi avec le nombre de commentaire, mais j'ai pas regardé si c'était les likes/disliikes qui faisais ça.

**Comment by artragis** [comment]
En fait avant ma PR, chaque commentaire générait trois requêtes
- récupération de l'auteur
- récupération du like de l'utilisateur courant
- récupération du diskile de l'utilisateur courant si le précédent 
  n'était pas trouvé

j'ai fait une jointure pour trouver l'auteur dès le départ, du coup j'ai 
baissé le nombre de requêtes.
J'ai aussi évité la répétition de requête sur les permissions.
Mais le problème du like/dislike est un poil plus complexe que ça.

**Comment by pierre-24** [comment]
Si t'y arrive pas, c'est pas trop grave non plus, puisque après vérification le code en _prod_ le fait aussi. Mais quittes à ratatiner les perf's du code précédent, autant mettre toutes les chances de notre coté ! (ceci étant dit, il semblerai qu'on en ressort grandement gagnant dans tout les ca). Merci, en tout cas !

**Comment by pierre-24** [comment]
Par contre, il y a deux types de requêtes qui reviennent en permanance:

``` sql
SELECT ••• FROM `member_profile` WHERE `member_profile`.`user_id` = 3 LIMIT 21
```

et 

``` sql
SELECT ••• FROM `auth_permission` INNER JOIN `auth_user_user_permissions` ON ( `auth_permission`.`id` = `auth_user_user_permissions`.`permission_id` ) INNER JOIN `django_content_type` ON ( `auth_permission`.`content_type_id` = `django_content_type`.`id` ) WHERE `auth_user_user_permissions`.`user_id` = 3 ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC
```

Donc à mon avis, y'a moyen de choper les permissions et le profile.

**Comment by artragis** [comment]
Je pense avoir une solution je la teste le plus rapidement possible.

**Comment by artragis** [comment]
Pour les permissions, j'en ai logiquement enlevé une bonne partie, mais 
en fait il arrive que certaines soient encore checkées plusieurs fois.

Je regarde ça de plus prêt.

**Comment by artragis** [comment]
Nouvelle amélioration du nombre de requête observable. c'est perfectible mais on est sur le bon chemin.

**Comment by pierre-24** [comment]
Le plus "étonnant", dans tout ça, [c'est que le code original](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorial/views.py#L979) dit ceci:

``` python
notes = Note.objects.filter(tutorial__pk=tutorial.pk).order_by("position").all()
```

Alors qu'on en est déjà à [ça](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views.py#L282-L288):

``` python
  paginator = Paginator(ContentReaction.objects
                              .select_related('author')
                              .select_related('editor')
                              .prefetch_related('author__post_liked')
                              .prefetch_related('author__post_disliked')
                              .filter(related_content=self.object),
                              settings.ZDS_APP["content"]["notes_per_page"])
```

(et ce qu'il y a en dessous)

Autrement dit, le nombre hallucinant de requêtes n'as jamais choqué personne, et logiquement, on fait de toute façon mieux que ce qui existe déjà ^^

**Comment by artragis** [comment]
là on fait clairement mieux, en effet ^^ .
Le dernier problème qu'il reste ce sont les permissions qui sont 
calculées à chaque fois.

**Comment by artragis** [comment]
> J'imagine que c'est normal que les notifs marchent pas encore

done

**Comment by pierre-24** [comment]
Yeaaaaaaaaaaaaaaaaaaaaah !

**Comment by artragis** [comment]
j'ai édité le premier message pour qu'il y ait un aperçu de ce qu'il reste à faire.

**Comment by pierre-24** [comment]
Bien :)

Bon, par contre, j'ai toutes mes notifs en double (et j'arrive pas à faire partir la deuxième), mais c'est peut être parce que je devrais repartir sur une nouvelle base (j'espère!). Et sinon, j'imagine que c'est normal, mais elles apparaissent pas dans "toutes les notifications" ;)

**Comment by artragis** [comment]
> j'ai toutes mes notifs en double (et j'arrive pas à faire partir la deuxième)

/!\ En fait, jusqu'à aujourd'hui 13h30 chaque nouveau message créait un ContentRead du coup toutes les notifications d'avant aujourd'hui sont en double. Il faut tester avec un autre utilisateur pour que ça soit plus correct. 

> Et sinon, j'imagine que c'est normal, mais elles apparaissent pas dans "toutes les notifications" ;)

Non. Faut que je regarde.

**Comment by pierre-24** [comment]
Ah, ok. Je vais voir si il y a moyen de _dropper_ ma table `ContentRead`, alors. Et du coup, pas oublier d'abonner les auteurs aux notifs de leurs propres contenus ;)

**Comment by artragis** [comment]
Je viens de nettoyer la table de mon instance en ligne. On peut tester comme il faut maintenant.

**Comment by pierre-24** [comment]
... J'allais te le proposer ;)

**Comment by pierre-24** [comment]
Problème: je viens de poster un commentaire sur http://zds.francoisdambrine.me/articles2/3/philae-a-la-recherche-de-lorigine-de-la-chiralite-du-monde/?page=2#comments avec `user`, sauf qu'il n’apparaît pas du tout. Ce que je te propose, c'est carément une RàZ de la base de donnée et du contenu de `/contents-private` et `/contents-public`. Pour être sûr :o

**Comment by artragis** [comment]
ok, ce soir.

**Comment by pierre-24** [comment]
Ok, je vais en profiter pour stocker tout les ZIPs pour les réimporter une fois que ce sera fait :)

(j'adore cette fonctionnalité <3 )

**Comment by artragis** [comment]
Ok ^^

**Comment by artragis** [comment]
RAZ fait.

**Comment by pierre-24** [comment]
Bon, pour les notifs, c'est à priori OK, et pour les perfs', c'est peut-être une impression, mais j'ai l'impression que ça va un peu mieux, donc gg :)

**Comment by pierre-24** [comment]
Whoops, qu'est ce qui se passe ?

![screenshot from 2015-05-05 15 02 02](https://cloud.githubusercontent.com/assets/7889675/7480608/b0cc9dd8-f337-11e4-9464-123eaf080747.png)

Je faisais répondre admin et user, donc ça ne peut pas arriver :o

**Comment by artragis** [comment]
> Et sinon, j'imagine que c'est normal, mais elles apparaissent pas dans "toutes les notifications" ;)

La page "toutes les notifications" ne prend en compte que les forums. C'est une évolution un peu trop complexe à mettre en place pour l'instant pour que je joue à ce jeu là. 

> Whoops, qu'est ce qui se passe ?

Corrigé, problème d'ordre avec le select_related il me réordonait les messages autrement. Mais là c'est bon.

Et j'ai mis la blinde de TU. Donc dès que tu as tout qatisé, on pourra dépiler.

**Comment by pierre-24** [comment]
Alors:
- Notifs: OK quoiqu'il arrive
- Performance, j'ai l'impression que ça va beaucoup mieux. Le nombre de requête est toujours énorme, mais j'ai l'impression quand même que le temps de traitement est plus rapide. À vérifier
- Par contre, après une interminable partie de ping-pong (la prochaine fois, je code un script), je suis enfin arrivé à la deuxième page:
  
  ![screenshot from 2015-05-06 14 03 03](https://cloud.githubusercontent.com/assets/7889675/7499975/d4e6e5e0-f3f8-11e4-81b4-ec8a5805a645.png)
  
  Donc là, il y a pas les barres du paginator :( (par contre, les notifs balancent bien à la page 2)

**Comment by artragis** [comment]
il semblerait que "le bon template" n'est pas si bon que ça en fait,

**Comment by pierre-24** [comment]
Tu t'arrange avec les gens dudit _paginator_ ... @Situphen ?

**Comment by Situphen** [comment]
Je sais pas trop comment ça fonctionne ! Il faut regarder comment c'est fait dans le module des membres ;)

**Comment by artragis** [comment]
on peut aussi jouer avec pagination.part.html, non?

**Comment by Situphen** [comment]
bah je pense pas

ping @GerardPaligot

**Comment by GerardPaligot** [comment]
L'issue est un peu longue. On m'explique pourquoi le ping ?

**Comment by artragis** [comment]
En gros on arrive pas à réutiliser les briques de base pour faire une 
pagination cohérente avec le reste du site.

**Comment by GerardPaligot** [comment]
Vous avez tenté d'utiliser `ZdsPagingListView` (la dernière version par rapport au dépôt officiel) ?

**Comment by artragis** [comment]
Non car notre vue est composite : on a un contenu (donc un DetailView 
avec pour modèle PublishableContent) qui affiche une liste de 
ContentReaction.

**Comment by GerardPaligot** [comment]
Malheureusement, je ne sais pas comment fonctionne les vues composites. Qu'est ce que vous avez tenté de faire et qu'est ce que vous avez comme résultat pour l'instant ?

**Comment by artragis** [comment]
on la faisait "old way" et sans preview du dernier message de la page 
précédente. On instancie un Paginator et on joue avec. Ensuite on passe 
ça dans pagination.part.html
mais on nous a dit que c'était mieux de passer dans paginator.html mais 
ça marche pas.

**Comment by GerardPaligot** [comment]
Ok, vous avez essayé d'utiliser l'ancien paginator avec le nouveau template ? Il faut utiliser le nouveau paginator avec le nouveau template.

**Comment by pierre-24** [comment]
J'ai vu, je vais essayer de faire ça vite fait bien fait.

**Comment by GerardPaligot** [comment]
Je vous aiderais bien mais impossible d'installer GeoIP sur ma machine que j'ai pour l'instant. Je ne peux pas lancer votre branche.

**Comment by pierre-24** [comment]
> Je vous aiderais bien mais impossible d'installer GeoIP sur ma machine que j'ai pour l'instant. Je ne peux pas lancer votre branche.

GeoIP ayant disparu de `dev`, ça devrait arriver par ici à un moment ou un autre. Par ailleurs, je me suis occupé de la pagination (#91), donc à une QA près, c'est bon :)

**Comment by artragis** [comment]
citation + hide OK

**Comment by artragis** [comment]
edition OK. Il ne me reste plus qu'à faire les alertes. Mais j'avoue être un peu dans le flou pour l'instant à ce propos.

**Comment by artragis** [comment]
et logiquement les auteurs sont inscrits à leur propre tuto.

**Comment by artragis** [comment]
Et voilà pour les alertes, par contre faut que je leur fasse un TU.

Bon test à tous.

**Comment by artragis** [comment]
TU ajouté, 100% terminé, plus qu'à faire la QA de toutes les cases.

bon test à tous.

**Comment by pierre-24** [comment]
GG, en tout cas :)

Rapport de QA (sur ton serveur)
- Le bouton citation ne rajoute pas les `>` et l'attribut `source:`
- Le bouton "éditer" n’apparaît pas pour _user_ (un problème de droits qui foirent, parce que c'est possible pour admin)
- Vérifier en prod' qu'on peut signaler deux fois un même message (pas sur)
- Quand on signale, le message de signalement n'apparait pas pour l'admin qui arrive dessus, alors que c'est le cas pour les forums. Du coup on peut pas "résoudre l'alerte" ^^
- Quand _admin_ édite le message de _user_, il ne peut pas le faire (la _textarea_) est grisée. Le bon comportement, c'est qu'il puisse le faire mais qu'il aie droit à un message "c'pas votre commentaire, alors faites gaffe" (voir en prod')
- On a `Masqué par None` quand on masque un message
- À priori, le "+1" est effectué quand on clique dessus, mais il ne s'affiche plus (j'ai testé en local pour vérifier que c'était pas le serveur, mais non). Le pouce reste gris foncé et devient pas vert. Pareil pour "-1"
- Sur le forum, un utilisateur peut masquer son propre message (voir [ici](http://zds.francoisdambrine.me/forums/sujet/5/sujet-de-test/?page=1#p15)).
- Sur le forum, on a également des boutons "voir" et "démasquer" en tant qu'admin:
  ![screenshot from 2015-05-13 07 30 07](https://cloud.githubusercontent.com/assets/7889675/7609566/f15e4d32-f941-11e4-9e80-706176f70aef.png)

**Comment by artragis** [comment]
> On a Masqué par None quand on masque un message

je le fixe rapidement

> Le bouton citation ne rajoute pas les > et l'attribut source:

Je le fixe rapidement

> À priori, le "+1" est effectué quand on clique dessus, mais il ne
> s'affiche plus (j'ai testé en local pour vérifier que c'était pas le
> serveur, mais non). Le pouce reste gris foncé et devient pas vert. Pareil
> pour "-1"

Celui là je comprends pas pourquoi.

Pour le reste c'est assez ardu à faire. Je pensais que les templates
étaient bien fait mais en fait non.

Tu compares souvent au forum, est-on sûr qu'en prod sur les **tuto** on a
le comportement que tu décris?

**Comment by pierre-24** [comment]
Je t'avoue que je compare au forum pour deux raison: 1) la flemme de faire la série validation/publi pour un tuto chez toi et 2) parce que c'est là que la _template_ est censée être implémentée de manière complète.

Ceci étant dit, je viens d'aller essayer, et tout ce que j'ai mis dans ma liste est possible pour un article :)

On peut bien mettre plusieurs alertes sur un même message, par contre, donc ça c'est pas un bug:

![screenshot from 2015-05-13 07 52 58](https://cloud.githubusercontent.com/assets/7889675/7609817/1042696a-f945-11e4-913e-6409e41c4a12.png)

**Comment by artragis** [comment]
Ok, donc là j'ai clairement besoin d'aide !

**Comment by pierre-24** [comment]
Je vais regarder pour t'aider :)

**Comment by artragis** [comment]
Merci :)

2015-05-13 14:08 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by pierre-24** [comment]
Bon, j'ai pas fait autant que je le voulais, mais j'ai au moins réglé le signalement, la prévisualisation, l'édition (une sombre histoire d'antispam) et le fait de pouvoir masquer ses propres messages.

Ce que j'ai pas fait:
- TU pour tout ça (mais peut-être que c'est déjà fait, parce qu'on tape dans la pure intégration)
- Le bouton "démasquer" (suffit de rajouter ce qu'il faut dans `UpdateNoteView`)
- L'histoire des +1/-1, que j'ai pas creusé (je parie que la solution est toute bête).

Bref, ça va déjà mieux :)

**Comment by artragis** [comment]
Je m'occupe des +1/-1

Pour les TU, il faut juste ajouter celui sur le "démasquer", les autres suffisent.

**Comment by artragis** [comment]
> L'histoire des +1/-1, que j'ai pas creusé (je parie que la solution est toute bête).
> 
> À priori, le "+1" est effectué quand on clique dessus, mais il ne s'affiche plus (j'ai testé en local pour vérifier que c'était pas le serveur, mais non). Le pouce reste gris foncé et devient pas vert. Pareil pour "-1"

done.

**Comment by pierre-24** [comment]
En effet, les +1/-1 fonctionnent à nouveaux.

Bon, par contre, hier, j'ai voulu aller trop vite, donc j'ai remis `perms_change=perms.tutorial.change_tutorial` [là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/templates/tutorialv2/view/content_online.html#L187) et j'aurais pas du, puisque ça reblombe les perfs' (oups). Ce que je propose, c'est un `{% set perms.tutorial.change_tutorial as perms_change %}` en dehors de la boucle for (genre juste avant) et ça devrait aller beaucoup mieux.

Soit dit en passant, la template qui gère l'affichage des commentaires fonctionne un peu trop bien. Ainsi, tu as systématiquement remplacé `{% if perms_change %}` par `{% if message.pk in messages_machin_truc %}`, sauf que les deux n'ont pas la même signification dans tout les cas. Du coup, quand `user` tente de masquer son commentaire, on lui demande pourquoi il veut masquer son message, alors que cette _modal box_ est réservée à l'admin:

![screenshot from 2015-05-14 11 33 11](https://cloud.githubusercontent.com/assets/7889675/7635112/0ae995b8-fa2d-11e4-8b9c-eb9c6f2bbf6d.png)

Pour "démasquer", je regarderais ce soir (et limite, tout ça aussi, si tu ne l'as pas fait entretemps)

**Comment by pierre-24** [comment]
EDIT: voir même un `{% set is_staff as perms_change %}`, en fait :)

**Comment by pierre-24** [comment]
Et soit dit en passant, le dernier message de la page précédente n'est pas (plus?) marqué comme tel:

![screenshot from 2015-05-14 11 38 27](https://cloud.githubusercontent.com/assets/7889675/7635230/cb2002c2-fa2d-11e4-92a0-593280697b95.png)

(http://zds.francoisdambrine.me/articles2/5/les-chroniques-du-libre-le-mozilla-science-lab/?page=2#p34)

**Comment by artragis** [comment]
J'ai vu mais je ne sais comment ça se change ça.

**Comment by artragis** [comment]
mmmhhh. je vois, j'étais persuadé du contraire.

**Comment by artragis** [comment]
> |{% set perms.tutorial.change_tutorial as perms_change %}| en dehors 
> de la boucle for (genre juste avant) et ça devrait aller beaucoup mieux.
> Je m'en occupe.

**Comment by pierre-24** [comment]
Hop et hop, _two in a row_ !

(bon, par contre, je suis grillé pour la QA)

**Comment by Vayel** [comment]
Ca se passe comment la QA ici ?

**Comment by artragis** [comment]
tout semble bon, je clos.
