### ISSUE TITLE
Télécharger contenus "supplémentaires"

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#58]
PDF, HTML, archive, ...

Parce que #56 ne l'as pas fait ;)
# TODO list
- [x] Implémentation du code
- [x] récupération des images (dont les SVG, voir #28)

**Comment by artragis** [comment]
ping @firm1 et @kje pour ça.

**Comment by firm1** [comment]
Faudrait voir si @kje a eu le temps de faire l'assembleur à partir du manifest.

**Comment by pierre-24** [comment]
Bon, c'est fait en grosse partie.

Évidement, comme j'ai pas implémenté la partie "rapatrier les images", ça marche pas pour les contenus qui ont des images (la génération du PDF plante). Vous pouvez déjà tester, donc, mais il reste un morceau à faire.

**Comment by pierre-24** [comment]
(et évidement, moi, je demande à pandoc de faire sa popotte, ce qui se passe après, c'est ZEP-05 ;) )

PS: @kje, c'est @GerardPaligot

**Comment by GerardPaligot** [comment]
On me ping ?

**Comment by artragis** [comment]
@pierre-24 , @kje s'appele christophe, @GerardPaligot s'appelle andr0 (bah quoi?)

c'est surtout que sur gh kje ne pointe pas vers notre kje à nous mais sur un inconnu.

**Comment by GerardPaligot** [comment]
@pierre-24 Tu me prends pour le fantôme ?! :O

**Comment by pierre-24** [comment]
Mais j'arrête pas de vous confondre :'(

**Comment by GerardPaligot** [comment]
D'un côté, c'est un fantôme qui se fait bouffer par un palet de hokey sur glace et qui s'appelle Kje. De l'autre, un magnifique robot tout option qui contrôle le monde, Andr0 alias moi GerardPaligot.

C'est super simple, non ? ^^

Plus sérieusement, je ne sais pas comment c'est possible de nous confondre. On a même pas un pseudo qui se ressemble. x)

**Comment by pierre-24** [comment]
En fait, ce qui me perturbe, c'est que aucun de vous deux n'as le même pseudo sur GH et sur ZdS et pas le même avatar non plus. Du coup, je passe ma vie à oublier qui est qui et qui fait quoi.

**Comment by GerardPaligot** [comment]
Ah. Malheureusement, j'utilise GitHub pour des raisons professionnelles aussi. Je ne peux donc pas le changer en Andr0 et mettre mon avatar. Désolé mon vieux. :)

**Comment by Vayel** [comment]
Qu'est-on censé pouvoir télécharger ? Je n'ai que "Archive" et "Markdown" pour l'auteur (admin) et "Archive" pour user. http://zds.francoisdambrine.me/tutoriels2/44/qa58/

**Comment by pierre-24** [comment]
Alors, deux choses sont à prendre en compte ici:
1. Théoriquement, quand tout va bien, tu peux télécharger "archive", "HTML", "PDF", "EPUB" et "Markdown" (mais uniquement quand t'es admin pour ce dernier, je pense que c'est juste pour faire des tests, celui là). 
2. MAIS (!), parce que le machin qui fait ça, pandoc, est ultra-lourd à installer (parce qu'il a LaTeX en dépendance), artragis ne l'as pas mis en place sur son serveur pour le moment. En plus de ça, la fonctionnalité est pas encore complètement remise en place, à cause des images (je dois regarder).

Conclusion, tu vois ce qu'il y a à voir, mais pas encore de QA à faire pour le moment.

**Comment by artragis** [comment]
pour l'instant : le téléchargement du zip. quand tu es membre, le .md et 
le .zip quand tu es staff.

**Comment by pierre-24** [comment]
Bon, voilà qui est fait.

# Note de QA

**c'est impossible à tester sur le serveur actuellement, parce que pandoc est une dépendance très lourde, vous devez tester en local avec la pile logicielle complète de ZdS**
- Créer un article. Pour introduction et conclusion, placez des images. Tout ce à quoi vous pourriez penser: images qui existent, qui existent pas, SVG, PNG, d'internet ou d'une galerie. Tout.
- Créer un extrait et faire de même.
- Valider le machin et vérifier que le PDF est généré (c'est en général le test qui bloque). Vérifier aussi que les autres contenus le sont bien (mais ça, en général, ils fonctionnent quand même)

Comme article = tuto = contenu, ça suffira comme ça pour le moment :)

**Comment by artragis** [comment]
pandoc est présent sur le serveur (comme ça je pourrais donner des logs 
en cas d'échec) c'est juste qu'il faut que je fasse une RAZ de la bdd.

**Comment by Vayel** [comment]
On attend pour la QA du coup ?

**Comment by artragis** [comment]
VOus pouvez QA.

2015-05-21 9:56 GMT+02:00 Vincent notifications@github.com:

**Comment by Vayel** [comment]
Pas de PDF on dirait : http://zds.francoisdambrine.me/articles2/58/qa58/

**Comment by artragis** [comment]
pandoc n'était pas dans le path, le problème c'est qu'il a des problème
avec les fonts et que je n'arrive pas à installer ttf-mscorefonts-installer

``` bash
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
!
! The font "Merriweather" cannot be found.
!
! See the fontspec documentation for further information.
!
! For immediate help type H <return>.
!...............................................

l.23     \setmainfont{Merriweather}

```

2015-05-21 11:45 GMT+02:00 Vincent notifications@github.com:

**Comment by pierre-24** [comment]
BIzarre. C'est quoi l'OS de ton serveur ?

**Comment by artragis** [comment]
debian wheezy

**Comment by pierre-24** [comment]
Très bizarre, c'est le mien aussi sur mon pc o_O

**Comment by artragis** [comment]
j'ai réussi à mettre les ttfmsfontinstaller mais ça fait toujours la même
erreur.

2015-05-21 14:46 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by Eskimon** [comment]
Au pire override les settings pour virer la font qui t'ennuie : https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/settings.py#L330

**Comment by pierre-24** [comment]
Ça me rapelle que Travis a une façon un peu spéciale de traiter la chose:

![screenshot from 2015-06-17 12 06 56](https://cloud.githubusercontent.com/assets/7889675/8204496/58568e60-14e9-11e5-8ae7-f2c615281fe8.png)

**Comment by artragis** [comment]
je n'ai plus d'erreur, mais pas de PDF non plus.

2015-06-17 12:06 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by Eskimon** [comment]
Tu aurais des logs éventuellement ?

**Comment by artragis** [comment]
je les trouve pas.

2015-06-17 12:51 GMT+02:00 Eskimon notifications@github.com:

**Comment by artragis** [comment]
Je les ai
! Missing $ inserted.
<inserted text>
                $
l.263 bits, il n'y a que \$ 2^{}{32} = 4 \times

pandoc: Error producing PDF from TeX source

**Comment by artragis** [comment]
Heureux de vous dire que sur cet _article_ ça marche du feu de dieu
http://zds.francoisdambrine.me/articles2/77/le-monde-de-la-signature-numerique/

Donc non seulement les articles produisent un PDF, mais en plus ça marche
pas trop mal (il a du mal avec les balises math inline cependant.

Par contre, il faudra qu'on revoie la politique de nommage de l'extrait
unique d'un article ancienne version car là ça fait un poil moche.

2015-06-17 13:34 GMT+02:00 francois dambrine artragis@gmail.com:

> Je les ai
> ! Missing $ inserted.
> <inserted text>
>                 $
> l.263 bits, il n'y a que \$ 2^{}{32} = 4 \times
> 
> pandoc: Error producing PDF from TeX source
>

**Comment by pierre-24** [comment]
Tout ce qui se passe du côté de pandoc, c'est pas notre problème.

Par contre, ton histoire de math, c'est peut-être rien (un bug coté pandoc) comme c'est peut -être quelque chose, t'as essayé avec quoi ?

Pour ce qui est du nommage de l'extrait, on pourrait l'appeller de différentes manières: "contenu", ou utiliser le titre de l'article :-)

**Comment by artragis** [comment]
La QA fonctionne, du coup je clos.
