### ISSUE TITLE
Problème validation contenu

### ISSUE THREAD

**Issue by poulp** [artragis/zds-site#59]
Si on met en validation un contenu sans remplir les champs de la fenetre qui s'ouvre on tombe sur cette erreur : 
`TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'`

**Comment by pierre-24** [comment]
Oh, très bonne remarque, et je sais exactement d'où ça vient. Par contre, je réfléchis encore à la manière la moins crade de régler ça (en gros, ça vient du fait que le formulaire est "invalide" lorsque le champ est vide et que donc, Django tente de repartir sur la page précédente, mais qu'il n'y a pas de "page précédente", parce que ce formulaire n'as pas de page à lui mais apparaît dans une fenêtre modale, d'où deux choix: lui donner une page à lui ou valider le formulaire autrement).

**Comment by poulp** [comment]
Aussi présent quand on rejette un contenu sans donner de justificatifs

**Comment by pierre-24** [comment]
... Et de manière générale sur la plupart des formulaires présents dans une modale ;)

**Comment by poulp** [comment]
Effectivement ^^

**Comment by pierre-24** [comment]
Note à moi-même sur celle-là:

``` python
# [...] le bon mixin
def form_invalid(self, form):
    errs = form.errors.as_data()
    if len(errs) > 0:
        message.error(self.request, errrs[0].message)
    # éventuelement jouer à deviner quel est le champ qui pose problème et pourquoi
    return redirect(la_bonne_url_qui_est_dans_le_form)     
```

**Comment by pierre-24** [comment]
Hop, normalement c'est réglé, ici. Jusqu'à ce qu'on trouve un autre formulaire qui aie besoin de ça.

**Comment by Vayel** [comment]
C'est OK ici, pour les tutoriels et les articles.

**Comment by pierre-24** [comment]
Vendu :)
