### ISSUE TITLE
Impossible de retirer son contenu de la validation

### ISSUE THREAD

**Issue by poulp** [artragis/zds-site#60]

**Comment by pierre-24** [comment]
Ah, oui, juste.

Question évidente, c'est possible en prod' et donc c'est bien une régression ?

**Comment by Eskimon** [comment]
> Question évidente, c'est possible en prod' et donc c'est bien une régression ?

Ca a été en pré-prod et marchait mal donc a été revert. Du coup je dois le QA ou pas ca ?

**Comment by pierre-24** [comment]
Ben là, je l'ai implémenté. Donc .... Oui ?

**Comment by Vayel** [comment]
La QA passe, pour les tutoriels et les articles.

Par contre, l'annulation fonctionne même quand un valido a réservé le contenu. J'ignore quel comportement on souhaite avoir. Je donnerais la possibilité, en ajoutant quand même un champ pour laisser un message au valido. De même pour la suppression.

**Comment by pierre-24** [comment]
Pour ce qui est de l'annulation malgré qu'un valido l'aie réservé, j'ai décidé que c'étais possible et je l'ai mise. Par défaut, l'admin recoit un message, mais effectivement pourquoi pas rajouter un champ "message" (d'autant que l'objet `Validation` possède de la place pour ça, à priori). Pour ce qui est de la suppression ... On peut y penser, mais dans ce cas, je dirais que l'auteur fait ce qu'il veut. Soit on interdit de virer un contenu si il est en validation (et alors, pour le supprimer, l'auteur doit le retirer de la validation, donc ce justifier le cas échéant), soit on se dit que l'auteur fait encore ce qu'il veux. Qu'est ce que t'en penses ?

**Comment by Vayel** [comment]
Je pense que dans les deux cas l'auteur fait ce qu'il veut mais que c'est le minimum de politesse d'en expliquer la raison au valido. Je ferais donc un truc du genre : 

Ce contenu est en cours de validation par X, qui appréciera de savoir pourquoi vous souhaitez le retirer de la validation/supprimer. 

Puis un bouton pour confirmer.

**Comment by pierre-24** [comment]
On peut tenter un truc comme ça :)

**Comment by pierre-24** [comment]
Là, c'est implémenté, le temps que ça arrive sur le serveur et tu pourra QA:

# Note de QA
- Créer un tuto avec user
- Demander la validation
- Avec admin, réserver le tuto
- Avec user, annuler la validation, tout d'abord sans préciser de texte (on se fait jeter), ensuite avec. + Vérifier qu'admin a bien reçu son MP
- Redemander une validation
- Re-réserver avec admin
- Avec user, supprimer le tuto, vérifier qu'on a bien le piti champ supplémentaire qui s'affiche, essayer tout d'abord en ne mettant rien (et on se fait jeter) et avec un texte idiot
- Vérifier qu'admin a bien recu son MP

**Comment by Eskimon** [comment]
QA++ : on en profite aussi pour vérifier que tout apparaît bien dans la page d'historique des validations

**Comment by Vayel** [comment]
Quand on se fait jeter, le message n'est pas très français : "Vous devez une raison pour l'annulation". Je mettrais un truc du genre : "Merci de fournir une raison à l'annulation.".

Le MP reçu par le validateur est bourré de fautes par contre. Je mettrais plutôt : "La validation du contenu X, que tu avais réservé, a été annulée par Y pour la raison suivante :"

"Vous devez justifier votre suppression !" est un peu impératif. Je mettrais plutôt : "Merci de fournir une raison à la suppression.".

Un petit souci : 
- Mise en validation par user
- Redirection de user sur la page du tutoriel
- Sur une autre page, réservation par admin
- Suppression par user sans avoir rechargé la page
- Pas de demande de message

Le MP reçu aurait plutôt cette forme : "La validation du contenu X, que tu avais réservé, a été annulée parce que le contenu a été supprimé par Y. La raison est la suivante :".

Au passage, Y désigne qui ? L'auteur qui supprime le tutoriel ou tous les auteurs du tutoriel supprimé ?

Au niveau de l'historique de validation, j'ignore ce qu'il soit contenir. Il est [ici](http://zds.francoisdambrine.me/validations/historique/47/qa60/). J'ai : 
- Demandé la validation avec user ("Demande de validation 1")
- Réservé avec admin
- Annulé avec user ("Annulation de la validation")
- Demandé la validation avec user ("Validation")
- Réservé avec admin
- Dé-réservé avec admin

**Comment by pierre-24** [comment]
Vayel, je vais finir par t'expliquer comment on corrige les fautes d'orthographes dans le code. J'ai beau savoir coder, l'orthographe n'est pas mon fort et tout ce que tu reportes, c'est moi qui fait de la m*** ([si jamais, les MPs sont stockés là](https://github.com/artragis/zds-site/tree/zep_12_double_stack/templates/tutorialv2/messages), au pire tu peux faire de PR avec l'outil d'édition de GH).

> Pas de demande de message

C'est "normal": on parle de tout un système qui fonctionne sans javascript: du coup, la forme de la modale est générée à la création de la page et bougera plus, donc c'est logique qu'il y aie pas demande de texte. Mais logiquement, t'as dû être empêché de le supprimer quand même.

(dans un futur lointain, on aura une API et une partie en JS, alors on pourra faire mieux)

> Au passage, Y désigne qui ? L'auteur qui supprime le tutoriel ou tous les auteurs du tutoriel supprimé ?

La personne qui supprime le tuto (parce que c'est lui qui déclenche le MP). Ce "pouvoir" est réservé aux auteurs, même les gens du staff ne peuvent pas supprimer un tuto/article.

> Au niveau de l'historique de validation, j'ignore ce qu'il soit contenir.

Moi il me semble logique, il y a un truc qui te choque ?

**Comment by Vayel** [comment]
Je sais utiliser git il n'y a pas de souci. C'est juste que j'ai la flemme de fouiller le code pour dénicher le texte à corriger.

Pour l'historique, je pensais plus à un truc du genre : 

| Date | Evènement |
| --- | --- |
| Il y a 3 heures | Demande de validation |
| Il y a 2 heures | Réservation par Bidule |
| Il y a 1h30 | Annulation de la validation pour la raison suivante : |
| Il y a 1 heure | Demande de validation |
| Il y a 1 heure | Réservation par Machin |
| Il y a 30 minutes | Refus de publication |
| Il y a 20 minutes | Demande de validation |
| Il y a 10 minutes | Réservation par Machin |
| Maintenant | Publication |

**Comment by pierre-24** [comment]
> Je sais utiliser git il n'y a pas de souci. C'est juste que j'ai la flemme de fouiller le code pour dénicher le texte à corriger.

Dans le dossier que je t'ai donné en lien, t'as tout les MPs (et également les messages de topics de la bêta), donc si il y a des fautes à corriger, c'est probablement par là qu'il faut commencer. Et j'acceillerai une PR sur le sujet avec plaisir, crois moi. L'autre partie (les messages renvoyés en cas d'erreurs) est un peu plus dispersé, mais les erreurs de formulaires (donc ces fameux message en orange) [sont "cachées" là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/forms.py). Sinon, bah il faut aller [regarder dans les vues](https://github.com/artragis/zds-site/tree/zep_12_double_stack/zds/tutorialv2/views) (ça à l'air bordelique, mais crois moi, c'est déjà plus rangé qu'avant).

> Pour l'historique, je pensais plus à un truc du genre : [...]

Ce que tu propose est très élégant mais se heurte à un petit problème "technique": un objet `Validation` contient le message de l'auteur, le statut (accepté, refusé, en cours de validation, toussa), le validateur éventuel, et son message éventuel. Donc une ligne du tableau = un objet `Validation`, et c'est pour ça que t'as la proposition de validation et son devenir sur la même ligne. Ce que tu propose est ceci dit faisable (tout est toujours faisable ;) ), mais je t'avoue que c'est pas une priorité (et ne le prend pas mal, hein, mais comme t'as pu le constater, on est en pleine phase _bugfix_ et ça n'arrête pas). Bref, c'est noté et si y'a le temps, ça y sera.

**Comment by Vayel** [comment]
> Bref, c'est noté et si y'a le temps, ça y sera.

C'est noté via cette _issue_ ? Si non, on peut fermer je pense. ^^

**Comment by pierre-24** [comment]
C'est noté dans ma tête, donc oui, on peut fermer.
