### ISSUE TITLE
Ajouter un auteur

### ISSUE THREAD

**Issue by poulp** [artragis/zds-site#61]
J'ai un soucis, la page s'assombrit mais la modal n’apparaît pas. J'ai fait un rebuild du front mais toujours pas, est ce que ça vous le fait aussi ?

**Comment by pierre-24** [comment]
Yep, et c'est un doublon de #54, c'est tout simplement pas encore implémenté :)

**Comment by poulp** [comment]
ah dsl j’ai pas fait gaffe

**Comment by pierre-24** [comment]
Pas de problème, le titre de l'issue en question est pas évident ^^
