### ISSUE TITLE
Intégrer la ZEP-12 à `load_fixtures`

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#64]
Il faudrait s'intégrer à la commande `python manage.py load_fixtures size=SIZE type=LIST_OF_TYPE` pour pouvoir générer à la demande des tutoriels et articles de tests, tout en éliminant les anciennes commandes qui utilise l'ancien code.

**Comment by artragis** [comment]
Crée un fichier yaml avec les différentes factory possible puis utilise load_factory_data, ça peut aller non?

**Comment by pierre-24** [comment]
Je découvre la fonctionnalité à peu près en même temps que la doc, mais en effet ;)

**Comment by artragis** [comment]
pourtant elle est documentée depuis très longtemps en fait. (install.md)

**Comment by pierre-24** [comment]
C'est fait ? *-*

**Comment by artragis** [comment]
non, ça sert juste à rien l'existant le fait très bien.

**Comment by pierre-24** [comment]
Je me suis mal exprimé. Par "avoir notre propre commande de fixtures", 
je voulais dire nous intégrer à la commande " 
pythonmanage.pyload_fixturessize=SIZEtype=LIST_OF_TYPE" :)

**Comment by artragis** [comment]
donc tu peux rouvrir.

2015-05-27 12:56 GMT+02:00 Pierre Beaujean notifications@github.com:

**Comment by artragis** [comment]
qui s'en occupe?

**Comment by pierre-24** [comment]
Je veux bien. Mais c'est du code pénible et chiant, donc il faut que je me motive :p

**Comment by pierre-24** [comment]
Voilà voilà :)

**Comment by artragis** [comment]
donc si je lance python manage.py load_fixtures type=content ça marche?

**Comment by pierre-24** [comment]
C'est
- `python manage.py load_fixtures type=tutorial2` pour les tutos
- `python manage.py load_fixtures type=article2` pour les articles
- `python manage.py load_fixtures type=comment` pour commenter tout ça (sans distinction ;) )

**Comment by artragis** [comment]
QA OK! une de moins, bravo !

**Comment by pierre-24** [comment]
_Nice_ la QA à 7h30 du mat' :-)

/me va prendre un café

**Comment by artragis** [comment]
Le courage, on le prend quand on l'a.

2015-07-09 8:40 GMT+02:00 Pierre Beaujean notifications@github.com:
