### ISSUE TITLE
Gérer le topic en cas de suppression

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#71]
Si un topic de bêta existe, rien n'est fait quand le contenu est supprimé ;)

(à mon avis, ça a ça place dans la vue correspondante et c'est très facile à régler ;) )

**Comment by artragis** [comment]
pour l'instant même dans le module de base rien n'est fait il me semble.

**Comment by pierre-24** [comment]
Je suis tout à fait d'accord ^^

**Comment by Eskimon** [comment]
Je vous propose deux idées, au moins l'une d'elles devraient être implémentée :
- Soit on se contente de fermer le sujet de beta
  - Bonus, Clem' écrit un message auto pour expliquer que le tuto a été supprimé
- Soit on vire le sujet en entier

Cependant, dans un souci de conserver les remarques des gens et respecter le temps passe a leur rédaction je serais plutôt partisan de la première solution

**Comment by pierre-24** [comment]
Moi je dit "option 1" !

**Comment by Eskimon** [comment]
Avec Bonus ?

**Comment by pierre-24** [comment]
Ben actuelement, c'est l'utilisateur lui-même qui poste ses messages d'update sur les sujets concernant les bêta. Après, changer l'utilisateur en bot dans ce cas particuiler, ça prend 15 secondes chrono, donc pourquoi pas ;)

**Comment by Eskimon** [comment]
Yep mais je trouverais ca plus propre que ce soit Clem' qui l'annonce perso.

Un truc tout con comme:

> Ce sujet de beta est fermé car l'auteur a décidé de supprimé son ouvrage.

**Comment by artragis** [comment]
Que faut-il faire ici (aka d'ousquonenest)?

**Comment by pierre-24** [comment]
Tout, parce que j'avais complètement oublié que ça existait (je regarde les "help wanted", en général ^^).

**Comment by artragis** [comment]
Codé, testé unitairement, manque plus que la QA !

(supprimer un contenu qui a un beta_topic fait que ce dernier est locké + le tag "supprimé" est ajouté + on modifie le premier poste).

**Comment by Vayel** [comment]
Au clic sur "Supprimer le tutoriel" : 

```
Environment:


Request Method: POST
Request URL: http://zds.francoisdambrine.me/contenus/supprimer/285/qa71/

Django Version: 1.7.7
Python Version: 2.7.9
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'django.contrib.humanize',
 'easy_thumbnails',
 'easy_thumbnails.optimize',
 'crispy_forms',
 'haystack',
 'munin',
 'social.apps.django_app.default',
 'rest_framework',
 'rest_framework_swagger',
 'corsheaders',
 'oauth2_provider',
 'zds.utils',
 'zds.pages',
 'zds.gallery',
 'zds.mp',
 'zds.article',
 'zds.forum',
 'zds.tutorial',
 'zds.tutorialv2',
 'zds.member',
 'zds.featured',
 'django.contrib.admin',
 'debug_toolbar')
Installed Middleware:
(u'debug_toolbar.middleware.DebugToolbarMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'zds.utils.ThreadLocals',
 'zds.middlewares.SetLastVisitMiddleware.SetLastVisitMiddleware',
 'zds.middlewares.profile.ProfileMiddleware')


Traceback:
File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  111.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/views/generic/base.py" in view
  69.             return self.dispatch(request, *args, **kwargs)
File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  29.             return bound_func(*args, **kwargs)
File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/db/transaction.py" in inner
  394.                 return func(*args, **kwargs)
File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  25.                 return func.__get__(self, type(self))(*args2, **kwargs2)
File "/home/francois/zds-site/zds/tutorialv2/views/views_contents.py" in dispatch
  291.         return super(DeleteContent, self).dispatch(*args, **kwargs)
File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  29.             return bound_func(*args, **kwargs)
File "/home/francois/zds-site/zds/member/decorator.py" in _can_write_and_read_now
  27.         return func(request, *args, **kwargs)
File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  25.                 return func.__get__(self, type(self))(*args2, **kwargs2)
File "/home/francois/zds-site/zds/member/decorator.py" in dispatch
  66.         return super(LoggedWithReadWriteHability, self).dispatch(*args, **kwargs)
File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/utils/decorators.py" in _wrapper
  29.             return bound_func(*args, **kwargs)
File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)
File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/utils/decorators.py" in bound_func
  25.                 return func.__get__(self, type(self))(*args2, **kwargs2)
File "/home/francois/zds-site/zds/member/decorator.py" in dispatch
  56.         return super(LoginRequiredMixin, self).dispatch(*args, **kwargs)
File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/views/generic/base.py" in dispatch
  87.         return handler(request, *args, **kwargs)
File "/home/francois/zds-site/zds-env/local/lib/python2.7/site-packages/django/views/generic/edit.py" in post
  259.         return self.delete(request, *args, **kwargs)
File "/home/francois/zds-site/zds/tutorialv2/views/views_contents.py" in delete
  329.             post.add_tags([u"Supprimé"])

Exception Type: AttributeError at /contenus/supprimer/285/qa71/
Exception Value: 'Post' object has no attribute 'add_tags'
```

**Comment by artragis** [comment]
oups :p j'ai pas mis à jour mon instance. Je le fais maintenant.

**Comment by Vayel** [comment]
C'est bon ici. Par contre, pour les mêmes raisons qu'on ne supprime pas le sujet, je propose de ne pas effacer le contenu du premier message. Ou bien on l'édite en précisant que le contenu n'existe plus, ou bien ou poste un message l'annonçant, avant de fermer le sujet.

**Comment by artragis** [comment]
c'est ce qui est fait, non?

**Comment by Vayel** [comment]
[Nop](http://zds.francoisdambrine.me/forums/sujet/35/qa71/).

Au passage, on écrit "bêta" et non "béta". ^^

**Comment by artragis** [comment]
Pourquoi on devrait garder le contenu du premier message puisque le lien 
ne mène plus à rien? C'est balot mais c'est comme ça. Le premier message 
précise que le contenu a été supprimé, c'est déjà amplement suffisant, non?

**Comment by Vayel** [comment]
Si l'auteur a édité ce message en apportant des précisions, peut-être souhaitera-t-il pouvoir retrouver ces précisions plus tard. C'est peu probable certes, mais on ne perd pas grand chose à les laisser, si ?

**Comment by pierre-24** [comment]
Je suis d'accord avec Vayel, il ne faut pas éditer le premier message, plusieurs auteurs se sont déjà plaints ;)

**Comment by artragis** [comment]
là ils **suppriment** leur tuto. Bon, je veux bien ne mettre qu'une 
partie de texte si ça vous chante, mais bon.

**Comment by Vayel** [comment]
Tu as raison : en principe, ils n'auront pas besoin de conserver le contenu du premier message. En principe. Ne pas l'effacer nous permet de gérer les cas où ce n'est pas vérifié, sans porter atteinte à la compréhension des membres. Autant le faire, non ? :)

**Comment by artragis** [comment]
J'ai modifié le comportement:

désormais on verrouille le sujet, mais en plus on y ajoute en tête du premier poste : 

``` text
[[a]]
|| Le contenu qui était en béta a été supprimé par son auteur.
```

mais on n'écrase pas la suite !

**Comment by pierre-24** [comment]
_perfect_ ;)

**Comment by artragis** [comment]
On peut fermer?

**Comment by Vayel** [comment]
b**ê**ta. :P

Et peut-être "par un de ses auteurs" ?

**Comment by Vayel** [comment]
Up

**Comment by artragis** [comment]
Ah oui, faut que je modifie "beta". Raaahhh, c'est rageant ces erreurs :p

2015-07-06 14:44 GMT+02:00 Vincent notifications@github.com:

**Comment by artragis** [comment]
voilà, la typo est corrigée.

**Comment by Vayel** [comment]
Tu me dis pour la QA (quand tu auras redémarré le serveur).

**Comment by artragis** [comment]
j'ai mis le bêta pas plus tardq ue maintenant, tu peux y aller;
(par contre le "l'un de ses auteurs" est omis volontairement car si nous 
avons bien codé, on ne supprime pas un tuto fait à plusieurs, du moins 
c'est comme ça que j'ai retenu, faut demander @pierre-24 et @spacefox)

**Comment by pierre-24** [comment]
En tout cas, ça me semble logique.

**Comment by Vayel** [comment]
Je crains malheureusement que ça ne fonctionne pas : http://zds.francoisdambrine.me/forums/sujet/42/qa71/

Oui, c'est une bonne méthode. Et de mémoire, j'avais QA ce fonctionnement.

**Comment by Vayel** [comment]
Je pense que tu n'as pas mis à jour le code, parce qu'il semble [bon](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_contents.py#L331).

**Comment by Vayel** [comment]
On est bon ici.

**Comment by pierre-24** [comment]
Cool :)
