### ISSUE TITLE
La visualisation de la version "hors-ligne" est bizarre pour un admin

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#73]
Pour reproduire le bug:
- Avec "user", créer et demander la publication d'un article
- Se connecter avec l'admin, publier le truc.
- Sur la version en ligne, cliquer sur "voir la version hors-ligne"
- Obtenir

![screenshot from 2015-04-27 16 16 51](https://cloud.githubusercontent.com/assets/7889675/7356861/fc81ac68-ecf8-11e4-8ac3-5902f777a17c.png)

Et là, il y a plusieurs choses qui ne vont pas, mais le plus "important", c'est que le menu de gauche est bizarre. Je pense qu'on donne pas les bon droit au bon moment (voir variable `can_edit` ?)

À voir sur http://zds.francoisdambrine.me/contenus/3/philae-a-la-recherche-de-lorigine-de-la-chiralite-du-monde/

**Comment by artragis** [comment]
oui, je ne fais qu'un "can_edit" et pas un "can_edit and permisions...." au début c'était "volontaire", mais en fait c'est plutôt un bug qu'autre chose. Je fixe ça dès que possible.

**Comment by artragis** [comment]
fixed.

Désolé du dérangement.

**Comment by pierre-24** [comment]
Genre, c'est notre "bébé", donc ça m'ennuie pas, loin de là. Je préfère trouver les bugs maintenant qu'en phase finale de QA ou pire, en prod' :)
