### ISSUE TITLE
intégrer les indicateurs dans le profile

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#74]
le nombre de tuto "en cours", "en validation", "publié" idem pour les artilces.

**Comment by pierre-24** [comment]
Bien vu !

**Comment by artragis** [comment]
Les indicateurs sont là mais les liens ne sont pas forcément bon, notamment j'obtiens une erreur incompréhensible ici : http://zds.francoisdambrine.me/contenus/liste-tutoriels/1/

**Comment by GerardPaligot** [comment]
Ma PR s'en charge
