### ISSUE TITLE
Tri sur les contenus

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#76]
Il faudra remettre ça:

![screenshot from 2015-04-30 10 28 02](https://cloud.githubusercontent.com/assets/7889675/7414918/b072bf42-ef23-11e4-8cfd-baefaaeba0e5.png)

Sinon, c'est une régression !

**Comment by artragis** [comment]
done

**Comment by Eskimon** [comment]
### QA Time \o/
- L'ordre alphabétique semble inversé, normal ?
- L'ordre par date de création semble inversé, normal ?
- J'ai pas l'impression que le tri par date de modification fonctionne comme il faut (on dirait qu'il retourne par date de création mais je suis pas sur)...
- Vu que tout est sur une seule page il faudrait probablement des checkboxs dans la barre latérale pour par exemple "afficher les articles" et "afficher les tutos" et coché par défaut je suppose...

**Comment by artragis** [comment]
> L'ordre alphabétique semble inversé, normal 

Hum, c'est comme ça que je l'ai codé, mais non, pas normal. C'est pas ce que je voulais faire, et c'est pas logique

> L'ordre par date de création semble inversé, normal ?

Oui, totalement voulu, je pense que quand on trie selon cette date c'est pour avoir plus facilement accès au dernier contenu créé, non? Sinon, je peux le modifier aussi.

> J'ai pas l'impression que le tri par date de modification fonctionne comme il faut (on dirait qu'il retourne par date de création mais je suis pas sur)...

Nope, ça trie bien par dernière modif, c'est juste que sur le site de test, il y a fort à parier que les modifications se sont faites en une fois.

Donc : dois-je modifier le tri par date? Une fois que j'aurai cette réponse je ferai un commit qui répare le tri alphabétique, et qui implémente ladite réponse.

**Comment by Eskimon** [comment]
> Nope, ça trie bien par dernière modif, c'est juste que sur le site de test, il y a fort à parier que les modifications se sont faites en une fois.

J'utilise ma version local et donc fait de la modification comme je souhaite.

Je viens de penser, c'est bien censé marcher si les contenus sont tous en brouillon non ?

sinon ok pour le tri par date, je comprend l'argument et n'y avait pas pensé

**Comment by artragis** [comment]
> Je viens de penser, c'est bien censé marcher si les contenus sont 
> tous en brouillon non ?

En fait ça marche pour tous les contenus. Ce que je ne comprends pas 
c'est que j'ai testé et que j'ai bien l'ordre de modification qui est 
pris en compte.

Ensuite pour la date : sur la prod on est sur l'ordre "du plus ancien au 
plus récent", je propose donc qu'on garde ce comportement là et tant pis 
pour mon argument.

**Comment by artragis** [comment]
C'est fait, tu peux valider?

**Comment by Eskimon** [comment]
Les filtres sont bon MAIS c'est quoi l'ordre de tri par défaut quand on a pas de critères ? J'ai l'impression que c'est ante-alphabétique non ?

**Comment by artragis** [comment]
> Les filtres sont bon MAIS c'est quoi l'ordre de tri par défaut quand on a
> pas de critères ? J'ai l'impression que c'est ante-alphabétique non ?

je dirais ordre de création.

**Comment by Eskimon** [comment]
> je dirais ordre de création.

Je pense pas

![screenshot from 2015-05-07 14 50 17](https://cloud.githubusercontent.com/assets/761168/7515573/73b8c0c4-f4c8-11e4-9413-e991acdc4c67.png)

**Comment by artragis** [comment]
En effet, en vérifiant le code : 

``` python
    sorts = {
        '': lambda q: q.order_by('-title'),
        'creation': [lambda q: q.order_by('creation_date'), _(u"Par date de création")],
        'abc': [lambda q: q.order_by('title'), _(u"Par ordre alphabétique")],
        'modification': [lambda q: q.order_by('-update_date'), _(u"Par date de dernière modification")]
    }
```

**Comment by Eskimon** [comment]
Faudrait juste virer le `-` ^^

**Comment by artragis** [comment]
Voilà qui est fait.

**Comment by Eskimon** [comment]
Approved :) ticket fully tested je pense (sauf si tu me demandes de tester aussi le comportement des articles par rapport aux tutos)

**Comment by artragis** [comment]
Parfait, je dépile !

**Comment by pierre-24** [comment]
Hep, sur la dernière version en date, le tri n'est plus proposé:

![screenshot from 2015-05-16 08 00 59](https://cloud.githubusercontent.com/assets/7889675/7666049/c948e8e0-fba1-11e4-8c37-39e86c2c68c3.png)

**Comment by artragis** [comment]
il doit y avoir un problème dans le template.

**Comment by GerardPaligot** [comment]
Ma PR s'en charge mais je n'ai pas les bonnes icônes pour chaque filtre. Puisque les filtres (et les tris) sont générés par le back, ça vous semble déconnant que le back sache quel icone doit avoir chaque filtre ? (Sachant qu'il connait déjà son texte)

**Comment by pierre-24** [comment]
Comme j'ai dit, pour moi c'est probablement la bonne solution.

**Comment by pierre-24** [comment]
On est bon :)
