### ISSUE TITLE
Robots.txt pour les téléchargements

### ISSUE THREAD

**Issue by Eskimon** [artragis/zds-site#77]
Cf ce [ticket](https://github.com/zestedesavoir/zds-site/issues/1999) et sa [PR](https://github.com/zestedesavoir/zds-site/pull/2610).

L'idée est d’empêcher le referencement des contenus sans valeur ajoutée (mise en page) donc de ne laisser que les pdf et epub dans les moteurs de recherches

**Comment by pierre-24** [comment]
Dans l'idée, on pourrait éventuellement regarder pour "tricher" et rajouter l'extention PDF/le reste, pour que les moteurs de recherche les considèrent comme tels (je pensais qu'ils regardait au `mimetype`, il semblerait que non).

À condition que ça soit pas trop compliqué, bien entendu :)

**Comment by Eskimon** [comment]
ca serait propre d'avoir l'extension, mais si le code est le même que celui d'origine ca risque d’être sale à implémenter...

**Comment by pierre-24** [comment]
Je vais voir ce que je peux faire pour ça. C'est surtout une question d'url, en fait, plus qu'autre chose, à mon sens. Le reste, c'est récupérer le bon fichier ;)

**Comment by pierre-24** [comment]
(j'aime bien [l'idée de Situphen](https://github.com/zestedesavoir/zds-site/pull/2610#issuecomment-97903113) )

**Comment by pierre-24** [comment]
Bon, l'idée a été implémentée. Du coup, comment qu'on empêche l'indexation du HTML ?

**Comment by Eskimon** [comment]
Avec le robots.txt ?

**Comment by pierre-24** [comment]
Oui, je me doute ^^ , mais `DISALLOW /articles/*.html`, ça marche ?

**Comment by Eskimon** [comment]
Ah bonne question... et apparemment il y a une zone d'ombre sur le sujet http://stackoverflow.com/questions/6306763/regexp-for-robots-txt

**Comment by pierre-24** [comment]
Ah. Bon ... Deux solutions: soit on réécrit les urls en mettant `/contenus/telecharger/pdf/{pk}/machin.pdf` et alors on peut faire une règle assez simple, soit on croise les doigts pour que les "autres bots" viennent pas nous embêter :s

**Comment by Eskimon** [comment]
Au pire on fait ca surtout pour le referencement non ? Donc si les "autres bots" des moteurs que personne n'utilise reference quand meme c'est pas dramatique.
Mais sinon j'apprecie l'idee d'avoir les urls comme tu le proposes, je trouve ca plus propre donc si c'est pas trop de boulot je suis votant pour ca.

**Comment by pierre-24** [comment]
Changer une URL, ça prend 2 secondes avec Django, donc je vais regarder à ça :)

**Comment by Eskimon** [comment]
Ca en est ou ici ? Attendre que la generation des contenus marche ?

**Comment by pierre-24** [comment]
C'est ça :)

(c'est en cours, j'ai un code fonctionnel sur une branche à moi, je drois juste cadenasser le tout avec des T.U.)

**Comment by pierre-24** [comment]
Voilà. Ce serai de toute façon difficile à QA, à moins de demander à Google de passer sur le serveur d'artragis o_O
