### ISSUE TITLE
Utiliser le bon template de pagination

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#80]
Voir [ici](https://github.com/zestedesavoir/zds-site/issues/2597#issuecomment-98322916), faudrait qu'on emploit `paginator.html` au lieu de `pagination.part.html` :o

**Comment by artragis** [comment]
done

**Comment by pierre-24** [comment]
Je la laisse ouverte, parce qu'il faut que je fasse de même sur la page de la ZEP-03 :)

**Comment by pierre-24** [comment]
(d'ailleurs, je me l'assigne pour pas oublier)

**Comment by artragis** [comment]
Comme tu le sens.

**Comment by pierre-24** [comment]
Ah, oui, et pour la pagination des chapitres sur les tutos, aussi :)

**Comment by pierre-24** [comment]
Hop, réglé par #91 :)

**Comment by GerardPaligot** [comment]
QA ok pour moi

**Comment by pierre-24** [comment]
C'est bon :)
