### ISSUE TITLE
URL des bêta

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#86]
Au final, Firm1 avait fini par implémenter le fait que toutes les bêtas puissent être appellée par `/beta/`. Comme on le voulais et que ça serait une régression de toute façon, ben ... À faire :)

(ça devrait pas être très compliqué, d'ailleurs ...)

**fait par #101**
# Note QA
- Créer un article, le remplir un minimum et le passer en bêta
- Vérifier qu'on a bien recu un MP indiquant qu'un sujet avait été créé pour la bêta dans le forum
- Vérifier qu'on a bien, dans ce post, un lien du type `http://127.0.0.1:8000/contenus/beta/{pk}/{slug}/`, et qu'il est accessible pour un utilisateur qui n'est pas du staff et de l'auteur
- Refaire de même avec un moyen ou un big-tuto (pour rappel, article et mini-tuto, c'est _kiff_) et vérifier que ou que ce soit qu'on clique, on garde bien une URL en `/beta/`, c'est à dire: sur les titres, sur les sous-titres, sur le sommaire à gauche et le fil d'ariane (toujours avec un utilisateur qui n'est pas l'auteur).
- Signaler des fautes à l'auteur et vérifier que c'est bien le lien en `/beta/` qui est employé pour ce faire (sur le tuto lui-même et sur un chapitre dudit-tuto).

**Comment by pierre-24** [comment]
Réglé par #101. N'hésitez pas à vérifier partout (!)

**Comment by Vayel** [comment]
Peux-tu préciser le premier post ? Que faut-il faire exactement au niveau de la QA ?

**Comment by pierre-24** [comment]
J'ai édité le premier post en conséquence :)

**Comment by Vayel** [comment]
```
Page not found (404)
Request Method:     POST
Request URL:    http://zds.francoisdambrine.me/contenus/activer-beta/36/qa86/
```

**Comment by pierre-24** [comment]
Vayel: 1 - ZEP-12: 0. 

Je vais voir ce que je peux faire :)

**Comment by pierre-24** [comment]
... Rien, faut juste attendre que @artragis remonte la dernière version en date sur son serveur :)

**Comment by artragis** [comment]
mon serveur est tout à fait à jour.

**Comment by pierre-24** [comment]
Je veux bien te croire, mais alors y'a un truc à creuser. Sur le serveur, pas moyen de mettre un truc en bêta, en local, j'y arrive comme je veux o_O

**Comment by pierre-24** [comment]
Ceci étant dit, @Vayel a oublié de mentionner un truc très intéréssant, c'est que `No Forum matches the given query.`. Ce qui signifie que cette 404 est très probablement balancée [par cette ligne là](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/views/views_contents.py#L1047). Du coup ... ?

**Comment by artragis** [comment]
c'était ça: l'id du forum de beta était incorrect

**Comment by Vayel** [comment]
Il y a un problème au niveau de ce que vous appelez, je crois, le fil d'Arianne, _i.e._ la barre sous le logo du site : Accueil > Tutoriels > Nom du tuto
- http://zds.francoisdambrine.me/contenus/beta/39/qa86tuto/p-1/ (QA86tuto)
- http://zds.francoisdambrine.me/contenus/beta/39/qa86tuto/p/c/ (P)

**Comment by pierre-24** [comment]
Tout à fait (mais il m'as fallu du temps pour comprendre ce que tu voulais dire): les URLs ne renvoient pas sur ce qu'elles sont censées renvoyer. J'ajoute que le bug n'est présent que pour les URLs des bêtas (donc ça ressemble furieusement à un bug coté _back_)

**Comment by pierre-24** [comment]
Corrigé, normalement

**Comment by Vayel** [comment]
QA OK.

**Comment by pierre-24** [comment]
Et une de moins, merci @Vayel :)
