### ISSUE TITLE
Rajouter l'header qui va bien pour l'encodage du markdown

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#89]
Lorsqu'on télécharge la version markdown d'un tuto publié, il est balancé sans encodage, donc le navigo assume ISO-machin-chose par défaut et c'est moche. Je parie que préciser l'encodage tient en deux lignes ;)

**Comment by pierre-24** [comment]
(une des deux lignes étant un `if`)

**Comment by Eskimon** [comment]
Je confirme la bonne presence du header :)

![screenshot from 2015-05-07 11 17 33](https://cloud.githubusercontent.com/assets/761168/7512091/b2960068-f4aa-11e4-86e3-c594654358c3.png)

**Comment by artragis** [comment]
Ok, je ferme.
