### ISSUE TITLE
une introduction vide peut faire bugger la publication

### ISSUE THREAD

**Issue by artragis** [artragis/zds-site#90]
Avec admin, 
- tenter de valider le tuto suivant : http://zds.francoisdambrine.me/contenus/4/blablabla/
- pleurer

@pierre-24 
##  Aide QA
- créer un tuto
- créer l'architecture suivante

```
P1
    C1
P2
P3
```
- déplacer C1 avant P2 
- lancer la publication du tuto

**Comment by pierre-24** [comment]
En soi, je considère ça comme une "bonne chose", parce que ça veux dire que mon mécanisme de protection contre la "validation de n'importe quoi" fonctionne. Évidement, dans ce cas-ci, c'est un peu trop efficace et c'est un bug ;)

**Comment by pierre-24** [comment]
(ps: le problème, c'est pas l'intro vide, c'est le conteneur vide)

**Comment by artragis** [comment]
alors il faudra le corriger quand même parce que ce genre de chose n'est
pas rare dans le corpus déjà existant sur zds (cf tutoriel ASP.NET)

**Comment by pierre-24** [comment]
On est bien d'accord que c'est un test un peu hyperactif, dans ce cas là :p

**Comment by pierre-24** [comment]
... Et en fait, non ! J'arrive à le publier en local. Sauf que je sais d'où viens le problème: quand on regarde au `manifest.json` contenu dans l'archive, on voit ça:

![screenshot from 2015-05-06 14 27 33](https://cloud.githubusercontent.com/assets/7889675/7500489/07fac66a-f3fc-11e4-870f-508618e8e6a4.png)

Les lignes que j'ai sélectionné sont pas logique, et j'en déduis (au delà du titre) que ce conteneur a été déplacé, mais que certaines infos ont pas été mises à jour ! À mon avis, il manque un `container.update_children()` dans une des fonctions de mouvement ;)

**Comment by artragis** [comment]
en effet, c'est tout à fait ça !

**Comment by pierre-24** [comment]
C'est pas "réglé" par ton dernier commit en date, ça ?

**Comment by artragis** [comment]
Je passe en "need qa".

**Comment by Vayel** [comment]
Au moment de la publication de `QA 90` j'obtiens : 

```
LargeZipFile at /validations/accepter/11/

Filesize would require ZIP64 extensions

Request Method:     POST
Request URL:    http://zds.francoisdambrine.me/validations/accepter/11/
Django Version:     1.7.7
Exception Type:     LargeZipFile
Exception Value:    

Filesize would require ZIP64 extensions

Exception Location:     /usr/lib/python2.7/zipfile.py in _writecheck, line 1037
Python Executable:  /home/francois/zds-site/zdsenv/bin/python
Python Version:     2.7.3
Python Path:    

['/home/francois/zds-site',
 '/home/francois/zds-site/zdsenv/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg',
 '/home/francois/zds-site/zdsenv/lib/python2.7',
 '/home/francois/zds-site/zdsenv/lib/python2.7/plat-linux2',
 '/home/francois/zds-site/zdsenv/lib/python2.7/lib-tk',
 '/home/francois/zds-site/zdsenv/lib/python2.7/lib-old',
 '/home/francois/zds-site/zdsenv/lib/python2.7/lib-dynload',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-linux2',
 '/usr/lib/python2.7/lib-tk',
 '/home/francois/zds-site/zdsenv/local/lib/python2.7/site-packages',
 '/home/francois/zds-site/zdsenv/local/lib/python2.7/site-packages/git/ext/gitdb',
 '/home/francois/zds-site/zdsenv/local/lib/python2.7/site-packages/gitdb/ext/smmap']

Server time:    sam, 16 Mai 2015 17:44:15 +0200
```

Mais le tutoriel a été publié...

**Comment by pierre-24** [comment]
MMmh, @artragis, tu aurais tenté de rajouter l'export en zip récement ?

**Comment by artragis** [comment]
oups, oui. semblerait qu'une extension soit obligatoire, je vois comment 
on peut faire.

**Comment by artragis** [comment]
mais je vois pas comment c'est possible que ça demande autant

**Comment by artragis** [comment]
ça devrait être corrigé.

**Comment by pierre-24** [comment]
Là, t'as une erreur de type "fichier existe déjà" :)

**Comment by artragis** [comment]
je dirais que ce sont les artéfact de l'ancienne publication. Peux-tu 
tester avec un autre tuto?

**Comment by Vayel** [comment]
Avec un tutoriel `QA 90`, il me dit `File exists`. 

Quand je fais la QA avec `QA 90 pouet pouet` je reçois un `504 Gateway Time-out` au moment de la publication mais le tutoriel est quand même mis en ligne.

**Comment by artragis** [comment]
le problème de l'archive n'est pas résolu. Il me crée une archive 
récursive qui atteint 58 Go là.

**Comment by artragis** [comment]
autrement dit, need help pour comprendre où ça merde dans la création du 
zip.

**Comment by pierre-24** [comment]
Simple idée (j'ai pas regardé le code): tu zippe le dossier complet, qui contient l'archive, qui cobtient le dossier qui contient l'archive ?

Dans tout les cas, pour moi, il faut éviter de réinventer la roue: t'appelle la méthode qui zippe une version donnée dans un draft et tu le stocke dans le dossier qui va bien (`get_extra_content_directory()` ?)

**Comment by pierre-24** [comment]
[Cette ligne là en particulier](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/utils.py#L462) est bizarre et je suis pas sur qu'elle fait bien ce que tu penses qu'elle doit faire. De manière générale, tu saurais m'expliquer en français ce que fait cette fonction ? (par exemple, j'ai l'impression qu'elle va aller chercher la version _draft_ et pas la version de validation, si les deux sont différentes)

**Comment by artragis** [comment]
ah, je savais même pas que ça existait. On a vraiment trop bien 
travaillé en fait :p

**Comment by Vayel** [comment]
La QA passe, avec [ce tutoriel](http://zds.francoisdambrine.me/tutoriels2/26/90qa/).

Par contre, quand j'utilise des noms comme `QA 90`, `QA90`, il me dit que ça existe déjà. Probablement dû aux bugs ci-dessus, corrigés depuis.

**Comment by artragis** [comment]
oui c'est dû à un mauvais nettoyage du serveur de ma part.

Merci pour cette QA. je clos.
