### ISSUE TITLE
Erreur 404 après la modification du titre

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#93]
[Comme l'as très bien fait remarquer Firm1](https://zestedesavoir.com/forums/sujet/846/zep-12-refonte-du-principe-des-tutoriels-et-articles/?page=15#p55915), on est pas encore tout à fait au point coté _slug_ qui change. De manière générale, 
- Créer un contenu
- Changer son titre (et donc son slug)
- Mettre en bêta/valider et ce manger des 404 sur les versions en validation/bêta

Bref, y'a encore des trucs à mettre pour que notre `SingleContentViewMixin` se comporte convenablement ;)

**Comment by pierre-24** [comment]
Réglé par #98 :)

**Comment by artragis** [comment]
QA validée, théoriquement.
