### ISSUE TITLE
Erreur 500 sur un contenu qui n'existe pas ?

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#94]
On a une erreur 500 sur http://zds.francoisdambrine.me/contenus/100/s/ ... Parce qu'on récupère un objet qui vaut `None` et qu'on vérifie pas avant de tenter d'accéder à un de ces attributs qu'il l'est.

**Comment by artragis** [comment]
Le problème se trouve [ici](https://github.com/artragis/zds-site/blob/zep_12_double_stack/zds/tutorialv2/mixins.py#L54)

Le code à ajouter est simplement `if self.object is None: raise Http404`. Il faudra aussi ajouter le test unitaire correspondant.

**Comment by artragis** [comment]
ça devrait être bon !

**Comment by pierre-24** [comment]
Eh, nice, ça veut dire qu'en fait, t'avance sur l'édition d'une réponse, en fait, j'avais pas vu :-)

**Comment by pierre-24** [comment]
... Et sinon, oui, c'est bon :)

**Comment by artragis** [comment]
j'avance, dans le sens où tu n'as plus le "unexisting template".
par contre j'arrive pas à mettre le lien d'édition et la citation fait 
la merde.
bref j'ai du taf ce week end.
