### ISSUE TITLE
Repartir sur une ancienne version

### ISSUE THREAD

**Issue by pierre-24** [artragis/zds-site#95]
En prod, il semblerai qu'il soit possible de repartir sur d'ancienne version, tout du moins pour des extraits. Comme je découvre la fonctionnalité, je sais pas dire si on repart sur l'ancienne version juste pour l'extrait ou pour tout le contenu (et ce que je viens de dire n'est absolument pas clair). Bref, _stay tunned_.

**Comment by pierre-24** [comment]
(faudrait un label "régression", non ?)

**Comment by artragis** [comment]
je ne sais toujours pas utiliser cette fonctionnalité, alors la coder ...

**Comment by pierre-24** [comment]
Mouais. Elle est complètement buggée en prod' !
- Déjà, pas moyen d'éditer l'intro/la conclusion du tuto lui-même quand tu visites une version précédente, t'as le bouton "voir la version brouillon", et c'est tout
- C'est pas possible sur une partie: le lien "éditer" n'as pas l'attribut `&version=qqch`
- C'est possible (par miracle) sur un chapitre, dans le sens ou `&version=qqch` est bien dans le lien. Par contre, tu te manges quand même le texte de la dernière version
- Fail total sur un extrait (pas de  `&version=qqch`)
- De manière générale, quand on ajoute le  `&version=qqch` à la main, on revient pas pour autant en arrière

@Firm1 : quand est ce que cette fonction a été codée et pourquoi c'est aussi rempli de _fail_ ? (je précise que j'ai été faire mes test sur la bêta). Est ce que cette fonctionnalité existe vraiment ? o_O

**Comment by firm1** [comment]
> quand est ce que cette fonction a été codée

depuis le début.

> pourquoi c'est aussi rempli de fail ?

j'imagine que les regressions se sont accumulées, et vu qu'il y'a pas e TU dessus

> Est ce que cette fonctionnalité existe vraiment ?

visiblement ça ne fonctionne plus.

**Comment by pierre-24** [comment]
Aw. fonctionnalité-non-documentée-non-testée-unitairement-et-inconnue-du-grand-public, tu m'étonnes qu'on aie fini par la faire "disparaître" ^^

**Comment by pierre-24** [comment]
À réflexion, je vais même aller plus loin: puisque je n'ai aucune idée de comment est censé fonctionner une telle fonctionnalité, puisqu'elle a physiquement disparu du dépôt principal depuis un certain temps (je viens de remonter l'historique, on commence déjà à voir des régression apparaître au moment de la 1.2), ça rentre dans la catégorie "évolution" _de facto_ et je considère que ça sort du cadre de la ZEP-12.

Tant pis.

**Comment by Eskimon** [comment]
Approved !
