### ISSUE TITLE
Citer une réaction d'un tutoriel => Erreur 500

### ISSUE THREAD

**Issue by firm1** [artragis/zds-site#96]
**Scénario** : 
- Aller sur un tutoriel publié : [la par exemple](http://zds.francoisdambrine.me/tutoriels2/11/les-promesses-en-javascript/?page=1#p13)
- Ecrire un commentaire
- Tout de suite après, citez votre propre commentaire

**Problème** : Erreur 500

Je finis sur l'url : `http://zds.francoisdambrine.me/contenus/reactions/get-json/13/`

**Comment by pierre-24** [comment]
Yep, on sais, et de manière générale, aucun de ces boutons là ne fonctionne : #57 :)

**Comment by firm1** [comment]
ahhh, j'ai pas lu toutes les issues alors.

Je ferme.
